### ISSUE TITLE
Error doing job: Exception in callback WebSocketClient._on_close(<Task cancell...client.py:62>>)

### ISSUE THREAD

**Issue by theastadler** [fuatakgun/eufy_security#1017]
It was working fully for a day, and since today I keep getting a notification to reconfigure it. 

It asks for the capcha, it tries to inisializate and it goes back to reconfigure. 

This error originated from a custom integration.

Logger: homeassistant
Source: custom_components/eufy_security/eufy_security_api/web_socket_client.py:63
Integration: Eufy Security (documentation, issues)
First occurred: 23:46:20 (1 occurrences)
Last logged: 23:46:20

Error doing job: Exception in callback WebSocketClient._on_close(<Task cancell...client.py:62>>)
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/config/custom_components/eufy_security/eufy_security_api/web_socket_client.py", line 81, in _on_close
    self.close_callback(future)
  File "/config/custom_components/eufy_security/eufy_security_api/api_client.py", line 308, in _on_close
    _LOGGER.debug(f"on_close - executed - {future} = {future.exception()}")
                                                      ^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/eufy_security/eufy_security_api/web_socket_client.py", line 63, in _process_messages
    async for msg in self.socket:
  File "/usr/local/lib/python3.11/site-packages/aiohttp/client_ws.py", line 297, in __anext__
    msg = await self.receive()
          ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/client_ws.py", line 229, in receive
    msg = await self._reader.read()
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/streams.py", line 657, in read
    return await super().read()
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/streams.py", line 616, in read
    await self._waiter
asyncio.exceptions.CancelledError

and 

Logger: homeassistant.config_entries
Source: config_entries.py:426
First occurred: 23:46:41 (1 occurrences)
Last logged: 23:46:41

Config entry '127.0.0.1' for eufy_security integration could not authenticate: Captcha code is required, please revalidate on Integrations page

**Comment by fuatakgun** [comment]
follow the bug template and fill out all required fields
