### ISSUE TITLE
Error Config flow could not be loaded: 500 Internal Server Error Server got itself in trouble

### ISSUE THREAD

**Issue by ttuuxxeerr** [fuatakgun/eufy_security#1065]
Please check existing (open or closed) issues before creating a new one. (https://github.com/fuatakgun/eufy_security/issues?q=is%3Aissue+)

If this is not an issue, you can use `Discussions` (https://github.com/fuatakgun/eufy_security/discussions) section.

**Describe the bug**

I followed the procedure described in the instructions, however at the step to configure Eufy security I got the following message:: **Error. Config flow could not be loaded: 500 Internal Server Error Server got itself in trouble**

**To reproduce**

1. Go to 'Settings', 'Device & services',  Dufy Security
3. Click on 'CONFIGURE'
5. See error **Error. Config flow could not be loaded: 500 Internal Server Error Server got itself in trouble**

**Expected behavior**

I expect to see the configuration screen as described in the guide.

**Additional information**

Go to Settings -> System -> Repairs -> Click on 3 dots (...) -> System Information and get Version and Installation Type to below fields;
- Home Assistant Installation Type (OS - Supvervised - Core):  Home Assistant OS
- Home Assistant Core Version:  core-2024.1.0
- Eufy Security Add-on Version:  eufy-security-ws (1.7.1)
- Eufy Security Integration Version: 8.0.0

Hardware Information;
- Camera Model: Dufy homebase 2-4301 with 3 x eufy cam 2C

- Live Streaming Protocol (RTSP/P2P):  RTSP

- Debug Logs from Home Assistant (https://github.com/fuatakgun/eufy_security/discussions/624) - Without this, I will automatically resolve this issue
  
2024-01-04 09:13:54.397 DEBUG (MainThread) [custom_components.eufy_security.config_flow] eufy_security EufySecurityOptionFlowHandler - {'host': '127.0.0.1', 'port': 3000}
2024-01-04 09:13:54.397 DEBUG (MainThread) [custom_components.eufy_security.config_flow] eufy_security EufySecurityOptionFlowHandler - {}
2024-01-04 09:13:54.398 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
File "/usr/local/lib/python3.11/site-packages/aiohttp/web_protocol.py", line 452, in _handle_request
resp = await request_handler(request)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/aiohttp/web_app.py", line 543, in _handle
resp = await handler(request)
^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/aiohttp/web_middlewares.py", line 114, in impl
return await handler(request)
^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 85, in security_filter_middleware
return await handler(request)
^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware
return await handler(request)
^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
return await handler(request)
^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 80, in ban_middleware
return await handler(request)
^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 233, in auth_middleware
return await handler(request)
^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/components/http/headers.py", line 31, in headers_middleware
response = await handler(request)
^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 149, in handle
result = await handler(request, **request.match_info)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/components/http/decorators.py", line 63, in with_admin
return await func(self, request, *args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 213, in post
return await super().post(request)
^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 72, in wrapper
result = await method(view, request, data, *args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 71, in post
result = await self._flow_mgr.async_init(
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 285, in async_init
flow = await self.async_create_flow(handler, context=context, data=data)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/config_entries.py", line 1878, in async_create_flow
return handler.async_get_options_flow(entry)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/eufy_security/config_flow.py", line 62, in async_get_options_flow
return EufySecurityOptionFlowHandler(config_entry)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/eufy_security/config_flow.py", line 33, in __init__
vol.Optional(ConfigField.rtsp_server_port.name, default=self.config.rtsp_server_port): cv.port,
^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/enum.py", line 784, in __getattr__
raise AttributeError(name) from None
AttributeError: rtsp_server_port
- Logs from Eufy Security Add-on (either from Add-ons page of Home Assistant or Docker output):

**Additional context**

Add any other context about the problem goes here. Mainly, share everything as log files and use screenshots as last resort.

I tried to remove everything and start again. Also remove the 2FA on my account.

**Comment by rashors** [comment]
be sure that you add:

COUNTRY= UK
TZ= Europe/London

That whas my prolblem.

**Comment by ttuuxxeerr** [comment]
> be sure that you add:
> 
> COUNTRY= UK TZ= Europe/London
> 
> That whas my problem.

thanks for your comment. Where exactly did you add the two lines ?

Regards
