### ISSUE TITLE
Getting Error When Trying to Open the CONFIGURE From the Integration Page

### ISSUE THREAD

**Issue by eufysecurity** [fuatakgun/eufy_security#1068]
**Describe the bug**

When clicking on CONFIGURE on the integration page of eufy security it give an error: Config flow could not be loaded: 500 Internal Server Error Server got itself in trouble
![2024-01-04 17_58_35-Window](https://github.com/fuatakgun/eufy_security/assets/106836726/5420ba80-3aac-4d73-807b-267230849140)

**To reproduce**

1. Go to 'Settings'
2. Click on 'Device & services'
3. Click on 'Eufy Security'
4. Click on 'CONFIGURE'
5. Error Appears

**Expected behavior**

To open the Configuration panel

**Additional information**

Go to Settings -> System -> Repairs -> Click on 3 dots (...) -> System Information and get Version and Installation Type to below fields;
- Home Assistant Installation Type (OS - Supvervised - Core): Home Assistant OS
- Home Assistant Core Version: core-2024.1.0
- Eufy Security Add-on Version: 1.7.1
- Eufy Security Integration Version: v8.0.0

Log information:
2024-01-04 18:08:01.518 DEBUG (MainThread) [custom_components.eufy_security.config_flow] eufy_security EufySecurityOptionFlowHandler - {'host': '127.0.0.1', 'port': 3004}
2024-01-04 18:08:01.519 DEBUG (MainThread) [custom_components.eufy_security.config_flow] eufy_security EufySecurityOptionFlowHandler - {}
2024-01-04 18:08:01.519 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
File "/usr/local/lib/python3.11/site-packages/aiohttp/web_protocol.py", line 452, in _handle_request
resp = await request_handler(request)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/aiohttp/web_app.py", line 543, in _handle
resp = await handler(request)
^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/aiohttp/web_middlewares.py", line 114, in impl
return await handler(request)
^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 85, in security_filter_middleware
return await handler(request)
^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware
return await handler(request)
^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
return await handler(request)
^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 80, in ban_middleware
return await handler(request)
^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 233, in auth_middleware
return await handler(request)
^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/components/http/headers.py", line 31, in headers_middleware
response = await handler(request)
^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 149, in handle
result = await handler(request, **request.match_info)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/components/http/decorators.py", line 63, in with_admin
return await func(self, request, *args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 213, in post
return await super().post(request)
^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 72, in wrapper
result = await method(view, request, data, *args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 71, in post
result = await self._flow_mgr.async_init(
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 285, in async_init
flow = await self.async_create_flow(handler, context=context, data=data)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/config_entries.py", line 1878, in async_create_flow
return handler.async_get_options_flow(entry)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/eufy_security/config_flow.py", line 62, in async_get_options_flow
return EufySecurityOptionFlowHandler(config_entry)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/eufy_security/config_flow.py", line 33, in __init__
vol.Optional(ConfigField.rtsp_server_port.name, default=self.config.rtsp_server_port): cv.port,
^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/enum.py", line 784, in __getattr__
raise AttributeError(name) from None
AttributeError: rtsp_server_port

**Comment by djtrao** [comment]
I have the exact same problem, same log and all. Have been trying to find a solution these past few days.

**Comment by zapccu** [comment]
Same here. Configuration is only possible when reinstalling the integration

**Comment by edmomot** [comment]
Downgrading to the previous version ( v7.7.4) is the workaround that got me past this error. I removed the hub device integration in settings, removed from HACS, restarted my docker container, added the previous version, restarted the docker container again, and added the integration in settings.

I notice the release notes have this in the breaking changes, not sure if this is relevant:
* This change relies on go2rtc configuration. Please wait until a new version is released and do not get from master

**Comment by joelkay** [comment]
Downgrading to 7.7.4 is what worked for me aswell, I'm running on docker so have also got the latest go2rtc image, I doubt that's the issue.

**Comment by zapccu** [comment]
I think the root cause is, that "rtsp_server_port" is missing in file model.py

**Comment by djtrao** [comment]
> Downgrading to the previous version ( v7.7.4) is the workaround that got me past this error. I removed the hub device integration in settings, removed from HACS, restarted my docker container, added the previous version, restarted the docker container again, and added the integration in settings.
> 
> I notice the release notes have this in the breaking changes, not sure if this is relevant:
> 
> * This change relies on go2rtc configuration. Please wait until a new version is released and do not get from master

Unfortunately still the same problem here. 
Uninstalled the Integration, then removed the integration from HACS too. Restarted, re-installed on hacs, chose the previous version, restarted, installed the integration: Failed to setup problem...  just as in the Original Post...

**Comment by dMopp** [comment]
+1

**Comment by scullymi** [comment]
same here

**Comment by ttuuxxeerr** [comment]
same here

**Comment by apeeters** [comment]
Pull request https://github.com/fuatakgun/eufy_security/pull/1069 seems to be related.

**Comment by fuatakgun** [comment]
Sadly not related, at first look it seems to be.

By default rtsp host address equals the add-on host address and it was intentional.

**Comment by fuatakgun** [comment]
@kauthmbt , you are probably right, thanks, removed them now

**Comment by kauthmbt** [comment]
@fuatakgun  You are welcome!
Glad it helped and thanks for all your work and efforts

**Comment by fuatakgun** [comment]
Fixed in 8.0.1

**Comment by djtrao** [comment]
wow guys. Thanks so much. 
And fuatakgun, thanks for that speedy fix!
