### ISSUE TITLE
Homebase state cannot be updated

### ISSUE THREAD

**Issue by jasonlansdown** [fuatakgun/eufy_security#1110]
Please check existing (open or closed) issues before creating a new one. (https://github.com/fuatakgun/eufy_security/issues?q=is%3Aissue+)

If this is not an issue, you can use `Discussions` (https://github.com/fuatakgun/eufy_security/discussions) section.

**Describe the bug**

Open issues don't describe a fix for this. I cannot update my homebase via the device page itself or via automations. This was working about a week ago. 
I have just one homebase. It is a homebase 3.

**To reproduce**

See above

**Expected behavior**

See above. Homebase guard mode should be configurable.

**Additional information**

Go to Settings -> System -> Repairs -> Click on 3 dots (...) -> System Information and get Version and Installation Type to below fields;
- Home Assistant Installation Type (OS - Supvervised - Core): 
- Home Assistant Core Version:  core-2024.2.2
- Eufy Security Add-on Version: 1.7.1
- Eufy Security Integration Version: Firmware: 3.4.3.9

- Debug Logs from Home Assistant (https://github.com/fuatakgun/eufy_security/discussions/624) - Without this, I will automatically resolve this issue
  
[error_log.txt](https://github.com/fuatakgun/eufy_security/files/14381334/error_log.txt)

- Logs from Eufy Security Add-on (either from Add-ons page of Home Assistant or Docker output):

- Would you share your device with me in case further debugging required? (Yes/No): 
- Yes

**Additional context**

Add any other context about the problem goes here. Mainly, share everything as log files and use screenshots as last resort.

**Comment by prevello** [comment]
I have the same issue, not sure when it started but no entities are updated any longer.

Home Assistant 2024.2.2
eufy-security-ws add-on: 1.7.1
Eufy Security integration: 8.0.1


This is from the debug log when trying to change alarm control panel from Home > Away:

`2024-02-23 12:31:26.241 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [139658416572224] 'NoneType' object has no attribute 'available'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 240, in handle_call_service
    response = await hass.services.async_call(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2279, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2316, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 861, in entity_service_call
    if not entity.available:
           ^^^^^^^^^^^^^^^^
  File "/config/custom_components/eufy_security/entity.py", line 50, in available
    return self.coordinator.available
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/eufy_security/coordinator.py", line 111, in available
    return self._api.available
           ^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'available'`

**Comment by JoshWobbles** [comment]
I cannot get this working anymore either.
