### ISSUE TITLE
Cannot change guard mode 

### ISSUE THREAD

**Issue by Bkl741** [fuatakgun/eufy_security#1124]
Since I update home assistant I think, I can’t change guard mode. Nothing is happening when I edit it.

Homebase version   3.3.3.0h
Core 2024.3.3
Supervisor 2024.03.0
Operating System 12.1
UI  20240307.0
Eufy 8.0.1
Homebase 2

**Comment by Bkl741** [comment]
I didn't find anything in the logs

**Comment by Bkl741** [comment]
Today, I have some informations in logs files :

`Enregistreur: homeassistant
Source: custom_components/eufy_security/eufy_security_api/web_socket_client.py:63
intégration: Eufy Security ([documentation](https://github.com/fuatakgun/eufy_security), [problèmes](https://github.com/fuatakgun/eufy_security/issues))
S'est produit pour la première fois: 12:54:29 (1 occurrences)
Dernier enregistrement: 12:54:29

Error doing job: Exception in callback WebSocketClient._on_close(<Task cancell...client.py:62>>)
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/config/custom_components/eufy_security/eufy_security_api/web_socket_client.py", line 81, in _on_close
    self.close_callback(future)
  File "/config/custom_components/eufy_security/eufy_security_api/api_client.py", line 317, in _on_close
    _LOGGER.debug(f"on_close - executed - {future} = {future.exception()}")
                                                      ^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/eufy_security/eufy_security_api/web_socket_client.py", line 63, in _process_messages
    async for msg in self.socket:
  File "/usr/local/lib/python3.12/site-packages/aiohttp/client_ws.py", line 312, in __anext__
    msg = await self.receive()
          ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/client_ws.py", line 244, in receive
    msg = await self._reader.read()
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/streams.py", line 663, in read
    return await super().read()
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/streams.py", line 622, in read
    await self._waiter
asyncio.exceptions.CancelledError`

**Comment by Bkl741** [comment]
It's ok, I had to update eufy security ws.

**Comment by ripple7511** [comment]
I appear to be having the same issue-- 
eufy-security-ws is at 1.8.0.2 on my system, is there a newer update I need to get?

**Comment by michaelblight** [comment]
Mine was doing the same. I only needed to restart the eufy-security-ws addon to get it working again.

**Comment by robinhood-code** [comment]
> Hi, I'm having the same issue today. If I change the status on Eufy app it's updated in Home Assistant, but I can't change it from Home Assistant. I have tried to restart eufy security ws docker container.

when you can't change the guard mode, is the "Connected" sensor "On" or "Off" for that particular camera? You probably need to enable it under "Diagnostic" if you have not already done so.

**Comment by mariomaz87** [comment]
> > Hi, I'm having the same issue today. If I change the status on Eufy app it's updated in Home Assistant, but I can't change it from Home Assistant. I have tried to restart eufy security ws docker container.
> 
> when you can't change the guard mode, is the "Connected" sensor "On" or "Off" for that particular camera? You probably need to enable it under "Diagnostic" if you have not already done so.

In my case it’s the base and not the camera. The Connected sensor is On.

**Comment by robinhood-code** [comment]
> In my case it’s the base and not the camera. The Connected sensor is On.

If you are referring to the base then I can't change its mode as well.

**Comment by xxpas02** [comment]
I also can’t set the Homebase Guard Mode. I haven’t tried to before, so don’t know if it worked previously or not. It reports correctly when set from the Eufy app but cannot be changed in HA. 

Homebase version 3.3.3.2h
Homebase 2
Eufy Security 8.0.2
Core 2024.5.3
Supervisor 2024.05.1
Operating System 12.3
Frontend 20240501.1

**Comment by thoompje** [comment]
> Today, I have some informations in logs files :
> 
> `Enregistreur: homeassistant Source: custom_components/eufy_security/eufy_security_api/web_socket_client.py:63 intégration: Eufy Security ([documentation](https://github.com/fuatakgun/eufy_security), [problèmes](https://github.com/fuatakgun/eufy_security/issues)) S'est produit pour la première fois: 12:54:29 (1 occurrences) Dernier enregistrement: 12:54:29
> 
> Error doing job: Exception in callback WebSocketClient._on_close(>) Traceback (most recent call last): File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run self._context.run(self._callback, *self._args) File "/config/custom_components/eufy_security/eufy_security_api/web_socket_client.py", line 81, in _on_close self.close_callback(future) File "/config/custom_components/eufy_security/eufy_security_api/api_client.py", line 317, in _on_close _LOGGER.debug(f"on_close - executed - {future} = {future.exception()}") ^^^^^^^^^^^^^^^^^^ File "/config/custom_components/eufy_security/eufy_security_api/web_socket_client.py", line 63, in _process_messages async for msg in self.socket: File "/usr/local/lib/python3.12/site-packages/aiohttp/client_ws.py", line 312, in **anext** msg = await self.receive() ^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.12/site-packages/aiohttp/client_ws.py", line 244, in receive msg = await self._reader.read() ^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.12/site-packages/aiohttp/streams.py", line 663, in read return await super().read() ^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.12/site-packages/aiohttp/streams.py", line 622, in read await self._waiter asyncio.exceptions.CancelledError`

I have the same logs here, anyone any idea how to solve this?

**Comment by DocWind** [comment]
> I also can’t set the Homebase Guard Mode. I haven’t tried to before, so don’t know if it worked previously or not. It reports correctly when set from the Eufy app but cannot be changed in HA.
> 
> Homebase version 3.3.3.2h Homebase 2 Eufy Security 8.0.2 Core 2024.5.3 Supervisor 2024.05.1 Operating System 12.3 Frontend 20240501.1

Same problem here, but it worked fine until more or less 4 weeks ago. Then suddenly as you described. 
No solution so far?

**Comment by Calcue-dev** [comment]
I am also facing this issue, which is a real shame. Sometimes it works perfectly. Other times it does not. 

It's like it can read the state from the Base Station fine as the Base Station widget on my dashboard reflects what I do in the Eufy app. But, if you change the Arm mode of the Base Station from within Home Assistant it does not work. Randomly it starts working again after a while but then it will fail later again.

My logs are the exact same as the ones shared in this thread. 

Anyone have an update or anything I can try?

**Comment by mariomaz87** [comment]
> I am also facing this issue, which is a real shame. Sometimes it works perfectly. Other times it does not.
> 
> It's like it can read the state from the Base Station fine as the Base Station widget on my dashboard reflects what I do in the Eufy app. But, if you change the Arm mode of the Base Station from within Home Assistant it does not work. Randomly it starts working again after a while but then it will fail later again.
> 
> My logs are the exact same as the ones shared in this thread.
> 
> Anyone have an update or anything I can try?

Are you using other Eufy plugins (like Homebridge)? In this case, try to disable all the other plugins and restart Home Assistant

**Comment by cpohli** [comment]
I have just discovered this issue on my base station as well!
If i change the status via the eufy app, i instantly see the change in HA.
But i cannot change it from HA. Just nothing happens at all. Nothing in the logs either.

Any ideas on this?

Eufy HB2, latest HA and Eufy Security plugin. Plugin deleted, reinstalled, restarted -> same.

**Comment by fuatakgun** [comment]
folks, without proper log, you cannot get any help

**Comment by dadonali** [comment]
Im New in the HA game, can you Tell me how i get the logs you need?

**Comment by fuatakgun** [comment]
check the new issue template, it tells which logs are needed, README would help to some extent to get the logs.
