### ISSUE TITLE
Camera thumbnails visible, but not streaming across all models

### ISSUE THREAD

**Issue by komtx** [fuatakgun/eufy_security#1134]
While all but one of my cameras now show up in HA, none of them are able to stream.  My last camera is not recognized at all although it is the simplest of them all - the Indoor Cam  T8400

RTSP addresses show up for each camera, but RTC throws out several 'unrecognized' error codes 

[402f1039_eufy_security_ws_2024-04-19T17-24-52.652Z.log](https://github.com/fuatakgun/eufy_security/files/15043729/402f1039_eufy_security_ws_2024-04-19T17-24-52.652Z.log)

[a889bffc_go2rtc_2024-04-19T17-23-49.715Z.log](https://github.com/fuatakgun/eufy_security/files/15043725/a889bffc_go2rtc_2024-04-19T17-23-49.715Z.log)

**Expected behavior**

**Additional information**

Go to Settings -> System -> Repairs -> Click on 3 dots (...) -> System Information and get Version and Installation Type to below fields;
- Home Assistant Installation Type (OS - Supvervised - Core):  OS
- Home Assistant Core Version:  core-2024.4.3
- Eufy Security Add-on Version: 1.8.0-2
- Eufy Security Integration Version: v8.0.1

Hardware Information;
E340 Battery but using Home DC Voltage
S340 Solocam using solar
T8400 Indoor cam 2 - one showing thumbnail, one not discovered - both USB Powered
Solocam S40 (solar)

- Live Streaming Protocol (RTSP/P2P):  P2P but GoRTC installed

- Debug Logs from Home Assistant (https://github.com/fuatakgun/eufy_security/discussions/624) - Without this, I will automatically resolve this issue
  Logger: homeassistant.components.camera
Source: components/camera/__init__.py:902
integration: Camera (documentation, issues)
First occurred: 12:12:34 (3 occurrences)
Last logged: 12:13:07

This error originated from a custom integration.

Logger: homeassistant
Source: custom_components/eufy_security/eufy_security_api/web_socket_client.py:63
integration: Eufy Security (documentation, issues)
First occurred: 12:15:47 (2 occurrences)
Last logged: 12:16:26

Error doing job: Exception in callback WebSocketClient._on_close(<Task cancell...client.py:62>>)
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/config/custom_components/eufy_security/eufy_security_api/web_socket_client.py", line 81, in _on_close
    self.close_callback(future)
  File "/config/custom_components/eufy_security/eufy_security_api/api_client.py", line 317, in _on_close
    _LOGGER.debug(f"on_close - executed - {future} = {future.exception()}")
                                                      ^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/eufy_security/eufy_security_api/web_socket_client.py", line 63, in _process_messages
    async for msg in self.socket:
  File "/usr/local/lib/python3.12/site-packages/aiohttp/client_ws.py", line 312, in __anext__
    msg = await self.receive()
          ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/client_ws.py", line 244, in receive
    msg = await self._reader.read()
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/streams.py", line 681, in read
    return await super().read()
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/streams.py", line 640, in read
    await self._waiter
asyncio.exceptions.CancelledError

Logger: homeassistant.components.stream.stream.camera.doorbell
Source: components/stream/__init__.py:448
integration: Stream (documentation, issues)
First occurred: 12:14:57 (7 occurrences)
Last logged: 12:18:27

Error from stream worker: Error demuxing stream: [Errno 110] Operation timed out: 'rtsp://127.0.0.1:8554/T8214510234017E3'
Error from stream worker: Error opening stream (HTTP_NOT_FOUND, Server returned 404 Not Found) rtsp://127.0.0.1:8554/T8214510234017E3

Logger: homeassistant.components.stream.stream.camera.garage
Source: components/stream/__init__.py:448
integration: Stream (documentation, issues)
First occurred: 12:14:09 (8 occurrences)
Last logged: 12:18:49

Error from stream worker: Error demuxing stream: [Errno 110] Operation timed out: 'rtsp://127.0.0.1:8554/T8170T1023462BB6'; last error log: [NULL] missing picture in access unit with size 92
Error from stream worker: Error opening stream (HTTP_NOT_FOUND, Server returned 404 Not Found) rtsp://127.0.0.1:8554/T8170T1023462BB6

Logger: homeassistant.components.stream.stream.camera.sl_living_room
Source: components/stream/__init__.py:448
integration: Stream (documentation, issues)
First occurred: 12:16:15 (6 occurrences)
Last logged: 12:19:01

Error from stream worker: Error opening stream (ERRORTYPE_113, Host is unreachable) rtsp://192.168.5.111/live0
Error requesting stream: camera.garage does not support play stream service
- Logs from Eufy Security Add-on (either from Add-ons page of Home Assistant or Docker output):
[EufyAddon Log.pdf](https://github.com/fuatakgun/eufy_security/files/15043529/EufyAddon.Log.pdf)

- Would you share your device with me in case further debugging required? (Yes/No):  Yes

**Additional context**

Add any other context about the problem goes here. Mainly, share everything as log files and use screenshots as last resort.

**Comment by ramseys1990** [comment]
I have the same issue as stated here, I will be willing to share as well if need be.

**Comment by komtx** [comment]
hi - you should have my device shares from a couple of weeks ago - let me know if I need to send another invite.  Thanks again!

**Comment by member1980** [comment]
same here :( Eufy E340

**Comment by ramseys1990** [comment]
> @ramseys1990 please share following the readme file and drop a message over here

Hi, I have shared my cameras to eufydeveloper@gmail.com

**Comment by ramseys1990** [comment]
@fuatakgun Just wanted to touch base on this and see if I still need the cameras to be shared with you.
