### ISSUE TITLE
[Bug]: Solar Wall Light S120 T81A0 - Streams only for some minutes, Entities do not work

### ISSUE THREAD

**Issue by spunkt123** [fuatakgun/eufy_security#1155]
Please check existing (open or closed) issues before creating a new one. (https://github.com/fuatakgun/eufy_security/issues?q=is%3Aissue+)

If this is not an issue, you can use `Discussions` (https://github.com/fuatakgun/eufy_security/discussions) section.

**Describe the bug**

I use this integration with a 2K indoor cam which works fine. And i try to use it with a Solar Wall Light S120 (T81A0). Unfortunatelly it is not working correctly.
I can start the stream by clicking "Start P2P Stream" then i can see the stream for some minutes. Then the stream stops, the entity "StreamStatus" changes to "StreamStatus.IDLE". After that i cannot start the stream again by clicking "Start P2P Stream" - I have to stop the camera und start it again.

With my 2K indoor cam i activated "continuous recording" und NAS(RTSP)-Setting in eufy app. But the S120 does not have any RTSP-configuration.

Furthermore all the entities, e.g. "Motion detection", "Current Mode", "Event Image", etc. do not work. Motion detection is always "normal" even when the Eufy App is recognizing and sending a push notification

**To reproduce**

1. Go to 'Device'
2. Click on 'Start P2P Stream'
3. Stream is running for some minutes
4. Then the stream stops
5. "StreamStatus" changes to "StreamStatus.IDLE"
6. Click on 'Start P2P Stream'
7. Stream does not start

**Expected behavior**

Stream should start again.
Entities should be updated

**Additional information**

Go to Settings -> System -> Repairs -> Click on 3 dots (...) -> System Information and get Version and Installation Type to below fields;
- Home Assistant Installation Type (OS - Supvervised - Core): Home Assistant Container
- Home Assistant Core Version: core-2024.5.5
- Eufy Security Add-on Version: 1.8.0 (running as docker container)
- Eufy Security Integration Version: 8.0.2

Hardware Information;
- Camera Model: Solar Wall Light S120 T81A0

- Live Streaming Protocol (RTSP/P2P): RTSP

- Debug Logs from Home Assistant (https://github.com/fuatakgun/eufy_security/discussions/624) - Without this, I will automatically resolve this issue
```
2024-06-03 21:17:21.464 DEBUG (MainThread) [custom_components.eufy_security.eufy_security_api] domain - driver - EventSourceType.driver - driver.poll_refresh - {} - {}
2024-06-03 21:17:21.464 DEBUG (MainThread) [custom_components.eufy_security.eufy_security_api] {'command': 'driver.poll_refresh', 'messageId': 'driver.poll_refresh.6f6e0067e6634349a2f87340f5e8929e'}
2024-06-03 21:17:21.464 DEBUG (MainThread) [custom_components.eufy_security.eufy_security_api] send_message - {'command': 'driver.poll_refresh', 'messageId': 'driver.poll_refresh.6f6e0067e6634349a2f87340f5e8929e'}
2024-06-03 21:17:21.672 DEBUG (MainThread) [custom_components.eufy_security.eufy_security_api] _on_message - {'type': 'result', 'success': True, 'messageId': 'driver.poll_refresh.6f6e0067e6634349a2f87340f5e8929e', 'result': {}}
2024-06-03 21:17:21.672 DEBUG (MainThread) [custom_components.eufy_security] coordinator - complete update_local
2024-06-03 21:17:21.672 DEBUG (MainThread) [custom_components.eufy_security] Finished fetching eufy_security data in 0.209 seconds (success: True)
2024-06-03 21:17:28.097 DEBUG (MainThread) [custom_components.eufy_security] image 1 - False - None
2024-06-03 21:17:28.097 DEBUG (MainThread) [custom_components.eufy_security] async_camera_image 5 - is_empty False
2024-06-03 21:17:28.097 DEBUG (MainThread) [custom_components.eufy_security] async_camera_image 6 - 89273
2024-06-03 21:17:30.124 DEBUG (MainThread) [custom_components.eufy_security] image 1 - False - None
2024-06-03 21:17:30.124 DEBUG (MainThread) [custom_components.eufy_security] async_camera_image 5 - is_empty False
2024-06-03 21:17:30.124 DEBUG (MainThread) [custom_components.eufy_security] async_camera_image 6 - 89273
2024-06-03 21:17:38.081 DEBUG (MainThread) [custom_components.eufy_security] image 1 - False - None
2024-06-03 21:17:38.081 DEBUG (MainThread) [custom_components.eufy_security] async_camera_image 5 - is_empty False
2024-06-03 21:17:38.081 DEBUG (MainThread) [custom_components.eufy_security] async_camera_image 6 - 89273
2024-06-03 21:17:48.075 DEBUG (MainThread) [custom_components.eufy_security] image 1 - False - None
2024-06-03 21:17:48.075 DEBUG (MainThread) [custom_components.eufy_security] async_camera_image 5 - is_empty False
2024-06-03 21:17:48.075 DEBUG (MainThread) [custom_components.eufy_security] async_camera_image 6 - 89273
2024-06-03 21:17:58.083 DEBUG (MainThread) [custom_components.eufy_security] image 1 - False - None
2024-06-03 21:17:58.083 DEBUG (MainThread) [custom_components.eufy_security] async_camera_image 5 - is_empty False
2024-06-03 21:17:58.083 DEBUG (MainThread) [custom_components.eufy_security] async_camera_image 6 - 89273
2024-06-03 21:18:08.076 DEBUG (MainThread) [custom_components.eufy_security] image 1 - False - None
2024-06-03 21:18:08.077 DEBUG (MainThread) [custom_components.eufy_security] async_camera_image 5 - is_empty False
2024-06-03 21:18:08.077 DEBUG (MainThread) [custom_components.eufy_security] async_camera_image 6 - 89273
2024-06-03 21:18:18.078 DEBUG (MainThread) [custom_components.eufy_security] image 1 - False - None
2024-06-03 21:18:18.078 DEBUG (MainThread) [custom_components.eufy_security] async_camera_image 5 - is_empty False
2024-06-03 21:18:18.079 DEBUG (MainThread) [custom_components.eufy_security] async_camera_image 6 - 89273
2024-06-03 21:18:28.085 DEBUG (MainThread) [custom_components.eufy_security] image 1 - False - None
2024-06-03 21:18:28.085 DEBUG (MainThread) [custom_components.eufy_security] async_camera_image 5 - is_empty False
2024-06-03 21:18:28.086 DEBUG (MainThread) [custom_components.eufy_security] async_camera_image 6 - 89273
2024-06-03 21:18:42.256 DEBUG (MainThread) [custom_components.eufy_security.eufy_security_api] url - StreamProvider.P2P - rtsp://127.0.0.1:8554/T81A0P102346231E
2024-06-03 21:18:42.257 DEBUG (MainThread) [custom_components.eufy_security.eufy_security_api] _initiate_start_stream - info - send command to add-on - StreamProvider.P2P
2024-06-03 21:18:42.257 DEBUG (MainThread) [custom_components.eufy_security.eufy_security_api] domain - device - EventSourceType.device - device.start_livestream - {'serial_no': 'T81A0P102346231E'} - {'serialNumber': 'T81A0P102346231E'}
2024-06-03 21:18:42.257 DEBUG (MainThread) [custom_components.eufy_security.eufy_security_api] {'serialNumber': 'T81A0P102346231E', 'command': 'device.start_livestream', 'messageId': 'device.start_livestream.265bf93beb294e7f8d25aa1acfdef50c'}
2024-06-03 21:18:42.257 DEBUG (MainThread) [custom_components.eufy_security.eufy_security_api] send_message - {'serialNumber': 'T81A0P102346231E', 'command': 'device.start_livestream', 'messageId': 'device.start_livestream.265bf93beb294e7f8d25aa1acfdef50c'}
2024-06-03 21:18:42.260 DEBUG (MainThread) [custom_components.eufy_security.eufy_security_api] _on_message - {'type': 'result', 'success': True, 'messageId': 'device.start_livestream.265bf93beb294e7f8d25aa1acfdef50c', 'result': {'async': True}}
2024-06-03 21:18:45.385 DEBUG (MainThread) [custom_components.eufy_security.eufy_security_api] _on_message - {'type': 'event', 'event': {'source': 'station', 'event': 'connected', 'serialNumber': 'T81A0P102346231E'}}
2024-06-03 21:18:45.529 DEBUG (MainThread) [custom_components.eufy_security.eufy_security_api] _on_message - {'type': 'event', 'event': {'source': 'device', 'event': 'command result', 'serialNumber': 'T81A0P102346231E', 'command': 'start_livestream', 'returnCode': -134, 'returnCodeName': 'ERROR_CONNECT_TIMEOUT', 'customData': {'command': {'name': 'deviceStartLivestream', 'value': 0}}}}
2024-06-03 21:18:45.529 DEBUG (MainThread) [custom_components.eufy_security.eufy_security_api] event not handled -T81A0P102346231E - Event(type='command result', data={'source': 'device', 'event': 'command result', 'serialNumber': 'T81A0P102346231E', 'command': 'start_livestream', 'returnCode': -134, 'returnCodeName': 'ERROR_CONNECT_TIMEOUT', 'customData': {'command': {'name': 'deviceStartLivestream', 'value': 0}}})
2024-06-03 21:18:45.591 DEBUG (MainThread) [custom_components.eufy_security] image 1 - False - None
2024-06-03 21:18:45.591 DEBUG (MainThread) [custom_components.eufy_security] async_camera_image 5 - is_empty False
2024-06-03 21:18:45.591 DEBUG (MainThread) [custom_components.eufy_security] async_camera_image 6 - 89273
2024-06-03 21:18:47.262 DEBUG (MainThread) [custom_components.eufy_security.eufy_security_api] _initiate_start_stream - error - command was failed - <asyncio.locks.Event object at 0x7f66f83749b0 [unset]>
2024-06-03 21:18:47.481 DEBUG (MainThread) [custom_components.eufy_security.eufy_security_api] _on_message - {'type': 'event', 'event': {'source': 'device', 'event': 'command result', 'serialNumber': 'T81A0P102346231E', 'command': 'start_livestream', 'returnCode': 0, 'returnCodeName': 'ERROR_PPCS_SUCCESSFUL', 'customData': {'command': {'name': 'deviceStartLivestream', 'value': 0}}}}
2024-06-03 21:18:47.482 DEBUG (MainThread) [custom_components.eufy_security.eufy_security_api] event not handled -T81A0P102346231E - Event(type='command result', data={'source': 'device', 'event': 'command result', 'serialNumber': 'T81A0P102346231E', 'command': 'start_livestream', 'returnCode': 0, 'returnCodeName': 'ERROR_PPCS_SUCCESSFUL', 'customData': {'command': {'name': 'deviceStartLivestream', 'value': 0}}})
2024-06-03 21:18:49.571 DEBUG (MainThread) [custom_components.eufy_security.eufy_security_api] _on_message - {'type': 'event', 'event': {'source': 'device', 'event': 'livestream started', 'serialNumber': 'T81A0P102346231E'}}
2024-06-03 21:18:49.571 DEBUG (MainThread) [custom_components.eufy_security.eufy_security_api] _handle_livestream_started - Event(type='livestream started', data={'source': 'device', 'event': 'livestream started', 'serialNumber': 'T81A0P102346231E'})
2024-06-03 21:18:56.078 DEBUG (MainThread) [custom_components.eufy_security] image 1 - False - None
2024-06-03 21:18:56.079 DEBUG (MainThread) [custom_components.eufy_security] async_camera_image 5 - is_empty False
2024-06-03 21:18:56.079 DEBUG (MainThread) [custom_components.eufy_security] async_camera_image 6 - 89273
2024-06-03 21:19:06.075 DEBUG (MainThread) [custom_components.eufy_security] image 1 - False - None
2024-06-03 21:19:06.075 DEBUG (MainThread) [custom_components.eufy_security] async_camera_image 5 - is_empty False
2024-06-03 21:19:06.075 DEBUG (MainThread) [custom_components.eufy_security] async_camera_image 6 - 89273
2024-06-03 21:19:16.075 DEBUG (MainThread) [custom_components.eufy_security] image 1 - False - None
2024-06-03 21:19:16.075 DEBUG (MainThread) [custom_components.eufy_security] async_camera_image 5 - is_empty False
2024-06-03 21:19:16.075 DEBUG (MainThread) [custom_components.eufy_security] async_camera_image 6 - 89273
2024-06-03 21:19:16.425 DEBUG (MainThread) [custom_components.eufy_security.eufy_security_api] url - StreamProvider.P2P - rtsp://127.0.0.1:8554/T81A0P102346231E
2024-06-03 21:19:16.425 DEBUG (MainThread) [custom_components.eufy_security.eufy_security_api] _initiate_start_stream - info - send command to add-on - StreamProvider.P2P
2024-06-03 21:19:16.425 DEBUG (MainThread) [custom_components.eufy_security.eufy_security_api] domain - device - EventSourceType.device - device.start_livestream - {'serial_no': 'T81A0P102346231E'} - {'serialNumber': 'T81A0P102346231E'}
2024-06-03 21:19:16.425 DEBUG (MainThread) [custom_components.eufy_security.eufy_security_api] {'serialNumber': 'T81A0P102346231E', 'command': 'device.start_livestream', 'messageId': 'device.start_livestream.2c15e56c7f8a405485d5d6d7ebcdfeac'}
2024-06-03 21:19:16.425 DEBUG (MainThread) [custom_components.eufy_security.eufy_security_api] send_message - {'serialNumber': 'T81A0P102346231E', 'command': 'device.start_livestream', 'messageId': 'device.start_livestream.2c15e56c7f8a405485d5d6d7ebcdfeac'}
2024-06-03 21:19:16.480 DEBUG (MainThread) [custom_components.eufy_security.eufy_security_api] _on_message - {'type': 'result', 'success': False, 'messageId': 'device.start_livestream.2c15e56c7f8a405485d5d6d7ebcdfeac', 'errorCode': 'device_livestream_already_running'}
2024-06-03 21:19:16.489 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140080384660032] Unexpected exception
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 239, in handle_call_service
    response = await hass.services.async_call(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2738, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2779, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 975, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1047, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/button/__init__.py", line 134, in _async_press_action
    await self.async_press()
  File "/config/custom_components/eufy_security/button.py", line 51, in async_press
    await handler_func()
  File "/config/custom_components/eufy_security/eufy_security_api/camera.py", line 154, in start_livestream
    if await self._initiate_start_stream(StreamProvider.P2P) is False:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/eufy_security/eufy_security_api/camera.py", line 121, in _initiate_start_stream
    if await self.api.start_livestream(self.product_type, self.serial_no) is False:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/eufy_security/eufy_security_api/api_client.py", line 224, in start_livestream
    await self._send_message_get_response(OutgoingMessage(OutgoingMessageType.start_livestream, serial_no=serial_no))
  File "/config/custom_components/eufy_security/eufy_security_api/api_client.py", line 333, in _send_message_get_response
    return await future
           ^^^^^^^^^^^^
custom_components.eufy_security.eufy_security_api.exceptions.FailedCommandException: {'type': 'result', 'success': False, 'messageId': 'device.start_livestream.2c15e56c7f8a405485d5d6d7ebcdfeac', 'errorCode': 'device_livestream_already_running'}
2024-06-03 21:19:25.573 DEBUG (MainThread) [custom_components.eufy_security] image 1 - False - None
2024-06-03 21:19:25.573 DEBUG (MainThread) [custom_components.eufy_security] async_camera_image 5 - is_empty False
2024-06-03 21:19:25.573 DEBUG (MainThread) [custom_components.eufy_security] async_camera_image 6 - 89273
2024-06-03 21:19:35.576 DEBUG (MainThread) [custom_components.eufy_security] image 1 - False - None
2024-06-03 21:19:35.576 DEBUG (MainThread) [custom_components.eufy_security] async_camera_image 5 - is_empty False
2024-06-03 21:19:35.576 DEBUG (MainThread) [custom_components.eufy_security] async_camera_image 6 - 89273
2024-06-03 21:19:45.583 DEBUG (MainThread) [custom_components.eufy_security] image 1 - False - None
```
- Logs from Eufy Security Add-on (either from Add-ons page of Home Assistant or Docker output):
```
2024-06-03 18:56:37.973 INFO    eufy-security-ws:eufy-security-client   [http] [Station.onConnect] Connected to station T81A0P102346231E on host 194.99.91.54 and port 41287
2024-06-03 19:12:33.052 INFO    eufy-security-ws:eufy-security-client   [http] [Station.onDisconnect] Disconnected from station T81A0P102346231E
2024-06-03 19:18:45.383 INFO    eufy-security-ws:eufy-security-client   [http] [Station.onConnect] Connected to station T81A0P102346231E on host 194.99.91.54 and port 41323
2024-06-03 19:18:45.523 WARN    eufy-security-ws:eufy-security-client   [p2p] [P2PClientProtocol._sendCommand] Command aged out from send queue for station T81A0P102346231E {
  commandType: 1700,
  nestedCommandType: 1000,
  channel: 0,
  ageing: 425903,
  maxAgeing: 120000
}
2024-06-03 19:19:16.437 ERROR   eufy-security-ws        Message error

 LivestreamAlreadyRunningError  Livestream for device T81A0P102346231E is already running, LivestreamAlreadyRunningError
error stack:
  • message_handler.js  DeviceMessageHandler.handle
        /dist/lib/device/message_handler.js:203
  • task_queues process.processTicksAndRejections
        internal/process/task_queues:95
  • server.js   async Client.receiveMessage
        /dist/lib/server.js:94
```

- Would you share your device with me in case further debugging required? (Yes/No):
Yes

**Additional context**

Add any other context about the problem goes here. Mainly, share everything as log files and use screenshots as last resort.
<img width="742" alt="Bildschirmfoto 2024-06-03 um 21 15 23" src="https://github.com/fuatakgun/eufy_security/assets/119702473/9a849b80-544e-450b-95c5-eeb256173aa8">
<img width="742" alt="Bildschirmfoto 2024-06-03 um 21 16 44" src="https://github.com/fuatakgun/eufy_security/assets/119702473/b28fabdb-d4e7-4911-85ba-d6d05b508178">

**Comment by fabien4444** [comment]
Hello
same issue here.
The push motion detection does not work at all.

**Comment by huebnerthomas** [comment]
I suppose I have the same challenges just with an S100 camera.

[140363741887312] Unexpected exception
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 241, in handle_call_service
    response = await hass.services.async_call(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2731, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2774, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 999, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1071, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/config/custom_components/eufy_security/camera.py", line 200, in async_turn_on
    await self._start_livestream()
  File "/config/custom_components/eufy_security/camera.py", line 161, in _start_livestream
    if await self.product.start_livestream() is False:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/eufy_security/eufy_security_api/camera.py", line 154, in start_livestream
    if await self._initiate_start_stream(StreamProvider.P2P) is False:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/eufy_security/eufy_security_api/camera.py", line 121, in _initiate_start_stream
    if await self.api.start_livestream(self.product_type, self.serial_no) is False:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/eufy_security/eufy_security_api/api_client.py", line 224, in start_livestream
    await self._send_message_get_response(OutgoingMessage(OutgoingMessageType.start_livestream, serial_no=serial_no))
  File "/config/custom_components/eufy_security/eufy_security_api/api_client.py", line 333, in _send_message_get_response
    return await future
           ^^^^^^^^^^^^
custom_components.eufy_security.eufy_security_api.exceptions.FailedCommandException: {'type': 'result', 'success': False, 'messageId': 'device.start_livestream.ca78d527676642f48e1ce4a24a64fdfc', 'errorCode': 'device_livestream_already_running'}

**Comment by duffy6** [comment]
Same ober here with S100.
Also in iobroker with the Eusec Adapter
