### ISSUE TITLE
"Access Token" error during setup

### ISSUE THREAD

**Issue by karllogue** [fuatakgun/eufy_security#1163]
Getting this every time I startup Home Assistant:

Logger: homeassistant.setup
Source: setup.py:402
First occurred: 6:34:09 PM (1 occurrences)
Last logged: 6:34:09 PM

Error during setup of component eufy
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 402, in _async_setup_component
    result = await task
             ^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/eufy/__init__.py", line 62, in setup
    data = lakeside.get_devices(
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/lakeside/__init__.py", line 39, in get_devices
    token = r.json()['access_token']
            ~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: 'access_token'

**Comment by Willempie79** [comment]
Ik krijg dezelfde foutmelding

**Comment by jartill** [comment]
Yep. Getting same here. 

Core 2024.7.1 
Eufy add-on 1.8.0-2
Integration 8.0.2

**Comment by fuatakgun** [comment]
This error is from core integration (eufy) not from mine (eufy_security)
