### ISSUE TITLE
The integration stopped working :(

### ISSUE THREAD

**Issue by appsfinder2** [fuatakgun/eufy_security#1165]
after core update release-2024.6

[402f1039_eufy_security_ws_2024-06-21T04-34-05.269Z.log](https://github.com/user-attachments/files/15922759/402f1039_eufy_security_ws_2024-06-21T04-34-05.269Z.log)

**Comment by prabath83** [comment]
Yes the intergration stopped working. if you open the developer tools and monitor the binary_sensor.backyard_motion_detected (which is my backyard camera) while standing infront of the camera nothing changes. confirmed for me too

**Comment by prabath83** [comment]
![image](https://github.com/fuatakgun/eufy_security/assets/3162448/9e91750f-6ca0-457f-8c63-954708236ba4)

**Comment by komtx** [comment]
I am getting this error now:
eufy_security Exception in login : Connection to add-on was broken. please reload the integration! - traceback: Traceback (most recent call last): File "/usr/local/lib/python3.12/site-packages/aiohttp/connector.py", line 1025, in _wrap_create_connection return await self._loop.create_connection(*args, **kwargs) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1120, in create_connection raise exceptions[0] File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1102, in create_connection sock = await self._connect_sock( ^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1005, in _connect_sock await self.sock_connect(sock, address) File "/usr/local/lib/python3.12/asyncio/selector_events.py", line 641, in sock_connect return await fut ^^^^^^^^^ File "/usr/local/lib/python3.12/asyncio/selector_events.py", line 681, in _sock_connect_cb raise OSError(err, f'Connect call failed {address}') ConnectionRefusedError: [Errno 111] Connect call failed ('127.0.0.1', 3000) The above exception was the direct cause of the following exception: Traceback (most recent call last): File "/config/custom_components/eufy_security/eufy_security_api/web_socket_client.py", line 42, in connect self.socket = await self.session.ws_connect(f"ws://{self.host}:{self.port}", heartbeat=10, compress=9) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.12/site-packages/aiohttp/client.py", line 835, in _ws_connect resp = await self.request( ^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.12/site-packages/aiohttp/client.py", line 581, in _request conn = await self._connector.connect( ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.12/site-packages/aiohttp/connector.py", line 544, in connect proto = await self._create_connection(req, traces, timeout) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.12/site-packages/aiohttp/connector.py", line 944, in _create_connection _, proto = await self._create_direct_connection(req, traces, timeout) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.12/site-packages/aiohttp/connector.py", line 1257, in _create_direct_connection raise last_exc File "/usr/local/lib/python3.12/site-packages/aiohttp/connector.py", line 1226, in _create_direct_connection transp, proto = await self._wrap_create_connection( ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.12/site-packages/aiohttp/connector.py", line 1033, in _wrap_create_connection raise client_error(req.connection_key, exc) from exc aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host 127.0.0.1:3000 ssl:default [Connect call failed ('127.0.0.1', 3000)] The above exception was the direct cause of the following exception: Traceback (most recent call last): File "/config/custom_components/eufy_security/config_flow.py", line 123, in _test_credentials await api_client.ws_connect() File "/config/custom_components/eufy_security/eufy_security_api/api_client.py", line 66, in ws_connect await self._client.connect() File "/config/custom_components/eufy_security/eufy_security_api/web_socket_client.py", line 44, in connect raise WebSocketConnectionException("Connection to add-on was broken. please reload the integration!") from exc custom_components.eufy_security.eufy_security_api.exceptions.WebSocketConnectionException: Connection to add-on was broken. please reload the integration!

**Comment by ekmc88** [comment]
Recently my integration has been stuck on initialising. Occasionally it will also show failed to load. Is anyone else having this issue?

**Comment by fabien4444** [comment]
> Recently my integration has been stuck on initialising. Occasionally it will also show "Failed setup, will retry: Connection to add-on was broken. please reload the integration!". Is anyone else having this issue?

Yes, i have same!
HA Core: 2024.6.4

**Comment by YaBoiDan** [comment]
Same here, just stopped working and stuck in initializing or failed.

**Comment by Anders-Falk** [comment]
New user but get the same errors on HACore: 2024.6.4. Not much respons here?

**Comment by clarky860** [comment]
Try enabling "Force IPv4 addresses first" in the Add-ons settings

![image](https://github.com/fuatakgun/eufy_security/assets/92803991/cb7caed8-9992-448a-9806-6e44cd141c0d)

**Comment by ekmc88** [comment]
> Try enabling "Force IPv4 addresses first" in the Add-ons settings
> 
> 
> 
> ![image](https://github.com/fuatakgun/eufy_security/assets/92803991/cb7caed8-9992-448a-9806-6e44cd141c0d)
> 
> 

Thanks Clarky. This has worked!

**Comment by fabien4444** [comment]
> Try enabling "Force IPv4 addresses first" in the Add-ons settings
> 
> ![image](https://private-user-images.githubusercontent.com/92803991/345085622-cb7caed8-9992-448a-9806-6e44cd141c0d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk5NDk2NTEsIm5iZiI6MTcxOTk0OTM1MSwicGF0aCI6Ii85MjgwMzk5MS8zNDUwODU2MjItY2I3Y2FlZDgtOTk5Mi00NDhhLTk4MDYtNmU0NGNkMTQxYzBkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzAyVDE5NDIzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAwOWQwYjQ4M2E0ZTQ3ZTE4MjdmNzViZjRjYmU3ZDUxYmRlYjk2ZjFlZWMyYTkzNGE5OWM4NzIwN2Q2NjIzYjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.vN1YMPAIxZp0Bo5cMCYo5RoQA-HAzg6dWxW7lUKniKU)

Not working for me :(

**Comment by Surreal2010** [comment]
> Try enabling "Force IPv4 addresses first" in the Add-ons settings
> 
> ![image](https://private-user-images.githubusercontent.com/92803991/345085622-cb7caed8-9992-448a-9806-6e44cd141c0d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk5OTA5ODEsIm5iZiI6MTcxOTk5MDY4MSwicGF0aCI6Ii85MjgwMzk5MS8zNDUwODU2MjItY2I3Y2FlZDgtOTk5Mi00NDhhLTk4MDYtNmU0NGNkMTQxYzBkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzAzVDA3MTEyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIyMGQyYzYyMmNlMTM5ZTM0NjUzOTI4Njk3MDY5YWQ1N2RiZDQyYjEwNGI3YzE0NDIxMmExMDViOTliZjRiOTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.eKBsg4cVINUjMhGgYLX1hLihk3ApDMlOE44VhdOttEI)

Confirmed working for me! I had to reload the integration after modifying this setting in the add-on and afterwards it was working again.

**Comment by PatBrick2712** [comment]
This "Force ipv4 addressess first" solution didn't work for me. Problem is still the same. After restarting the eufy-security-ws add-on and then reload the eufy security integration it works for a few hours.

**Comment by mjacoulet** [comment]
This worked for me too... Thanks for the tips @clarky860 

> Try enabling "Force IPv4 addresses first" in the Add-ons settings
> 
> ![image](https://private-user-images.githubusercontent.com/92803991/345085622-cb7caed8-9992-448a-9806-6e44cd141c0d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE0MDU5MjYsIm5iZiI6MTcyMTQwNTYyNiwicGF0aCI6Ii85MjgwMzk5MS8zNDUwODU2MjItY2I3Y2FlZDgtOTk5Mi00NDhhLTk4MDYtNmU0NGNkMTQxYzBkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE5VDE2MTM0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlkMmJkZTEwMTNmYmYyOGIxNzZkYjE3ZDU4MDcxMjM4ODIzNmI5NWY5OTU5NjVhMjA1NjNkNGIwOTQ3ZTcyZGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Fzrh4oW3IvvY8KVgcuQOOAi6ps6xOvuAz_9s1YusY2I)

**Comment by fuatakgun** [comment]
If add-on is not running, integration cannot function at all.

**Comment by alyyousuf7** [comment]
I have `Force IPv4 addresses first` toggled on, and after some time, the add-on failed with: `Connection to Eufy Security add-on is broken, retrying in background!`

system info:
```
Core: 2024.7.4
Supervisor: 2024.08.0
Operating System: 12.4
Frontend: 20240710.0

eufy-security-ws: 1.8.0-2 
eufy_security: 8.0.2
```

logs from `eufy-security-ws`: These ones are repeating:
```
2024-08-07 07:11:28.179	DEBUG	eufy-security-ws:eufy-security-client	[p2p] [P2PClientProtocol.handleDataBinaryAndVideo] Handle DATA VIDEO - Not implemented message {
  stationSN: 'STATION-SERIAL-NO',
  commandIdName: undefined,
  commandId: 0,
  channel: 0,
  data: ''
}
```

logs from `eufy_security`:

```
2024-08-07 01:39:38.799 DEBUG (MainThread) [custom_components.eufy_security] coordinator - complete update_local
2024-08-07 01:39:38.799 DEBUG (MainThread) [custom_components.eufy_security] Finished fetching eufy_security data in 1.348 seconds (success: True)
2024-08-07 01:47:20.888 DEBUG (SyncWorker_24) [custom_components.eufy_security.eufy_security_api] write_bytes video - post response - 500 - EOF
2024-08-07 01:47:20.888 DEBUG (SyncWorker_24) [custom_components.eufy_security.eufy_security_api] write_bytes - post ended - {self.retry}
2024-08-07 01:47:20.888 DEBUG (SyncWorker_24) [custom_components.eufy_security.eufy_security_api] write_bytes video - ended with True
2024-08-07 01:47:20.908 DEBUG (SyncWorker_14) [custom_components.eufy_security.eufy_security_api] write_bytes video - post response - 500 - EOF
2024-08-07 01:47:20.909 DEBUG (SyncWorker_14) [custom_components.eufy_security.eufy_security_api] write_bytes - post ended - {self.retry}
2024-08-07 01:47:20.909 DEBUG (SyncWorker_14) [custom_components.eufy_security.eufy_security_api] write_bytes video - ended with True
2024-08-07 01:47:21.228 DEBUG (MainThread) [custom_components.eufy_security.eufy_security_api] async_restart_livestream - start - True
2024-08-07 01:47:21.228 DEBUG (MainThread) [custom_components.eufy_security.eufy_security_api] domain - device - EventSourceType.device - device.stop_livestream - {'serial_no': 'CAM2-SERIAL-NO'} - {'serialNumber': 'CAM2-SERIAL-NO'}
2024-08-07 01:47:21.228 DEBUG (MainThread) [custom_components.eufy_security.eufy_security_api] {'serialNumber': 'CAM2-SERIAL-NO', 'command': 'device.stop_livestream', 'messageId': 'device.stop_livestream.CAM1-ID'}
2024-08-07 01:47:21.228 DEBUG (MainThread) [custom_components.eufy_security.eufy_security_api] send_message - {'serialNumber': 'CAM2-SERIAL-NO', 'command': 'device.stop_livestream', 'messageId': 'device.stop_livestream.CAM1-ID'}
2024-08-07 01:47:21.229 DEBUG (MainThread) [custom_components.eufy_security.eufy_security_api] async_restart_livestream - start - True
2024-08-07 01:47:21.229 DEBUG (MainThread) [custom_components.eufy_security.eufy_security_api] domain - device - EventSourceType.device - device.stop_livestream - {'serial_no': 'CAM2-SERIAL-NO'} - {'serialNumber': 'CAM2-SERIAL-NO'}
2024-08-07 01:47:21.229 DEBUG (MainThread) [custom_components.eufy_security.eufy_security_api] {'serialNumber': 'CAM2-SERIAL-NO', 'command': 'device.stop_livestream', 'messageId': 'device.stop_livestream.CAM2-ID'}
2024-08-07 01:47:21.229 DEBUG (MainThread) [custom_components.eufy_security.eufy_security_api] send_message - {'serialNumber': 'CAM2-SERIAL-NO', 'command': 'device.stop_livestream', 'messageId': 'device.stop_livestream.CAM2-ID'}
2024-08-07 01:47:35.340 DEBUG (MainThread) [custom_components.eufy_security.eufy_security_api] websocket client _on_close False
2024-08-07 01:47:35.340 DEBUG (MainThread) [custom_components.eufy_security.eufy_security_api] on_close - executed - <Task finished name='Task-9150' coro=<WebSocketClient._process_messages() done, defined at /config/custom_components/eufy_security/eufy_security_api/web_socket_client.py:62> result=None> = None
2024-08-07 01:47:40.341 DEBUG (MainThread) [custom_components.eufy_security] async_unload_entry 1
2024-08-07 01:47:40.342 DEBUG (MainThread) [custom_components.eufy_security] async_unload_entry 2
```

**Comment by Escovan** [comment]
Same problem in latest HA
```
Eufy Security - Error
Connection to Eufy Security add-on is broken, retrying in background!
```
Just installed this but it's quite buggy it seems. Found you guys...
Also, this crashing of the addon comes with maximum load for a single core on my dedicated HA x86-64-box... Making the active cooling spin up, and causing some noise. Don't like it. A forced restart of the plugin seems to fix it temporarily. 
![image](https://github.com/user-attachments/assets/f9680634-ef00-433f-b7cc-2a1f3c04eaa8)

**Comment by clarky860** [comment]
![image](https://github.com/user-attachments/assets/646fe9ba-7cae-4770-a2f1-edcc3ade3e21)
I just added this automation as I still have to restart the service every now and again
