### ISSUE TITLE
Host/Port Wrong on Setup

### ISSUE THREAD

**Issue by bjaurelio** [fuatakgun/eufy_security#1173]
Please check existing (open or closed) issues before creating a new one. (https://github.com/fuatakgun/eufy_security/issues?q=is%3Aissue+)

If this is not an issue, you can use `Discussions` (https://github.com/fuatakgun/eufy_security/discussions) section.

I am trying to setup the integration in my Home Assistant. I am running the latest version as a VM in Unraid. After installing Eufy Security through HACS, I restarted Home Assistant and attempted several times to add the integration. Every time I receive an error that the "Host/Port is wrong." I even tried changing the IP address to the IP for the VM on my local network. That did not work either.

![image](https://github.com/fuatakgun/eufy_security/assets/91978516/3f128766-2ed5-4dfd-b58e-5253c053ab84)

Attempt to add integration

1. Go to 'Settings/Devices and Services'
2. Click on 'Add Integration'
3. Click on 'Submit'

**Additional information**

Go to Settings -> System -> Repairs -> Click on 3 dots (...) -> System Information and get Version and Installation Type to below fields;
- Home Assistant Installation Type (OS - Supvervised - Core): Home Assistant OS 12.4
- Home Assistant Core Version: core-2024.7.1
- Eufy Security Add-on Version: 8.0.2
- Eufy Security Integration Version:

Hardware Information;
- Camera Model:

N/A

- Live Streaming Protocol (RTSP/P2P): 
N/A

- Debug Logs from Home Assistant (https://github.com/fuatakgun/eufy_security/discussions/624) - Without this, I will automatically resolve this issue
  
`2024-07-09 23:24:03.885 ERROR (MainThread) [custom_components.eufy_security.config_flow] eufy_security Exception in login : Connection to add-on was broken. please reload the integration! - traceback: Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/aiohttp/connector.py", line 1025, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1122, in create_connection
    raise exceptions[0]
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1104, in create_connection
    sock = await self._connect_sock(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1007, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/local/lib/python3.12/asyncio/selector_events.py", line 641, in sock_connect
    return await fut
           ^^^^^^^^^
  File "/usr/local/lib/python3.12/asyncio/selector_events.py", line 681, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 111] Connect call failed ('127.0.0.1', 3000)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/eufy_security/eufy_security_api/web_socket_client.py", line 42, in connect
    self.socket = await self.session.ws_connect(f"ws://{self.host}:{self.port}", heartbeat=10, compress=9)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/client.py", line 835, in _ws_connect
    resp = await self.request(
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/client.py", line 581, in _request
    conn = await self._connector.connect(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/connector.py", line 544, in connect
    proto = await self._create_connection(req, traces, timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/connector.py", line 944, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/connector.py", line 1257, in _create_direct_connection
    raise last_exc
  File "/usr/local/lib/python3.12/site-packages/aiohttp/connector.py", line 1226, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/connector.py", line 1033, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host 127.0.0.1:3000 ssl:default [Connect call failed ('127.0.0.1', 3000)]

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/eufy_security/config_flow.py", line 123, in _test_credentials
    await api_client.ws_connect()
  File "/config/custom_components/eufy_security/eufy_security_api/api_client.py", line 66, in ws_connect
    await self._client.connect()
  File "/config/custom_components/eufy_security/eufy_security_api/web_socket_client.py", line 44, in connect
    raise WebSocketConnectionException("Connection to add-on was broken. please reload the integration!") from exc
custom_components.eufy_security.eufy_security_api.exceptions.WebSocketConnectionException: Connection to add-on was broken. please reload the integration!

2024-07-09 23:24:12.637 ERROR (MainThread) [custom_components.eufy_security.config_flow] eufy_security Exception in login : Connection to add-on was broken. please reload the integration! - traceback: Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/aiohttp/connector.py", line 1025, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1122, in create_connection
    raise exceptions[0]
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1104, in create_connection
    sock = await self._connect_sock(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1007, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/local/lib/python3.12/asyncio/selector_events.py", line 641, in sock_connect
    return await fut
           ^^^^^^^^^
  File "/usr/local/lib/python3.12/asyncio/selector_events.py", line 681, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 111] Connect call failed ('192.168.1.190', 3000)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/eufy_security/eufy_security_api/web_socket_client.py", line 42, in connect
    self.socket = await self.session.ws_connect(f"ws://{self.host}:{self.port}", heartbeat=10, compress=9)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/client.py", line 835, in _ws_connect
    resp = await self.request(
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/client.py", line 581, in _request
    conn = await self._connector.connect(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/connector.py", line 544, in connect
    proto = await self._create_connection(req, traces, timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/connector.py", line 944, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/connector.py", line 1257, in _create_direct_connection
    raise last_exc
  File "/usr/local/lib/python3.12/site-packages/aiohttp/connector.py", line 1226, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/connector.py", line 1033, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host 192.168.1.190:3000 ssl:default [Connect call failed ('192.168.1.190', 3000)]

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/eufy_security/config_flow.py", line 123, in _test_credentials
    await api_client.ws_connect()
  File "/config/custom_components/eufy_security/eufy_security_api/api_client.py", line 66, in ws_connect
    await self._client.connect()
  File "/config/custom_components/eufy_security/eufy_security_api/web_socket_client.py", line 44, in connect
    raise WebSocketConnectionException("Connection to add-on was broken. please reload the integration!") from exc
custom_components.eufy_security.eufy_security_api.exceptions.WebSocketConnectionException: Connection to add-on was broken. please reload the integration!`

- Logs from Eufy Security Add-on (either from Add-ons page of Home Assistant or Docker output):

No logs due to being unable to add the integration

- Would you share your device with me in case further debugging required? (Yes/No):

Nothing to share because cannot add devices.

**Additional context**

Add any other context about the problem goes here. Mainly, share everything as log files and use screenshots as last resort.

**Comment by bengarding** [comment]
I just ran into this, my issue was that the add-on hadn't actually been started.

**Comment by bjaurelio** [comment]
That fixed my problem. Thanks!
