### ISSUE TITLE
Failed to unload

### ISSUE THREAD

**Issue by LasseLegarth** [fuatakgun/eufy_security#1203]
I get "failed to unload", after I've pressed "restart" on the eufy-security-ws under addons.
![image](https://github.com/user-attachments/assets/916be322-baca-4835-aca9-de5cc1d73ea2)

Just restart eufy-security-ws under addons.

This is my logfile:

2024-09-14 21:21:03.573 ERROR (MainThread) [homeassistant.config_entries] Error unloading entry 127.0.0.1 for eufy_security
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 819, in async_unload
    result = await component.async_unload_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/eufy_security/__init__.py", line 69, in async_unload_entry
    unloaded = await hass.config_entries.async_unload_platforms(entry, PLATFORMS)
                                                                ^^^^^
NameError: name 'entry' is not defined. Did you mean: 'entity'?

**Expected behavior**

That I can restart eufy-security-ws without having to restart all of home assistant :) I have 10 lamps from eufy, and unless I restart it once in a while, I lose connection to one or more lamps - so being able to restart it is quite important.

**Additional information**

Go to Settings -> System -> Repairs -> Click on 3 dots (...) -> System Information and get Version and Installation Type to below fields;
Version 	core-2024.9.1
Installation type 	Home Assistant OS
eufy-security-ws (1.9.0),
Eufy Security Integration Version: 8.0.3 - The issue was not there in the previous version.

- Would you share your device with me in case further debugging required? (Yes/No): Its not a device issue I think ...

**Comment by rammstone83** [comment]
same problem here :(
