### ISSUE TITLE
Eufy T8214 P2P not working

### ISSUE THREAD

**Issue by s-hardt** [fuatakgun/eufy_security#1211]
**Describe the bug**

When using the T8214 camera, the P2P stream does not work. It shows preparing, but never streaming.
And the status is stuck at preparing for the camera.

**To reproduce**

Just start the P2P streaming is enough to see the issue.

**Expected behavior**

**Additional information**
- Home Assistant Installation Type (OS - Supvervised - Core): 	Home Assistant OS
- Home Assistant Core Version: core-2024.9.2
- Eufy Security Add-on Version: 1.9.0
- Eufy Security Integration Version: 8.0.4

Hardware Information;
- Camera Model: Eufy T8214

- Live Streaming Protocol (RTSP/P2P):  The camera only supports P2P

- Debug Logs from Home Assistant (https://github.com/fuatakgun/eufy_security/discussions/624) - Without this, I will automatically resolve this issue
  2024-09-22 12:47:37.631 DEBUG (MainThread) [custom_components.eufy_security.eufy_security_api] url - StreamProvider.P2P - rtsp://127.0.0.1:8554/T821451024110CEA
2024-09-22 12:47:37.631 DEBUG (MainThread) [custom_components.eufy_security.eufy_security_api] _initiate_start_stream - info - send command to add-on - StreamProvider.P2P
2024-09-22 12:47:37.631 DEBUG (MainThread) [custom_components.eufy_security.eufy_security_api] domain - device - EventSourceType.device - device.start_livestream - {'serial_no': 'T821451024110CEA'} - {'serialNumber': 'T821451024110CEA'}
2024-09-22 12:47:37.631 DEBUG (MainThread) [custom_components.eufy_security.eufy_security_api] {'serialNumber': 'T821451024110CEA', 'command': 'device.start_livestream', 'messageId': 'device.start_livestream.d1ea61280b5148818c09b23f4886c77b'}
2024-09-22 12:47:37.631 DEBUG (MainThread) [custom_components.eufy_security.eufy_security_api] send_message - {'serialNumber': 'T821451024110CEA', 'command': 'device.start_livestream', 'messageId': 'device.start_livestream.d1ea61280b5148818c09b23f4886c77b'}
2024-09-22 12:47:37.640 DEBUG (MainThread) [custom_components.eufy_security.eufy_security_api] _on_message - {'type': 'result', 'success': True, 'messageId': 'device.start_livestream.d1ea61280b5148818c09b23f4886c77b', 'result': {'async': True}}
2024-09-22 12:47:39.783 DEBUG (MainThread) [custom_components.eufy_security.eufy_security_api] _on_message - {'type': 'event', 'event': {'source': 'station', 'event': 'connected', 'serialNumber': 'T821451024110CEA'}}
2024-09-22 12:47:40.092 DEBUG (MainThread) [custom_components.eufy_security.eufy_security_api] _on_message - {'type': 'event', 'event': {'source': 'device', 'event': 'command result', 'serialNumber': 'T821451024110CEA', 'command': 'start_livestream', 'returnCode': 0, 'returnCodeName': 'ERROR_PPCS_SUCCESSFUL', 'customData': {'command': {'name': 'deviceStartLivestream', 'value': 0}}}}
2024-09-22 12:47:40.092 DEBUG (MainThread) [custom_components.eufy_security.eufy_security_api] event not handled -T821451024110CEA - Event(type='command result', data={'source': 'device', 'event': 'command result', 'serialNumber': 'T821451024110CEA', 'command': 'start_livestream', 'returnCode': 0, 'returnCodeName': 'ERROR_PPCS_SUCCESSFUL', 'customData': {'command': {'name': 'deviceStartLivestream', 'value': 0}}})
2024-09-22 12:47:40.491 DEBUG (MainThread) [custom_components.eufy_security.eufy_security_api] _on_message - {'type': 'event', 'event': {'source': 'station', 'event': 'database query latest', 'serialNumber': 'T821451024110CEA', 'returnCode': -1100, 'data': []}}
2024-09-22 12:47:40.492 DEBUG (MainThread) [custom_components.eufy_security.eufy_security_api] event not handled -T821451024110CEA - Event(type='database query latest', data={'source': 'station', 'event': 'database query latest', 'serialNumber': 'T821451024110CEA', 'returnCode': -1100, 'data': []})
2024-09-22 12:47:42.642 DEBUG (MainThread) [custom_components.eufy_security.eufy_security_api] _initiate_start_stream - error - command was failed - <asyncio.locks.Event object at 0x7fa1b328baa0 [unset]>
2024-09-22 12:47:45.151 DEBUG (MainThread) [custom_components.eufy_security.eufy_security_api] _on_message - {'type': 'event', 'event': {'source': 'device', 'event': 'command result', 'serialNumber': 'T821451024110CEA', 'command': 'stop_livestream', 'returnCode': 0, 'returnCodeName': 'ERROR_PPCS_SUCCESSFUL', 'customData': {'command': {'name': 'deviceStopLivestream'}}}}
2024-09-22 12:47:45.152 DEBUG (MainThread) [custom_components.eufy_security.eufy_security_api] event not handled -T821451024110CEA - Event(type='command result', data={'source': 'device', 'event': 'command result', 'serialNumber': 'T821451024110CEA', 'command': 'stop_livestream', 'returnCode': 0, 'returnCodeName': 'ERROR_PPCS_SUCCESSFUL', 'customData': {'command': {'name': 'deviceStopLivestream'}}})
2024-09-22 12:48:01.091 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_protocol.py", line 462, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_app.py", line 537, in _handle
    resp = await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_middlewares.py", line 114, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 92, in security_filter_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 83, in forwarded_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 26, in request_context_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 85, in ban_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 242, in auth_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/headers.py", line 32, in headers_middleware
    response = await handler(request)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/http.py", line 73, in handle
    result = await handler(request, **request.match_info)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/webrtc/__init__.py", line 256, in get
    return await ws_poster(hass, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/webrtc/__init__.py", line 207, in ws_poster
    image_entity = _get_image_from_entity_id(hass, poster)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/webrtc/__init__.py", line 188, in _get_image_from_entity_id
    raise Exception("Image not found")
Exception: Image not found
2024-09-22 12:48:15.153 DEBUG (MainThread) [custom_components.eufy_security.eufy_security_api] _on_message - {'type': 'event', 'event': {'source': 'station', 'event': 'disconnected', 'serialNumber': 'T821451024110CEA'}}
2024-09-22 12:48:59.103 DEBUG (MainThread) [custom_components.eufy_security.eufy_security_api] _on_message - {'type': 'event', 'event': {'source': 'device', 'event': 'property changed', 'serialNumber': 'T821451024110CEA', 'name': 'wifiRssi', 'value': -63}}
2024-09-22 12:48:59.103 DEBUG (MainThread) [custom_components.eufy_security.eufy_security_api] camera _handle_property_changed - wifiRssi
2024-09-22 12:48:59.108 DEBUG (MainThread) [custom_components.eufy_security.eufy_security_api] _on_message - {'type': 'event', 'event': {'source': 'device', 'event': 'property changed', 'serialNumber': 'T821451024110CEA', 'name': 'batteryTemperature', 'value': 30}}
2024-09-22 12:48:59.108 DEBUG (MainThread) [custom_components.eufy_security.eufy_security_api] camera _handle_property_changed - batteryTemperature
2024-09-22 12:49:02.587 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_protocol.py", line 462, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_app.py", line 537, in _handle
    resp = await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_middlewares.py", line 114, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 92, in security_filter_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 83, in forwarded_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 26, in request_context_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 85, in ban_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 242, in auth_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/headers.py", line 32, in headers_middleware
    response = await handler(request)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/http.py", line 73, in handle
    result = await handler(request, **request.match_info)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/webrtc/__init__.py", line 256, in get
    return await ws_poster(hass, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/webrtc/__init__.py", line 207, in ws_poster
    image_entity = _get_image_from_entity_id(hass, poster)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/webrtc/__init__.py", line 188, in _get_image_from_entity_id
    raise Exception("Image not found")
Exception: Image not found
2024-09-22 12:49:06.817 DEBUG (MainThread) [custom_components.eufy_security] coordinator - start update_local
2024-09-22 12:49:06.817 DEBUG (MainThread) [custom_components.eufy_security.eufy_security_api] domain - driver - EventSourceType.driver - driver.poll_refresh - {} - {}
2024-09-22 12:49:06.817 DEBUG (MainThread) [custom_components.eufy_security.eufy_security_api] {'command': 'driver.poll_refresh', 'messageId': 'driver.poll_refresh.0c13d576262443529b4558882614afa1'}
2024-09-22 12:49:06.817 DEBUG (MainThread) [custom_components.eufy_security.eufy_security_api] send_message - {'command': 'driver.poll_refresh', 'messageId': 'driver.poll_refresh.0c13d576262443529b4558882614afa1'}
2024-09-22 12:49:07.074 DEBUG (MainThread) [custom_components.eufy_security.eufy_security_api] _on_message - {'type': 'result', 'success': True, 'messageId': 'driver.poll_refresh.0c13d576262443529b4558882614afa1', 'result': {}}

- Logs from Eufy Security Add-on (either from Add-ons page of Home Assistant or Docker output):
2024-09-22 10:48:09.819	DEBUG	eufy-security-ws:eufy-security-client	[p2p] [P2PClientProtocol.handleMsg] Received message - DATA CONTROL - Processing sequence 28... {
  stationSN: 'T821451024110CEA',
  remoteAddress: '89.247.147.177',
  remotePort: 14435,
  dataType: 'CONTROL',
  seqNo: 28
}
2024-09-22 10:48:09.827	DEBUG	eufy-security-ws:eufy-security-client	[p2p] [P2PClientProtocol.handleMsg] Received message - DATA CONTROL - Processing sequence 28... {
  stationSN: 'T821451024110CEA',
  remoteAddress: '89.247.147.177',
  remotePort: 14435,
  dataType: 'CONTROL',
  seqNo: 28
}
2024-09-22 10:48:11.807	DEBUG	eufy-security-ws:eufy-security-client	[p2p] [P2PClientProtocol._sendCommand] Sending p2p command... {
  station: 'T821451024110CEA',
  sequence: 21,
  commandType: 1139,
  channel: 255,
  retries: 0,
  messageStatesSize: 1
}
2024-09-22 10:48:11.830	DEBUG	eufy-security-ws:eufy-security-client	[p2p] [P2PClientProtocol.handleMsg] Received message - DATA CONTROL - Processing sequence 29... {
  stationSN: 'T821451024110CEA',
  remoteAddress: '89.247.147.177',
  remotePort: 14435,
  dataType: 'CONTROL',
  seqNo: 29
}
2024-09-22 10:48:13.808	DEBUG	eufy-security-ws:eufy-security-client	[p2p] [P2PClientProtocol._sendCommand] Sending p2p command... {
  station: 'T821451024110CEA',
  sequence: 22,
  commandType: 1139,
  channel: 255,
  retries: 0,
  messageStatesSize: 1
}
2024-09-22 10:48:13.820	DEBUG	eufy-security-ws:eufy-security-client	[p2p] [P2PClientProtocol.handleMsg] Received message - DATA CONTROL - Processing sequence 30... {
  stationSN: 'T821451024110CEA',
  remoteAddress: '89.247.147.177',
  remotePort: 14435,
  dataType: 'CONTROL',
  seqNo: 30
}
2024-09-22 10:48:13.826	DEBUG	eufy-security-ws:eufy-security-client	[p2p] [P2PClientProtocol.handleMsg] Received message - DATA CONTROL - Processing sequence 30... {
  stationSN: 'T821451024110CEA',
  remoteAddress: '89.247.147.177',
  remotePort: 14435,
  dataType: 'CONTROL',
  seqNo: 30
}
2024-09-22 10:48:15.152	INFO	eufy-security-ws:eufy-security-client	[p2p] [Timeout._onTimeout] Initiated closing of connection to station T821451024110CEA for saving battery.
2024-09-22 10:48:15.152	INFO	eufy-security-ws:eufy-security-client	[http] [Station.onDisconnect] Disconnected from station T821451024110CEA
2024-09-22 10:48:15.541	DEBUG	eufy-security-ws:eufy-security-client	[p2p] [P2PClientProtocol.handleMsg] Received message - END {
  stationSN: 'T821451024110CEA',
  remoteAddress: '89.247.147.177',
  remotePort: 14435
}

- Would you share your device with me in case further debugging required? (Yes/No):
Yes, I would love to share it with you.

**Comment by cyborcc** [comment]
+1
I am experiencing the same issue. I have tested different versions, both Hass.io and Docker, but encountered the same result: It shows "Preparing" but never starts streaming.

Additional information
- Home Assistant Installation Type (OS - Supvervised - Core): Home Assistant OS & Docker
- Home Assistant Core Version: core-2024.10.3
- Eufy Security Add-on Version: 1.9.1
- Eufy Security Integration Version: 8.0.4

LOG: same as @s-hardt 
}
2024-10-20 10:28:20.758	DEBUG	eufy-security-ws:eufy-security-client	[p2p] [P2PClientProtocol._sendCommand] Sending p2p command... {
  station: 'xxx',
  sequence: 22,
  commandType: 1139,
  channel: 255,
  retries: 0,
  messageStatesSize: 1
}
2024-10-20 10:28:20.774	DEBUG	eufy-security-ws:eufy-security-client	[p2p] [P2PClientProtocol.handleMsg] Received message - DATA CONTROL - Processing sequence 32... {
  stationSN: 'xxx',
  remoteAddress: '192.168.178.64',
  remotePort: 12132,
  dataType: 'CONTROL',
  seqNo: 32
}
2024-10-20 10:28:20.780	DEBUG	eufy-security-ws:eufy-security-client	[p2p] [P2PClientProtocol.handleMsg] Received message - DATA CONTROL - Processing sequence 32... {
  stationSN: 'xxx',
  remoteAddress: '192.168.178.64',
  remotePort: 12132,
  dataType: 'CONTROL',
  seqNo: 32
}
2024-10-20 10:28:22.061	INFO	eufy-security-ws:eufy-security-client	[p2p] [Timeout._onTimeout] Initiated closing of connection to station T82145102414163C for saving battery.
2024-10-20 10:28:22.061	INFO	eufy-security-ws:eufy-security-client	[http] [Station.onDisconnect] Disconnected from station T82145102414163C
2024-10-20 10:28:22.304	DEBUG	eufy-security-ws:eufy-security-client	[p2p] [P2PClientProtocol.handleMsg] Received message - END {
  stationSN: 'xxx',
  remoteAddress: '192.168.178.64',
  remotePort: 12132
}

Would you share your device with me in case further debugging required? (Yes/No):
Yes, I would love to share it with you.

Thank you

**Comment by supermina999** [comment]
+1
I'm experiencing the same issue with T8214

**Comment by Be4fun** [comment]
Same for me. The p2p stream stays in preparing. 
thanks for having a look at it

**Comment by nicoh88** [comment]
+1

Same here. 
The p2p stream stays in preparing, can not be stopped or started ...

Thansk for your hard work @fuatakgun

**Comment by fuatakgun** [comment]
we have checked the issue and it is with add-on.

```
2024-11-13 20:34:44.213 INFO eufy-security-ws:eufy-security-client
[main] Push notification connection successfully established
2024-11-13 20:35:03.620 INFO eufy-security-ws:eufy-security-client
[p2p] [Timeout._onTimeout] Initiated closing of connection to station
T82145102414163C for saving battery.
2024-11-13 20:35:03.621 INFO eufy-security-ws:eufy-security-client
[http] [Station.onDisconnect] Disconnected from station
T8214xxx
2024-11-13 20:35:44.492 INFO eufy-security-ws:eufy-security-client
[http] [Station.onConnect] Connected to station T8214xxx on
host 46.128.254.194 and port 10274
2024-11-13 20:35:49.868 INFO eufy-security-ws:eufy-security-client
[p2p] [Timeout._onTimeout] Stopping the station stream for the device
T8214xxx, because we haven't received any data for 5 seconds
2024-11-13 20:36:19.922 INFO eufy-security-ws:eufy-security-client
[p2p] [Timeout._onTimeout] Initiated closing of connection to station
T8214xxx for saving battery.
2024-11-13 20:36:19.923 INFO eufy-security-ws:eufy-security-client
```

**Comment by cyborcc** [comment]
Thank you, @fuatakgun  
I've created a new issue for this: @bropat  
https://github.com/bropat/eufy-security-ws/issues/374

If you’re experiencing the same problem, please consider adding a "+1".

**Comment by SBFGwolD** [comment]
+ 1

Hard wired E340.
