### ISSUE TITLE
Homebase 2 Guard Mode Does Not Update

### ISSUE THREAD

**Issue by Calcue-dev** [fuatakgun/eufy_security#1223]
Logging this issue, but also want to share my love for this integration! It is amazing but unfortunately just hitting this issue.

**Describe the bug**

I am using Eufy Homebase 2 with 3 door contact sensors and a keypad. I have been using this add on and it works amazingly. However, lately I have noticed random failures to update the Homebase arm mode. If I attempt to set the Homebase to Away (or any setting) it just will not apply. However, if I go into the Eufy app and set the Homebase to Away it works and in Home Assistant it does in fact pick this up and see that it is set to Away. However, from Home Assistant I still cannot set it to Home or anything else. Randomly it will recover from this over a period of time (unsure why?).

**To reproduce**

(note: I am unsure how to get the Home Assistant to a state where this happens)

1. Go to Home Assistant
2. Click on Home Base and set Mode to Home or Away

**Expected behavior**

The Base Station should be set to the desired setting.

**Logs**
```bash
Logger: homeassistant
Source: custom_components/eufy_security/eufy_security_api/web_socket_client.py:63
integration: Eufy Security ([documentation](https://github.com/fuatakgun/eufy_security), [issues](https://github.com/fuatakgun/eufy_security/issues))
First occurred: 7:03:29 PM (1 occurrences)
Last logged: 7:03:29 PM

Error doing job: Exception in callback WebSocketClient._on_close(<Task cancell...client.py:62>>) (None)
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/config/custom_components/eufy_security/eufy_security_api/web_socket_client.py", line 81, in _on_close
    self.close_callback(future)
  File "/config/custom_components/eufy_security/eufy_security_api/api_client.py", line 317, in _on_close
    _LOGGER.debug(f"on_close - executed - {future} = {future.exception()}")
                                                      ^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/eufy_security/eufy_security_api/web_socket_client.py", line 63, in _process_messages
    async for msg in self.socket:
  File "/usr/local/lib/python3.12/site-packages/aiohttp/client_ws.py", line 384, in __anext__
    msg = await self.receive()
          ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/client_ws.py", line 315, in receive
    msg = await self._reader.read()
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/streams.py", line 684, in read
    return await super().read()
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/streams.py", line 643, in read
    await self._waiter
asyncio.exceptions.CancelledError
```

**Additional information**

Go to Settings -> System -> Repairs -> Click on 3 dots (...) -> System Information and get Version and Installation Type to below fields;
- **Home Assistant Installation Type:** Home Assistant OS
- **Home Assistant Core Version:** core-2024.10.2
- **Eufy Security Add-on Version:** 1.9.1
- **Eufy Security Integration Version:** 8.0.4

Hardware Information;
- **Homebase Mode:** Homebase 2, System Version 3.3.5.0h, Subsystem Version: 1.3.0.9

  

- Would you share your device with me in case further debugging required? (Yes/No): **YES**

**Comment by Calcue-dev** [comment]
Restarting and reloading the integration and add-on allows it to begin working again. However, I will keep an eye on if it enters a failure state again. Will keep this open for now.

**Comment by srikb42** [comment]
This exact same issue happened to me today. Doesn't change the mode at all, whether from developer tools OR automations OR direct dashboard. Restarting the add-on worked though. (Only reloading the integration didn't work, add-on restart was required).  I will also keep an eye when this happens next time to gather more information. Thanks for keeping this open.

**Comment by fuatakgun** [comment]
To be honest, I have an automation to restart the add-on every night to keep everything under control,

Check add-on logs, for me, usually it goes down after long time.

**Comment by henninghartwig** [comment]
same here. But thanks to srikb42 it is working again. Restarting the addon is the key. Before I was just rebooting the homebase and reloading the integration, which did not work. Built an automation like fuatakgun suggested. Should be fixed though

**Comment by shkb42** [comment]
> I have a same issue please help me

Tbh my automation still runs, restarts(only) the add-on every night 2am. After that automation schedule,  never had this issue. I'd suggest you to do the same atleast until this is fixed.
