### ISSUE TITLE
Eufy security installation crahed after update core

### ISSUE THREAD

**Issue by Kruikie349** [fuatakgun/eufy_security#1259]
Can someone help me with the following problem?

I have installed the Eufy-security integration on :

Core                        2024.12.0.dev202410310231
Supervisor               2024.11.5.dev2801
Operating System   14.1.dev20241125
Frontend                  20241031.0.dev

That works fine ,

But when I update HA to Latest version Home Assistant Core
2025.1.0.dev202411280234 the Eufy-security integration chrahed completely. The integration can also not be removed and can not be reloaded.

Thanks for your support

Rob (Netherlands)

**Comment by deiniolj** [comment]
I have the same issue. I have automation that run off these cameras. Which are now useless.

**Comment by Kruikie349** [comment]
Hello Fuat, thanks for your answer.  I am not even sure what is the issue? Do you mean, you don't understand what I mean or  you don't know what is causing this problem?

**Comment by piitaya** [comment]
@Kruikie349 Can you check your logs? I'm pretty sure it's related to this one : https://github.com/fuatakgun/eufy_security/issues/1258

**Comment by Kruikie349** [comment]
@piitaya  I think what you say is correct because I saw something like that a few days ago in the logs. When I install 2025.1.0.dev202411280234  crash Eufy security, but there is no error message in the log .

**Comment by eikowagenknecht** [comment]
On 2024.12 final it‘s also not working.

Logger: homeassistant.loader
Source: loader.py:1074
First occurred: 22:43:13 (2 occurrences)
Last logged: 22:43:13

Unexpected exception importing component custom_components.eufy_security
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1074, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 200, in protected_loop_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.13/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 1022, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/eufy_security/__init__.py", line 13, in <module>
    from .const import COORDINATOR, DOMAIN, PLATFORMS
  File "/config/custom_components/eufy_security/const.py", line 16, in <module>
    from .model import EntityDescription
  File "/config/custom_components/eufy_security/model.py", line 19, in <module>
    class ConfigField(Enum):
    ...<14 lines>...
        mfa_input = auto()
  File "/config/custom_components/eufy_security/model.py", line 25, in ConfigField
    rtsp_server_address = auto()
    ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/enum.py", line 431, in __setitem__
    v.value = self._generate_next_value(
              ~~~~~~~~~~~~~~~~~~~~~~~~~^
            key, 1, len(self._member_names), self._last_values[:],
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
            )
            ^
  File "/usr/local/lib/python3.13/enum.py", line 1248, in _generate_next_value_
    raise TypeError('unable to sort non-numeric values') from None
TypeError: unable to sort non-numeric values

**Comment by fuatakgun** [comment]
Please get the latest version, just published 20 minutes ago

**Comment by Kruikie349** [comment]
Thank you so much

great,

Rob

Op wo 4 dec 2024 om 23:42 schreef Fuat Akgün ***@***.***>:

**Comment by R-ens** [comment]
I kind have the same issue: https://github.com/fuatakgun/eufy_security/issues/1258#issuecomment-2522788300
But i don't have any logging.... The entire component is not loading or something.

**Comment by fivergj** [comment]
Apologies for a basic question but I've only just started with HA....

I have a non-functioning v8,1 installed and tried reinstalling the integration via Add Integration - got an error.

I don't want to make things worse so what it the proper method?

Should I uninstall the current version and reinstall?
Is it a matter of manually copying files?
Would it be simpler/safer to revert to previous version of HA and update the integration from there?

Thank you
