### ISSUE TITLE
Support Request for T8531 Smart door camera lock

### ISSUE THREAD

**Issue by asan2020** [fuatakgun/eufy_security#1263]
Support request for T8531 Smart door lock with Camera

On enabling the add-on and the HACS integration I get only 2 active sensor Debug (device) and Debug (Station). Expect to see a camera stream and Lock/Unlock options. Tried on HA Supervised and Core versions (with Eufy-Security-Ws docker) with the same output

**Additional information**

Go to Settings -> System -> Repairs -> Click on 3 dots (...) -> System Information and get Version and Installation Type to below fields;
- Home Assistant Installation Type (OS - Supvervised - Core): 13.2
- Home Assistant Core Version:  2024.11.3
- Eufy Security Add-on Version: 1.9.1
- Eufy Security Integration Version: 8.1.0
- Using go2rtc Add-on or webrtc custom integration with integrated go2rtc: Webrtc 3.6.0

Hardware Information;
- Camera Model: E330 T8531

- Live Streaming Protocol (RTSP/P2P): Not working. Do not see the lock or camera

- Debug Logs from Home Assistant (https://github.com/fuatakgun/eufy_security/discussions/624) - Without this, I will automatically resolve this issue
  

- Logs from Eufy Security Add-on (either from Add-ons page of Home Assistant or Docker output):
    '66b7a5a8c0aa22b5184de79b96f78172d7e31ef8d52d': {
      house_id: '66b7a5a8c0aa22b5184de79b96f78172d7e31ef8d52d',
      user_id: '66b7a5e56c383d3adb4c7d3f7ab3e909d8f8d52d',
      admin_user_id: '66b7a5e56c383d3adb4c7d3f7ab3e909d8f8d52d',
      role_type: 2,
      house_name: "kee***'s Home",
      is_default: 1,
      geofence_id: 0,
      address: '',
      latitude: 0,
      longitude: 0,
      radius_range: 0,
      location_msg: 0,
      create_time: 1733102964,
      away_mode: 0,
      home_mode: 0
    }
  }
}
2024-12-02 01:31:04.335	DEBUG	eufy-security-ws:eufy-security-client	[http] [HTTPApi.request] Api request {
  method: 'post',
  endpoint: 'v2/house/station_list',
  responseType: undefined,
  token: '5885f7dc6590f7728a133c1b897389ba635709c232f3802a',
  data: {
    device_sn: '',
    num: 1000,
    orderby: '',
    page: 0,
    station_sn: '',
    time_zone: -18000000,
    transaction: '1733103064334'
  }
}
2024-12-02 01:31:04.424	DEBUG	eufy-security-ws:eufy-security-client	[http] [HTTPApi.request] Api request - Response {
  token: '5885f7dc6590f7728a133c1b897389ba635709c232f3802a',
  request: {
    method: 'post',
    endpoint: 'v2/house/station_list',
    data: {
      device_sn: '',
      num: 1000,
      orderby: '',
      page: 0,
      station_sn: '',
      time_zone: -18000000,
      transaction: '1733103064334'
    }
  },
  response: {
    code: 0,
    msg: 'Succeed.',
    data: 'OdCHHRDhY6x95lFsSXDlezreDTc89WKXQG5gcJYkrK+WshL1s1ybItoJPKiXvAg6uxVeteFNzmUqFLtWtu3GzFrbraDVAnLTXMEZbcJJhNqS6crmYROFDqk+a3nc7HYifvdeQqws0Nnhvx3388AmHuooGiEMtG/pYezskKS3xgRcuuq646FTQYDFFRL09vKnDtv5hqLFmpklnGLq7vZQG+VsrhcYAGCNR9yZ07zZhkNFxrIyBFnfeWDFNZXpUhMGh592D4Q6yoNNqY6X+H7PiZbSi8QlOKzCgndViu4rrvYFwan+jqLLk+hq0P1OuapElwiEmO9bpQeMDRP4z32iEAAe0ppQvndpST/0ogxZRPdBH9RzpX5OZEMIYu3u3Eel7dG8xzGqyQDGBDsO6SBEQaQl7L1GFavFPMPUzv6VZjuEF5CGAv5RyZ58JEJgBmHPaQbLsLpYtA0pnTLVqsB/CbbQ7Uk4Bj6kVGHVBPx4sDHa90zIeDHR064yu4eTAHM4ZbyVAdiadNW6JvOY7aMPLbQMRnGMfebJOTccqQt/yBVwcKfqQckxjWuYuU+r6b1Mc7RQPxROSLT1XWjcGOPCh6xaApgK9IdQY/rCZcZNamzqlp1LoMbZoRb9sb5uEaD+RgU5F01A77/4f3muM3s+At6P9jieA0woHTEuohLG1tRSY66mJmt5ZT21Dk/4pNFoNmC+JXX9K4AKbmEsmSkuMDDOqJLlRMCIZVeklqcAiKkUIcmgv0nYObh8qlGppURN62xoOtivXXKHl0Yx0Hpk5/++EmEjniIS1D5ZWqUMIvau5Bm8JG1Le0K5bNv08gxEFyPp6HOdItfaT5QdzCG/SixxOo7zD2lk1oVpQognHvZ3lpa8SvRXQi96F3RTgAGpHbS3Xj95HPYpVW3v64k0jDD3nqsTqyMFNNt1eWTUe3xSMb+KTEkJVBfewxOb4PcIo8XeiwF/bM3hxUVSvFiP/V2ZMj5BlIceiTnCtuj5MN1gVvfReXoMS3p9M8+XAigFwHCj0hTCMeBgS/CWIXx97ST1XcSh9NLZ0+Od1/9BDmqueHKPu+FRPEq4DlTgTFEq91G6o6JCMSZN9oeyM6MorTpcZhnmxmpXwmusmIPug4qmnR5F/aSlBmQsm2Xfsr2rpb9Cnmvxi9cd6D8HaaXgWcfeBq5fj8ZppK2uIpeLvOQ5e/xsKqApw9NzTKqpk880sXMvP3lzshUfboB63KJoXMGC2zHOAzc+89DxJTAAkLIxSkZ+HkEa/SKJqRE0LrMiRPmgpaR0faoJtoWB1zFMjXohbgWvR3XtaGY47U9LzbL9E2Sit8caiqV4A7FeLBJPQzgTrWwbfbbWmD+cfQvMg4MeqC+BZ3aDU5+NDwPbAeJ1SI+IWHRuj+0LkMLY24VKnpIC/LexMPoApPdx027VdS3o+7giy5OTSf4P6a8SduJqrRSvKZNLHk7JRO9tM1r9c087DEXyraIeMCWWOpst2QVDkoPp0CnPmXrvtNkMzcC4QVx+eEpr+Ff2LXOt4cp+2uE8Mjpatv2F0vWS1amQSedPqL+pmvMJH9Gw7r09PZcrEutf1L2j0fNXFoGQItXzK84nWezIoKJ9cEh26XQRIH7IRF8ENqikFwwBe2h0tUPaGJ9DCzhtuLoCloLYKAMcKtqpGewanvNnthvCNqqM5TyG+UbzXwEbGBDmpFUiAa/+lzXD1WIqlO9XEYBJh3H5KEEPOff1Vx3J9pWIq4L0sDQ5K6zvaRj+SMJrhaYcp/LdPDHLJAzgx6+FklMy2EDtqKUN1mGhr2nVI9QaRxjvMJi5YFc3a25/V0fWp1iV6y0F3HrEO3FVZXcD9lYefR/ABPSJCtZkPP0L7nv/XYYYs4pdy4OoGix9pRSUkT3g31IUPx6wgFTiTAeCTGPFp7MMmQJX5krDkdRzX7L95tjs1RBnsVwnJi7yxwpzln5PCqIicEMdjznw8SSfMpwEI72h9b8D3ohP4y4An3HnTqSz8SzP7xQEsv3AYDCO/2aaIDJX5UQ13qyaJylycAHa21JCj/+gbhMJHf0YU/3UP4vEu+fMqoJ5SRb2AbG1ONYYxVAEkTKn4Q5rNFwkgGXoUhblybRbZ3Mvdw1cdb8w/0KexNhVr0Pf2py6J+4XljsIZRwOieRb6WJ/ZdUtdV5mpmiKEUFBDjPoZyBk3GH6BA4FojkMKdtYkrOKpjnsebWzGAeEBWDZyjaVBNjzOLqRaX/SCHCZ2Lban6CFCjXOYQqe7aiuqtVxTDttFRDkzgalgU7NM4YSsk4fODwbrSRYics/uD2+NFBxI1mgO4xQPKiaT7AmdGjyb5UTtQs/OQjyTt3JpzAYF282J98PYCzq1jfViRwUGEKyNxJR/7e/xLVhg62/sJreiE1P06FMfBABuFBXXm1exkoAoV5lCBtzKV5MxZ9LeIyvjEPGA07MGMOypZJhBHhozmaDvxG0DbfVCguu++2YYMvUYP1LOFex1umgP0H9D/Cm/qtLxQV9UwRP0b9B926jMXC0nqbR/BPZw4OYN9zT+L45S7DRvEU2wektDt68B8+HDBzX+GPyD2BQNfk2HRdeo+muZA2OwM5RJsv8KzlFJHdmm2vtIvYNNf3g8X6ZPDlbPBnrmGfRX37rR34qOaBPhpFhUNAc9jUhgkinB7HF/mf4CucF6BN0Y7YS3SMYHWlhoa+3VJa5civgmQ9DvOl0qMyeBQGw52LT0R1rmfzSrObSzWnbMa5CbN+ZL6rLHT2wAExIEEVfcOe0vo5RZW+pl3pypUTay/WjlFt8kwCXDmN/rBidFzrv1UfHtTgBJbOFdJzR/ki+oYjSwiXudSAa2aWn/oIQvntEVnCtZ0nKIGLqRD8hs/KoucO6nSdAwGGQPef9EoqLoxnEVvRJHXKG8oZwHUnh7ORCln7IoW7M83UE2Rr+9Bh6fy3fPJoVGUF1jHU10pk26BQE0hckx8qHCcKsQBdYkfi77KHaoAl95LgzERPYxfodfAO3p+DjKgDCPCU+9l0fgVVguHZgEWO19g+pQvKybUQsg690XrYF/rhYaG1k+QvqPGap/7WSRAHG7zcs6VAx8fHf3rjpTre6Kr2I6ZsAXktelMTqG7Rj52lXrxfJ6oMRg7JdfwG76JU7L1heny39JZSVBDd/pHe86RVgi8FHw5hW3dORltrANPEcsnRC0x8R4Y8AH91yiA0AjWbEshnGw1ZjUIUvRXSMXdn0edOHfNImf2C8ge9V//nH5gr9HzBSx1619+UecQbayRy0bXsGJGYSrCqojs2FySPSE/FRyyusgHpW5rsb9Z42tg3XJurV2iRMp6tsRwPToE7a8A2pG2/c5nEsQ3/m+2r5iyx8C0Pg68LdlChIiroJ49iRca4ObyE8PQQbRKpFl+1D3BvzHW3yThtZ7rvQ6c5S0lo1CRUWtO2onmuNqs8h8uSJMIecyXzMAMjQ2sSwYMV1RbKH4mw8r4QMI3BOjkb32ItJSWmTtjw33pfkRqr3l3K+FIAieJwcRwdHDkytCd7lEc+/qN9ipvpkcrMWnqzmIOyhVjGC8Fqmk8b9p4kpE/+TvaIN8xBaoJCjdbKtT3UgStQnDO3fZkxux5e7qQsWqpIhPiSWS4GJvPrhuN9VNBcSFs+sz93xpZVBbtEsDzCvfuq867jsu8od3vYr5eFjWYAgUiUQZVqYlqge6R7/otgGZo5RGIfKVHhxGTACJI+ItlxPG3Sp+N7pbu4t2x1s3DTZVXqJEgK3PlIrxGQ1NMtG4j+/0wNXOzZpk9pfiNzl4dDjNit6NkcSz4Jbq8oz1Ujl4TODu64JCiDN7TJ3EUNIjhb/k7Oho7WbeZ0T3sr7bfZcHjpI0dLmIPkdo41MGLqp2iYV3cEiwvQx+s62jBwxzcIuA3XC0VUpASsuog6o5Np0fOGVbIyxTBHWY5aPw8wEbJfsvdHqNWpnMSoGZfbmUKPN3WWv'
  }
}
2024-12-02 01:31:04.426	DEBUG	eufy-security-ws:eufy-security-client	[http] [HTTPApi.getStationList] Decrypted station list data [
  {
    station_id: 1130668997,
    station_sn: 'T8531K1024290ABA',
    station_name: 'Front Door',
    station_model: 'T8531',
    time_zone: 'EST5EDT,M3.2.0,M11.1.0|1.1159',
    wifi_ssid: '',
    ip_addr: '192.168.30.12',
    wifi_mac: '102CB150F1B3',
    main_sw_version: '0.1.3.9',
    main_hw_version: '0.0.0.3',
    sec_sw_version: '0.4.4.5',
    sec_hw_version: 'AT+ANKER_GET_HW_VER V2',
    ai_kernel_version: '1.1.2',
    ai_rootfs_version: '1.1.9',
    ai_algor_version: '1.1.2',
    sec_sw_time: 1733090346,
    ai_kernel_time: 1733085149,
    ai_rootfs_time: 1733085149,
    ai_algor_time: 1733085149,
    bt_mac: '102CB1A6444D',
    device_type: 189,
    event_num: 12,
    sku_number: '',
    lot_number: '',
    cpuid: '62e8d76eca856b3c',
    create_time: 1722406636,
    update_time: 1733103025,
    status: 1,
    station_status: 0,
    status_change_time: 0,
    p2p_did: 'USPRBMA-187385-VKNVV',
    push_did: 'USPRBMA-187385-VKNVV',
    p2p_license: 'XZWNJJ',
    push_license: '',
    ndt_did: 'USPRBMA-187385-VKNVV',
    ndt_license: '',
    wakeup_flag: 7,
    p2p_conn: 'EFGBFFBKKEJKGGJJEJGIFKEGHBMPHBJJCFENBNHDBDNMOPOBGNAIHMODCMLOINOGAONEPFDALPINAJDJMNJIJNFKMIOHAHCNEGCKHLBCJKLLEEDKAOBDPEJDGN',
    app_conn: 'EBGCFGBNKDIHGMIMFJHMFCFAGHMPGPMEGEEOADDDBFIAKOLICPBPCLOOHCKGJGKFBHNGLKCCPDNFAN',
    query_server_did: '',
    prefix: 'USPRAMD',
    wakeup_key: 'N2VlNTQ2OTAwNzY5',
    signaling_servers: [
      'https://webrtc-signal-us.eufylife.com',
      'https://3.140.98.24'
    ],
    member: {
      family_id: 0,
      station_sn: 'T8531K1024290ABA',
      admin_user_id: 'f6c82f38400b2e8a6a97aee07d2e3b59764ee24f',
      member_user_id: '66b7a5e56c383d3adb4c7d3f7ab3e909d8f8d52d',
      short_user_id: '0005',
      member_type: 1,
      permissions: 0,
      member_nick: '',
      action_user_id: '',
      fence_state: 0,
      extra: '',
      member_avatar: '',
      house_id: '',
      create_time: 1733102966,
      update_time: 0,
      status: 0,
      email: '',
      nick_name: '',
      avatar: '',
      action_user_email: 'ravilesh@yahoo.com',
      action_user_name: 'ravilesh'
    },
    params: [
      {
        param_id: 0,
        station_sn: 'T8531K1024290ABA',
        param_type: 1140,
        param_value: '1',
        create_time: 1733090307,
        update_time: 0,
        status: 1
      }
    ],
    devices: [
      {
        device_id: 1141292399,
        is_init_complete: true,
        device_sn: 'T8531K1024290ABA',
        device_name: 'Front Door',
        device_model: 'T8531',
        time_zone: 'EST5EDT,M3.2.0,M11.1.0|1.1159',
        device_type: 189,
        device_channel: 0,
        station_sn: 'T8531K1024290ABA',
        schedule: '',
        schedulex: '',
        wifi_mac: '102CB150F1B3',
        main_sw_version: '0.1.3.9',
        main_hw_version: '0.0.0.3',
        sec_sw_version: '0.4.4.5',
        sec_hw_version: 'AT+ANKER_GET_HW_VER V2',
        sector_id: 0,
        event_num: 0,
        wifi_ssid: 'DDMM',
        ip_addr: '192.168.30.12',
        ai_kernel_version: '1.1.2',
        ai_rootfs_version: '1.1.9',
        ai_algor_version: '1.1.2',
        sec_sw_time: 1733090346,
        ai_kernel_time: 1733085149,
        ai_rootfs_time: 1733085149,
        ai_algor_time: 1733085149,
        bind_time: 1733090341,
        bt_mac: '102CB1A6444D',
        local_ip: '',
        language: 'en',
        sku_number: '',
        lot_number: '',
        cpuid: '62e8d76eca856b3c',
        create_time: 1722406636,
        update_time: 1733103025,
        status: 1
      }
    ],
    sensor_info: null,
    is_init_complete: true,
    virtual_version: '',
    house_id: 'f6c82f6ae2481127db40cb832f99f44c7b53654ee24f'
  }
]

- Would you share your device with me in case further debugging required? (Yes/No): Yes

**Comment by asan2020** [comment]
Log from HA

This error originated from a custom integration.

Logger: homeassistant
Source: custom_components/eufy_security/eufy_security_api/web_socket_client.py:63
integration: Eufy Security (documentation, issues)
First occurred: 5:30:46 PM (12 occurrences)
Last logged: 9:00:39 PM

Error doing job: Exception in callback WebSocketClient._on_close(<Task cancell...client.py:62>>) (None)
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/config/custom_components/eufy_security/eufy_security_api/web_socket_client.py", line 81, in _on_close
    self.close_callback(future)
  File "/config/custom_components/eufy_security/eufy_security_api/api_client.py", line 317, in _on_close
    _LOGGER.debug(f"on_close - executed - {future} = {future.exception()}")
                                                      ^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/eufy_security/eufy_security_api/web_socket_client.py", line 63, in _process_messages
    async for msg in self.socket:
  File "/usr/local/lib/python3.12/site-packages/aiohttp/client_ws.py", line 384, in __anext__
    msg = await self.receive()
          ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/client_ws.py", line 315, in receive
    msg = await self._reader.read()
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/streams.py", line 685, in read
    return await super().read()
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/streams.py", line 644, in read
    await self._waiter
asyncio.exceptions.CancelledError

**Comment by BeardedPlatypus17** [comment]
Do you still have this issue? I have HomeBase and it still isn't supported.
