### ISSUE TITLE
Setup failed for custom integration

### ISSUE THREAD

**Issue by crunchynapkin404** [fuatakgun/eufy_security#1265]
Logger: homeassistant.setup
Bron: setup.py:334
Eerst voorgekomen: 21:12:15 (1 gebeurtenissen)
Laatst gelogd: 21:12:15

Setup failed for custom integration 'eufy_security': Unable to import component: Exception importing custom_components.eufy_security
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1074, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 200, in protected_loop_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.13/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 1022, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/eufy_security/__init__.py", line 13, in <module>
    from .const import COORDINATOR, DOMAIN, PLATFORMS
  File "/config/custom_components/eufy_security/const.py", line 16, in <module>
    from .model import EntityDescription
  File "/config/custom_components/eufy_security/model.py", line 19, in <module>
    class ConfigField(Enum):
    ...<14 lines>...
        mfa_input = auto()
  File "/config/custom_components/eufy_security/model.py", line 25, in ConfigField
    rtsp_server_address = auto()
    ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/enum.py", line 431, in __setitem__
    v.value = self._generate_next_value(
              ~~~~~~~~~~~~~~~~~~~~~~~~~^
            key, 1, len(self._member_names), self._last_values[:],
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
            )
            ^
  File "/usr/local/lib/python3.13/enum.py", line 1248, in _generate_next_value_
    raise TypeError('unable to sort non-numeric values') from None
TypeError: unable to sort non-numeric values

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 334, in _async_setup_component
    component = await integration.async_get_component()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1034, in async_get_component
    self._component_future.result()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1026, in async_get_component
    comp = self._get_component()
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1085, in _get_component
    raise ImportError(f"Exception importing {self.pkg_path}") from err
ImportError: Exception importing custom_components.eufy_security


Logger: homeassistant.loader
Bron: loader.py:1074
Eerst voorgekomen: 21:12:15 (2 gebeurtenissen)
Laatst gelogd: 21:12:15

Unexpected exception importing component custom_components.eufy_security
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1074, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 200, in protected_loop_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.13/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 1022, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/eufy_security/__init__.py", line 13, in <module>
    from .const import COORDINATOR, DOMAIN, PLATFORMS
  File "/config/custom_components/eufy_security/const.py", line 16, in <module>
    from .model import EntityDescription
  File "/config/custom_components/eufy_security/model.py", line 19, in <module>
    class ConfigField(Enum):
    ...<14 lines>...
        mfa_input = auto()
  File "/config/custom_components/eufy_security/model.py", line 25, in ConfigField
    rtsp_server_address = auto()
    ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/enum.py", line 431, in __setitem__
    v.value = self._generate_next_value(
              ~~~~~~~~~~~~~~~~~~~~~~~~~^
            key, 1, len(self._member_names), self._last_values[:],
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
            )
            ^
  File "/usr/local/lib/python3.13/enum.py", line 1248, in _generate_next_value_
    raise TypeError('unable to sort non-numeric values') from None
TypeError: unable to sort non-numeric values

Logger: homeassistant.util.loop
Bron: util/loop.py:77
Eerst voorgekomen: 21:12:15 (1 gebeurtenissen)
Laatst gelogd: 21:12:15

Detected blocking call to import_module with args ('custom_components.eufy_security',) in /usr/src/homeassistant/homeassistant/loader.py, line 1074: ComponentProtocol, importlib.import_module(self.pkg_path) inside the event loop; This is causing stability issues. Please create a bug report at https://github.com/home-assistant/core/issues?q=is%3Aopen+is%3Aissue For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#import_module Traceback (most recent call last): File "<frozen runpy>", line 198, in _run_module_as_main File "<frozen runpy>", line 88, in _run_code File "/usr/src/homeassistant/homeassistant/__main__.py", line 227, in <module> sys.exit(main()) File "/usr/src/homeassistant/homeassistant/__main__.py", line 213, in main exit_code = runner.run(runtime_conf) File "/usr/src/homeassistant/homeassistant/runner.py", line 154, in run return loop.run_until_complete(setup_and_run_hass(runtime_config)) File "/usr/local/lib/python3.13/asyncio/base_events.py", line 708, in run_until_complete self.run_forever() File "/usr/local/lib/python3.13/asyncio/base_events.py", line 679, in run_forever self._run_once() File "/usr/local/lib/python3.13/asyncio/base_events.py", line 2027, in _run_once handle._run() File "/usr/local/lib/python3.13/asyncio/events.py", line 89, in _run self._context.run(self._callback, *self._args) File "/usr/src/homeassistant/homeassistant/setup.py", line 165, in async_setup_component result = await _async_setup_component(hass, domain, config) File "/usr/src/homeassistant/homeassistant/setup.py", line 334, in _async_setup_component component = await integration.async_get_component() File "/usr/src/homeassistant/homeassistant/loader.py", line 1026, in async_get_component comp = self._get_component() File "/usr/src/homeassistant/homeassistant/loader.py", line 1074, in _get_component ComponentProtocol, importlib.import_module(self.pkg_path)

**Comment by CrallH** [comment]
Same for me with 2024.12.0

**Comment by s-kaz2285** [comment]
Same for me after update.

**Comment by deadphyre** [comment]
Same here after update.

**Comment by Dutchy-79** [comment]
Same

**Comment by pcuser42** [comment]
#1261 appears to be the fix for this, I'm just waiting for it to be merged and released

**Comment by adultano** [comment]
Same here - rolled back to 11.3

**Comment by prle77** [comment]
Same issue here.. failed after update to 12.0

**Comment by CrallH** [comment]
> #1261 appears to be the fix for this, I'm just waiting for it to be merged and released

I edited my files like this and are up and running again 👍

**Comment by Dutchy-79** [comment]
> #1261 appears to be the fix for this, I'm just waiting for it to be merged and released

Can you explain what I should edit for quick and dirty fix while waiting for the update?

**Comment by Asgorath777** [comment]
> > #1261 appears to be the fix for this, I'm just waiting for it to be merged and released
> 
> Can you explain what I should edit for quick and dirty fix while waiting for the update?

You can follow the diff compare here: https://github.com/fuatakgun/eufy_security/pull/1261/files 

Basically replace the 'red lines' with the 'green lines' (which is just changing the auto() to a number). Both file names are in that link and the exact line numbers.

**Comment by fuatakgun** [comment]
merged, a new version released, please get it
