### ISSUE TITLE
Issue: unable to sort non-numeric values

### ISSUE THREAD

**Issue by magarto** [fuatakgun/eufy_security#1276]
**Describe the bug**

After updating to Home Assistant Core (docker) 2024.12.5, eufy security integration (docker) stopped working, but eufy security (docker) works

**To reproduce**

The only thing I did was updating HA to 2024.12.5. After downgrading 2024.12.0 it happens also. Downgrading to 2024.11.3 fixes it.

**Expected behavior**

**Additional information**

- Home Assistant Installation Type (OS - Supvervised - Core): Core 
- Home Assistant Core Version: 2024.12.5
- Eufy Security Add-on Version: 8.1.1
- Eufy Security Integration Version: 7.7.4
- Using go2rtc Add-on or webrtc custom integration with integrated go2rtc: Disabled

Hardware Information;
- Camera Model: T8134

- Live Streaming Protocol (RTSP/P2P): P2P

- Debug Logs from Home Assistant (https://github.com/fuatakgun/eufy_security/discussions/624) - Without this, I will automatically resolve this issue
  
Error 1:

Registrador: homeassistant.loader
Fuente: loader.py:1074
Ocurrió por primera vez: 22:20:57 (2 ocurrencias)
Última vez registrado: 22:20:57

Unexpected exception importing component custom_components.eufy_security
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1074, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 200, in protected_loop_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.13/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 1022, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/eufy_security/__init__.py", line 11, in <module>
    from .const import COORDINATOR, DOMAIN, PLATFORMS
  File "/config/custom_components/eufy_security/const.py", line 16, in <module>
    from .model import EntityDescription
  File "/config/custom_components/eufy_security/model.py", line 20, in <module>
    class ConfigField(Enum):
    ...<17 lines>...
        mfa_input = auto()
  File "/config/custom_components/eufy_security/model.py", line 26, in ConfigField
    rtsp_server_address = auto()
    ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/enum.py", line 431, in __setitem__
    v.value = self._generate_next_value(
              ~~~~~~~~~~~~~~~~~~~~~~~~~^
            key, 1, len(self._member_names), self._last_values[:],
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
            )
            ^
  File "/usr/local/lib/python3.13/enum.py", line 1248, in _generate_next_value_
    raise TypeError('unable to sort non-numeric values') from None
TypeError: unable to sort non-numeric values


Error 2:

Registrador: homeassistant.setup
Fuente: setup.py:334
Ocurrió por primera vez: 22:20:57 (1 ocurrencias)
Última vez registrado: 22:20:57

Setup failed for custom integration 'eufy_security': Unable to import component: Exception importing custom_components.eufy_security
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1074, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 200, in protected_loop_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.13/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 1022, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/eufy_security/__init__.py", line 11, in <module>
    from .const import COORDINATOR, DOMAIN, PLATFORMS
  File "/config/custom_components/eufy_security/const.py", line 16, in <module>
    from .model import EntityDescription
  File "/config/custom_components/eufy_security/model.py", line 20, in <module>
    class ConfigField(Enum):
    ...<17 lines>...
        mfa_input = auto()
  File "/config/custom_components/eufy_security/model.py", line 26, in ConfigField
    rtsp_server_address = auto()
    ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/enum.py", line 431, in __setitem__
    v.value = self._generate_next_value(
              ~~~~~~~~~~~~~~~~~~~~~~~~~^
            key, 1, len(self._member_names), self._last_values[:],
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
            )
            ^
  File "/usr/local/lib/python3.13/enum.py", line 1248, in _generate_next_value_
    raise TypeError('unable to sort non-numeric values') from None
TypeError: unable to sort non-numeric values

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 334, in _async_setup_component
    component = await integration.async_get_component()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1034, in async_get_component
    self._component_future.result()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1026, in async_get_component
    comp = self._get_component()
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1085, in _get_component
    raise ImportError(f"Exception importing {self.pkg_path}") from err
ImportError: Exception importing custom_components.eufy_security


- Logs from Eufy Security Add-on (either from Add-ons page of Home Assistant or Docker output):
No errors

- Would you share your device with me in case further debugging required? (Yes/No):
Yes

**Additional context**

No

**Comment by fuatakgun** [comment]
Update eufy_security integration to the latest version

**Comment by magarto** [comment]
Sorry, it fixed it
