### ISSUE TITLE
PictureURL error, Eufy 2k indoor snapshots not showing

### ISSUE THREAD

**Issue by jbrukardt** [fuatakgun/eufy_security#14]
Title says it all.    Snapshots are not showing for any indoor 2k camera that doesnt have an SD card in it.   Log file excerpt below

`Logger: aiohttp.server
Source: custom_components/eufy_security/camera.py:263
Integration: Eufy Security
First occurred: 3:56:03 PM (324 occurrences)
Last logged: 4:05:48 PM

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 422, in _handle_request
    resp = await self._request_handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_app.py", line 499, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_middlewares.py", line 119, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 197, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 24, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 78, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 144, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 135, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/camera/__init__.py", line 511, in get
    return await self.handle(request, camera)
  File "/usr/src/homeassistant/homeassistant/components/camera/__init__.py", line 528, in handle
    image = await camera.async_camera_image()
  File "/usr/src/homeassistant/homeassistant/components/camera/__init__.py", line 390, in async_camera_image
    return await self.hass.async_add_executor_job(self.camera_image)
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/eufy_security/camera.py", line 263, in camera_image
    if self.camera_picture_url != self.entity["pictureUrl"]:
KeyError: 'pictureUrl'
`

**Comment by fuatakgun** [comment]
have you enabled picture generation for motion notification in your eufy app?

**Comment by jbrukardt** [comment]
Yes.  In the actual app notifications pictures show, and they were retrievable in the old iobroker implementation that to the best of knowledge followed the same methodology from bropat

Screenshot of setting :  https://i.imgur.com/z0gpSug.png

**Comment by fuatakgun** [comment]
Can you try to install with latest changes?

**Comment by jbrukardt** [comment]
Latest change fixed it!   Zoomed in motion detected snapshots now showing up.
