### ISSUE TITLE
Floodlight Camera not working

### ISSUE THREAD

**Issue by air720boarder** [fuatakgun/eufy_security#18]
Getting an authentication error on Floodlight cams only:

2021-07-23 16:18:05 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 422, in _handle_request
resp = await self._request_handler(request)
File "/usr/local/lib/python3.9/site-packages/aiohttp/web_app.py", line 499, in _handle
resp = await handler(request)
File "/usr/local/lib/python3.9/site-packages/aiohttp/web_middlewares.py", line 119, in impl
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 77, in forwarded_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 24, in request_context_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 78, in ban_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 144, in auth_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 135, in handle
result = await result
File "/usr/src/homeassistant/homeassistant/components/camera/__init__.py", line 507, in get
if not camera.is_on:
File "/config/custom_components/eufy_security/camera.py", line 335, in is_on
return self.entity["enabled"]
KeyError: 'enabled'
2021-07-23 16:18:07 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140224870635312] Error handling message: Unknown error
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 25, in _handle_async_response
await func(hass, connection, msg)
File "/usr/src/homeassistant/homeassistant/components/camera/__init__.py", line 604, in ws_camera_stream
camera = _get_camera_from_entity_id(hass, entity_id)
File "/usr/src/homeassistant/homeassistant/components/camera/__init__.py", line 230, in _get_camera_from_entity_id
if not camera.is_on:
File "/config/custom_components/eufy_security/camera.py", line 335, in is_on
return self.entity["enabled"]
KeyError: 'enabled'
2021-07-23 16:18:07 WARNING (MainThread) [homeassistant.components.http.ban] Login attempt or request with invalid authentication from 192.168.1.12 (192.168.1.12). (Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.1.2 Safari/605.1.15)

**Comment by fuatakgun** [comment]
This line is creating an issue, i will fix it soon (on vacation for next 3 days, not that soon :-))

`self.entity["enabled"]` should be replaced with just `True`

**Comment by dpomnean** [comment]
If this is all you need @fuatakgun 
#19

**Comment by fuatakgun** [comment]
Merged

**Comment by fuatakgun** [comment]
We should be good here, resolving.
