### ISSUE TITLE
Error doing job: Task exception was never retrieved

### ISSUE THREAD

**Issue by FeromonDE** [fuatakgun/eufy_security#191]
Please check Services, Known Bug / Issues and Troubleshooting over here first: https://github.com/fuatakgun/eufy_security/blob/master/README.md

**Describe the bug**
```
2021-12-29 17:38:52 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/eufy_security/__init__.py", line 59, in update
    coordinator.async_set_updated_data(coordinator.data)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 287, in async_set_updated_data
    update_callback()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 325, in _handle_coordinator_update
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 505, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 538, in _async_write_ha_state
    state = self._stringify_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 511, in _stringify_state
    if (state := self.state) is None:
  File "/usr/src/homeassistant/homeassistant/components/select/__init__.py", line 93, in state
    if self.current_option is None or self.current_option not in self.options:
  File "/config/custom_components/eufy_security/select.py", line 65, in current_option
    return self.values_to_states[str(get_child_value(self.device.state, self.key))]
KeyError: '1'
```

**To Reproduce**

**Expected behavior**

**Screenshots**

**Hardware Information about Home Assistant

**Hardware Information about Cameras
- 2C Pro
- Eufy Doorbell
- Live Streaming Protocol: RTSP or P2p

**Additional context**

**Comment by fuatakgun** [comment]
Please enable debug logs and share the respective logs from home assistant

**Comment by kprestel** [comment]
Seeing the same issues and turnning on debug only gives one more line:

2022-01-02 11:07:40 DEBUG (MainThread) [custom_components.eufy_security] Manually updated eufy_security data
2022-01-02 11:07:40 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/eufy_security/__init__.py", line 59, in update
    coordinator.async_set_updated_data(coordinator.data)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 287, in async_set_updated_data
    update_callback()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 325, in _handle_coordinator_update
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 505, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 538, in _async_write_ha_state
    state = self._stringify_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 511, in _stringify_state
    if (state := self.state) is None:
  File "/usr/src/homeassistant/homeassistant/components/select/__init__.py", line 93, in state
    if self.current_option is None or self.current_option not in self.options:
  File "/config/custom_components/eufy_security/select.py", line 65, in current_option
    return self.values_to_states[str(get_child_value(self.device.state, self.key))]
KeyError: '1'

**Comment by fuatakgun** [comment]
i need to place more useful debug logs to find out the root cause of this, please stay tight

**Comment by fuatakgun** [comment]
Can you please share your devices with me so i can debug? Follow readme you will find insurance there.

**Comment by charlyr82** [comment]
I also have this issue, my logs are getting absolutely flooded with the error message from the OP. My eufy user for home assistant has 4x Eufy 2C Pro cameras, 1x Eufy 2K Wireless Doorbell, and 1x Eufy Wireless Doorbell (1080p) shared with it. I don't have a "Video Recording Quality" configuration entity (input_select) for the doorbells, but it also doesn't appear as an option in the eufy app on my phone, all of my Eufy 2C Pro cameras do have a "Video Recording Quality" configuration entity on the device page within home assistant (although it is greyed out).

I added some extra debug logging lines in to the select.py file within current_option method (at line 64):

def current_option(self) -> str:
        _LOGGER.debug(f"STATE:  {self.device.state}")
       _LOGGER.debug(f"KEY:  {self.key}")
        _LOGGER.debug(f"CHILDVALUE: {str(get_child_value(self.device.state, self.key))}")
        _LOGGER.debug(f"STATES: {get_child_value(self.device.properties_metadata, self.key)}")
        _LOGGER.debug(f"VALUESTOSTATES: {self.values_to_states}")
        _LOGGER.debug(f"VALUEtoSTATE: {self.values_to_states[str(get_child_value(self.device.state, self.key))]}")
        return self.values_to_states[str(get_child_value(self.device.state, self.key))]

Using this information, it looks like most of the select entities work perfectly, but for the key "videoRecordingQuality"
I get an error every time...

2022-01-12 23:15:04 DEBUG (MainThread) [custom_components.eufy_security] STATE: {'name': 'Back Garden', 'model': 'T8142-Z', 'serialNumber': 'REDACTED', 'hardwareVersion': 'T8142-Z', 'softwareVersion': '5.4.5', 'stationSerialNumber': 'REDACTED', 'enabled': True, 'state': 1, 'battery': 97, 'batteryTemperature': 4, 'lastChargingDays': 9, 'lastChargingTotalEvents': 80, 'lastChargingRecordedEvents': 27, 'lastChargingFalseEvents': 53, 'batteryUsageLastWeek': 0, 'motionDetected': False, 'personDetected': False, 'personName': '', 'antitheftDetection': False, 'motionDetection': True, 'rtspStream': False, 'watermark': 1, 'wifiRSSI': -60, 'pictureUrl': 'REDACTED', 'type': 15, 'motionDetectionType': 0, 'light': False, 'microphone': True, 'speaker': True, 'speakerVolume': 93, 'audioRecording': True, 'powerSource': 0, 'powerWorkingMode': 0, 'recordingEndClipMotionStops': True, 'recordingClipLength': 60, 'recordingRetriggerInterval': 5, 'videoStreamingQuality': 0, 'videoRecordingQuality': 1, 'lightSettingsBrightnessManual': 100, 'notificationType': 1, 'motionDetectionSensitivity': 5, 'statusLed': False, 'rtspStreamUrl': '', 'chargingStatus': 2, 'wifiSignalLevel': 4, 'nightvision': 1, 'p2pLiveStreamingStatus': False, 'rtspLiveStreamingStatus': False}
2022-01-12 23:15:04 DEBUG (MainThread) [custom_components.eufy_security] KEY: videoRecordingQuality
2022-01-12 23:15:04 DEBUG (MainThread) [custom_components.eufy_security] CHILDVALUE: 1
2022-01-12 23:15:04 DEBUG (MainThread) [custom_components.eufy_security] STATES: {'key': 1286, 'name': 'videoRecordingQuality', 'label': 'Video Recording Quality', 'readable': True, 'writeable': True, 'type': 'number', 'states': {'2': 'Full HD (1080P)', '3': '2K HD'}, 'commandId': 1023}
2022-01-12 23:15:04 DEBUG (MainThread) [custom_components.eufy_security] VALUESTOSTATES: {'2': 'Full HD (1080P)', '3': '2K HD'}
2022-01-12 23:15:05 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
File "/config/custom_components/eufy_security/__init__.py", line 59, in update
coordinator.async_set_updated_data(coordinator.data)
File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 287, in async_set_updated_data
update_callback()
File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 325, in _handle_coordinator_update
self.async_write_ha_state()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 505, in async_write_ha_state
self._async_write_ha_state()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 538, in _async_write_ha_state
state = self._stringify_state()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 511, in _stringify_state
if (state := self.state) is None:
File "/usr/src/homeassistant/homeassistant/components/select/__init__.py", line 93, in state
if self.current_option is None or self.current_option not in self.options:
File "/config/custom_components/eufy_security/select.py", line 70, in current_option
_LOGGER.debug(f"VALUEtoSTATE: {self.values_to_states[str(get_child_value(self.device.state, self.key))]}")
KeyError: '1'

The values_to_states method doesn't produce a log entry, as this seems to be where the problem occurs, the current device value of 1 doesn't appear in the states list for converting the value to a state.

**Comment by charlyr82** [comment]
Thanks for your assistance with this, using the latest version (1.2.2) when home assistant is up and running I get the following messages in the log once per second:

2022-01-14 08:39:12 DEBUG (MainThread) [custom_components.eufy_security] Manually updated eufy_security data
2022-01-14 08:39:12 ERROR (MainThread) [custom_components.eufy_security] eufy_security - Back Garden - eufy_security_REDACTED_BACKGARDEN_SERIALNO_video_recording_quality_select - missing value - value: 1 - values_to_states: {'2': 'Full HD (1080P)', '3': '2K HD'} - states_to_values: {'Full HD (1080P)': '2', '2K HD': '3'} - 
2022-01-14 08:39:12 ERROR (MainThread) [custom_components.eufy_security] eufy_security - Shed - eufy_security_REDACTED_SHED_SERIALNO_video_recording_quality_select - missing value - value: 1 - values_to_states: {'2': 'Full HD (1080P)', '3': '2K HD'} - states_to_values: {'Full HD (1080P)': '2', '2K HD': '3'} - 
2022-01-14 08:39:12 ERROR (MainThread) [custom_components.eufy_security] eufy_security - Front - eufy_security_REDACTED_FRONT_SERIALNO_video_recording_quality_select - missing value - value: 1 - values_to_states: {'2': 'Full HD (1080P)', '3': '2K HD'} - states_to_values: {'Full HD (1080P)': '2', '2K HD': '3'} - 
2022-01-14 08:39:12 ERROR (MainThread) [custom_components.eufy_security] eufy_security - Side Path - eufy_security_REDACTED_SIDEPATH_SERIALNO_video_recording_quality_select - missing value - value: 1 - values_to_states: {'2': 'Full HD (1080P)', '3': '2K HD'} - states_to_values: {'Full HD (1080P)': '2', '2K HD': '3'} - 

All of the cameras referenced in the errors above are Eufy 2C Pro. The "Back Garden", "Shed" and "Side Path" cameras are all set to record in 2K HD. The "Front" camera has RTSP enabled and so is recording in 1080p (seems to be a limitation of enabling RTSP). The eufy security app on my phone shows all of these recording qualities as expected.

Attached is a sanitized log file, Serial Numbers and PictureURLs have been redacted.

[eufy-security-debug-sanitized.log](https://github.com/fuatakgun/eufy_security/files/7869527/eufy-security-debug-sanitized.log)
.

**Comment by fuatakgun** [comment]
thanks for detailed logs, as you can see, video_recording_quality was received as `1` but there are no option as `1`. Possible options are `2` and `3`, this should go to eufy_security_ws repository, can you create an issue there?

In the meantime, I prefer to skip creating of these SELECT entities if value is missing, makes sense?

**Comment by charlyr82** [comment]
Skipping the SELECT entity creation if it doesn’t exist sounds like a good solution to me, my home assistant instance has been running for about 3 hours since I generated the initial debug log with debug logging off, and has generated 40,500 of the error messages in my post above. This is absolutely flooding my logs and making it very hard to find any other messages that may be coming up.

Thanks for your assistance with this, I will raise this issue over in the eufy_security_ws repository.

**Comment by fuatakgun** [comment]
Fix is coming, stay tight

**Comment by fuatakgun** [comment]
please get latest version, this should be fixed

**Comment by fuatakgun** [comment]
comment back if needed, resolving then
