### ISSUE TITLE
Unable to start the Eufy Security Add-on

### ISSUE THREAD

**Issue by highlandtran** [fuatakgun/eufy_security#219]
Hi
After installing the Eufy Security Add-on and input Configuration with Username, password and Country code (AU), I unable to start the Addon, no log or any more information 

Any idea?

**Comment by alnsiuenrasd** [comment]
I too am having the same issue. I have uninstalled, reinstalled, rebooted, etc. I have also tried multiple email addresses along with multiple different passwords per account.
Hardware: Pi4b+
OS: Home Assistant OS 7.1


```2022-01-19 17:00:48.597  INFO  Eufy Security server listening on port 3000<br/>
2022-01-19 17:00:50.317  ERROR Station T8500Q1020400227 - Response code not ok 
{
  code: 20028,
  msg: 'Failed to request.'
}
node:internal/errors:464
    ErrorCaptureStackTrace(err);
    ^
TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received undefined
    at new NodeError (node:internal/errors:371:5)
    at Function.from (node:buffer:322:9)
    at stringWithLength (/usr/src/app/node_modules/eufy-security-client/build/p2p/utils.js:23:35)
    at p2pDidToBuffer (/usr/src/app/node_modules/eufy-security-client/build/p2p/utils.js:32:18)
    at buildLookupWithKeyPayload (/usr/src/app/node_modules/eufy-security-client/build/p2p/utils.js:36:26)
    at P2PClientProtocol.lookupByAddress (/usr/src/app/node_modules/eufy-security-client/build/p2p/session.js:233:63)
    at /usr/src/app/node_modules/eufy-security-client/build/p2p/session.js:217:51
    at Array.map (<anonymous>)
    at P2PClientProtocol.lookup (/usr/src/app/node_modules/eufy-security-client/build/p2p/session.js:217:29)
    at Socket.<anonymous> (/usr/src/app/node_modules/eufy-security-client/build/p2p/session.js:296:26) {
  code: 'ERR_INVALID_ARG_TYPE'
}```

Here is my configuration yaml:
```USERNAME: <email>
PASSWORD: <password>
COUNTRY: US
EVENT_DURATION_SECONDS: 10```

**Comment by alnsiuenrasd** [comment]
When you Start the add-on from the Info tab and then switch to the Log tab you see no logs? What if you hit refresh?

> Hi After installing the Eufy Security Add-on and input Configuration with Username, password and Country code (AU), I unable to start the Addon, no log or any more information
> 
> Any idea?

**Comment by fuatakgun** [comment]
> When you Start the add-on from the Info tab and then switch to the Log tab you see no logs? What if you hit refresh?
> 
> > Hi After installing the Eufy Security Add-on and input Configuration with Username, password and Country code (AU), I unable to start the Addon, no log or any more information
> > 
> > Any idea?
> 
> 

Valid point, if nothing comes up, this looks a system specific issue, you can also check supervisor logs.
