### ISSUE TITLE
Getting host/port is wrong on configuring eufy web socket instance

### ISSUE THREAD

**Issue by yeazj** [fuatakgun/eufy_security#260]
Installed Eufy through HACS
While setting up integration, getting host/port is wrong error on configuring eufy web socket instance with options 'localhost' and '3000'

**Comment by yeazj** [comment]
This is the log 

2022-02-08 13:31:10 ERROR (MainThread) [custom_components.eufy_security.config_flow] eufy_security Exception in login : Cannot connect to host 0.0.0.0:3000 ssl:default [Connect call failed ('0.0.0.0', 3000)] - traceback: Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 986, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1056, in create_connection
    raise exceptions[0]
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1041, in create_connection
    sock = await self._connect_sock(
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 955, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/local/lib/python3.9/asyncio/selector_events.py", line 502, in sock_connect
    return await fut
  File "/usr/local/lib/python3.9/asyncio/selector_events.py", line 537, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 111] Connect call failed ('0.0.0.0', 3000)
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/config/custom_components/eufy_security/config_flow.py", line 191, in _test_credentials
    await eufy_ws.connect()
  File "/config/custom_components/eufy_security/websocket.py", line 40, in connect
    self.ws: aiohttp.ClientWebSocketResponse = await self.session.ws_connect(
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client.py", line 776, in _ws_connect
    resp = await self.request(
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client.py", line 535, in _request
    conn = await self._connector.connect(
  File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 542, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 907, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 1175, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
  File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 992, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host 0.0.0.0:3000 ssl:default [Connect call failed ('0.0.0.0', 3000)]

**Comment by fuatakgun** [comment]
can you share the logs of add-on?

**Comment by Ankonian1** [comment]
I am also having this issue. My add-on logs are below. Dont worry about T81. Thats a solo cam. Also, for context, I do have z-wave JS installed. So I am setting the eufy add-on to port 3001. 

2022-02-08 23:18:47.528  INFO  Eufy Security server listening on host 0.0.0.0, port 3000 
2022-02-08 23:18:49.236  INFO  Connected to station T8010P1321290ABC on host 192.168.50.149 and port 29706 
2022-02-08 23:18:49.663  INFO  Push notification connection successfully established 
2022-02-08 23:18:49.783  INFO  Connected to station T8123P1021350A81 on host 192.168.50.71 and port 22159 
2022-02-08 23:18:56.327  ERROR Status return code not 200 
{
  status: 423,
  statusText: 'Locked'
}
2022-02-08 23:18:56.332  INFO  No stations found. 
2022-02-08 23:19:04.838  INFO  Initiated closing of connection to station T8123P1021350A81 for saving battery. 
2022-02-08 23:19:04.840  INFO  Disconnected from station T8123P1021350A81 

Here is my HA log for the integration:
2022-02-08 18:15:41 WARNING (MainThread) [homeassistant.config_entries] Config entry 'localhost' for eufy_security integration not ready yet: Exception: Host/port is not reachable localhost 3000!; Retrying in background

**Comment by yeazj** [comment]
> can you share the logs of add-on?

Where can I find it? I checked supervisor log and there's nothing..

**Comment by guneezx** [comment]
I think I'm having similar issue. One day, all cameras in HA has gone.
I deleted HACS integration and ws addon and re-installed them.

My addon logs are as follows:
2022-02-11 23:08:41.863  INFO  Eufy Security server listening on host 0.0.0.0, port 3000 
2022-02-11 23:08:48.846  INFO  Push notification connection successfully established 
2022-02-11 23:08:49.056  INFO  No stations found. 
2022-02-11 23:08:50.212  INFO  No devices found.

**Comment by fuatakgun** [comment]
You should check here: https://github.com/bropat/eufy-security-ws/issues/74

**Comment by fuatakgun** [comment]
Please get latest version of addon and try again

**Comment by yeazj** [comment]
> Please get latest version of addon and try again

I tried with the latest version and i'm still getting the same issue.. there's nothing in supervisor log..

**Comment by Ankonian1** [comment]
Tried with the latest version. Re-installed everything. Working now.

**Comment by yeazj** [comment]
Issue is not resolved yet.. still showing host/port is wrong error when configuration starts
