### ISSUE TITLE
Multiple Errors - HA - RPi 3B+

### ISSUE THREAD

**Issue by tempus2016** [fuatakgun/eufy_security#267]
RPi 3B+. Installed a Eufy 2k Wireless Doorbell last night and getting this error

```
This error originated from a custom integration.

Logger: homeassistant
Source: custom_components/eufy_security/alarm_control_panel.py:236
Integration: Eufy Security (documentation, issues)
First occurred: 07:48:32 (321 occurrences)
Last logged: 07:54:56

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/eufy_security/__init__.py", line 60, in update
    coordinator.async_set_updated_data(coordinator.data)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 287, in async_set_updated_data
    update_callback()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 325, in _handle_coordinator_update
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 536, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 569, in _async_write_ha_state
    state = self._stringify_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 542, in _stringify_state
    if (state := self.state) is None:
  File "/config/custom_components/eufy_security/alarm_control_panel.py", line 236, in state
    return CODES_TO_STATES[current_mode]
KeyError: -1
```

I have tried the custom card to show the last image captured which works great, but when I click on the image, the video doesn't stream and shows the following:
<img width="586" alt="Screenshot 2022-02-10 at 07 58 54" src="https://user-images.githubusercontent.com/40920327/153362911-5c3f2431-e590-4813-91b3-1c189ef00ce9.png">

Other errors include:

```
This error originated from a custom integration.

Logger: custom_components.eufy_security
Source: custom_components/eufy_security/camera.py:221
Integration: Eufy Security (documentation, issues)
First occurred: 07:58:37 (4 occurrences)
Last logged: 07:58:37

eufy_security Front Door - video ffmpeg error - ffmpeg is not running
```

```
This error originated from a custom integration.

Logger: custom_components.eufy_security
Source: custom_components/eufy_security/camera.py:211
Integration: Eufy Security (documentation, issues)
First occurred: 07:58:37 (1 occurrences)
Last logged: 07:58:37

eufy_security Front Door video_thread exception: [Errno 32] Broken pipe- traceback: Traceback (most recent call last): File "/config/custom_components/eufy_security/camera.py", line 209, in write_bytes_to_ffmeg self.ffmpeg.process.stdin.write(frame_bytes) BrokenPipeError: [Errno 32] Broken pipe
```

```
This error originated from a custom integration.

Logger: custom_components.eufy_security
Source: custom_components/eufy_security/camera.py:256
Integration: Eufy Security (documentation, issues)
First occurred: 07:58:30 (1 occurrences)
Last logged: 07:58:30

eufy_security Front Door - stop_ffmpeg exception: 'NoneType' object has no attribute 'kill' - traceback: Traceback (most recent call last): File "/config/custom_components/eufy_security/camera.py", line 254, in stop_ffmpeg self.ffmpeg.kill() File "/usr/local/lib/python3.9/site-packages/haffmpeg/core.py", line 170, in kill self._proc.kill() AttributeError: 'NoneType' object has no attribute 'kill'
```

```
Logger: homeassistant.components.alarm_control_panel
Source: custom_components/eufy_security/alarm_control_panel.py:236
Integration: Alarm Control Panel (documentation, issues)
First occurred: 07:48:27 (2 occurrences)
Last logged: 07:48:27

Error adding entities for domain alarm_control_panel with platform eufy_security
Error while setting up eufy_security platform for alarm_control_panel
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 382, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 614, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 779, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 536, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 569, in _async_write_ha_state
    state = self._stringify_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 542, in _stringify_state
    if (state := self.state) is None:
  File "/config/custom_components/eufy_security/alarm_control_panel.py", line 236, in state
    return CODES_TO_STATES[current_mode]
KeyError: -1
```

**Comment by tempus2016** [comment]
New errors all the time now.
```
Logger: homeassistant.config_entries
Source: helpers/entity_component.py:157
First occurred: 08:57:32 (7 occurrences)
Last logged: 08:57:32

Error setting up entry Eufy for sensor
Error setting up entry Eufy for alarm_control_panel
Error setting up entry Eufy for lock
Error setting up entry Eufy for switch
Error setting up entry Eufy for select
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 327, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/usr/src/homeassistant/homeassistant/components/camera/__init__.py", line 420, in async_setup_entry
    return await component.async_setup_entry(entry)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 157, in async_setup_entry
    raise ValueError("Config entry has already been setup!")
ValueError: Config entry has already been setup!
```

If the below is regarding docker, I dont use it.
```
Logger: homeassistant.components.hassio
Source: components/hassio/websocket_api.py:120
Integration: Home Assistant Supervisor (documentation, issues)
First occurred: 08:46:12 (4 occurrences)
Last logged: 08:50:09

Failed to to call /addons/3a26b21d_eufy_security_addon/stats - Container addon_3a26b21d_eufy_security_addon is not running
```

**Comment by tempus2016** [comment]
Looks like my issues were caused by setting the "Security" to 'Geofence'. Changing it back to 'Home' made it work again.  Not sure what the problem is. Would be good to have Geofencing work.

**Comment by fuatakgun** [comment]
Please get latest version of addon and try again

**Comment by novisys** [comment]
Have the same errors on log...

**Comment by fuatakgun** [comment]
is it still valid?
