### ISSUE TITLE
-1 State for Alarm Control Panel

### ISSUE THREAD

**Issue by Saible** [fuatakgun/eufy_security#292]
**Describe the bug**
The integration is properly configured and works perfectly, however it keeps filling the log with the following:

This error originated from a custom integration.

Logger: homeassistant
Source: custom_components/eufy_security/alarm_control_panel.py:236 
Integration: Eufy Security (documentation, issues) 
First occurred: 12:20:55 (1 occurrences) 
Last logged: 12:20:55

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/eufy_security/__init__.py", line 60, in update
    coordinator.async_set_updated_data(coordinator.data)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 287, in async_set_updated_data
    update_callback()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 325, in _handle_coordinator_update
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 539, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 572, in _async_write_ha_state
    state = self._stringify_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 545, in _stringify_state
    if (state := self.state) is None:
  File "/config/custom_components/eufy_security/alarm_control_panel.py", line 236, in state
    return CODES_TO_STATES[current_mode]
KeyError: -1

**Comment by fuatakgun** [comment]
this should be raised once for every reload and it is expected to raise the error. We are getting a wrong input from `eufy-security-ws` library as a state of home-base or camera station and there is no mapping for `-1`, as it is not expected :)

**Comment by fuatakgun** [comment]
In short, error is expected and should be resolved in `eufy-security-ws`, please work with repository owner.

**Comment by fuatakgun** [comment]
I believe this should have been resolved by now, please reopen if needed.
