### ISSUE TITLE
Log flooding due exception

### ISSUE THREAD

**Issue by dMopp** [fuatakgun/eufy_security#296]
My log gets flooded by

```
Mar 10 14:45:17 ulli d3edf43e34b8[638]: #033[31m2022-03-10 14:45:17 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Mar 10 14:45:17 ulli d3edf43e34b8[638]: Traceback (most recent call last):
Mar 10 14:45:17 ulli d3edf43e34b8[638]:   File "/config/custom_components/eufy_security/__init__.py", line 60, in update
Mar 10 14:45:17 ulli d3edf43e34b8[638]:     coordinator.async_set_updated_data(coordinator.data)
Mar 10 14:45:17 ulli d3edf43e34b8[638]:   File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 287, in async_set_updated_data
Mar 10 14:45:17 ulli d3edf43e34b8[638]:     update_callback()
Mar 10 14:45:17 ulli d3edf43e34b8[638]:   File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 325, in _handle_coordinator_update
Mar 10 14:45:17 ulli d3edf43e34b8[638]:     self.async_write_ha_state()
Mar 10 14:45:17 ulli d3edf43e34b8[638]:   File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 539, in async_write_ha_state
Mar 10 14:45:17 ulli d3edf43e34b8[638]:     self._async_write_ha_state()
Mar 10 14:45:17 ulli d3edf43e34b8[638]:   File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 572, in _async_write_ha_state
Mar 10 14:45:17 ulli d3edf43e34b8[638]:     state = self._stringify_state()
Mar 10 14:45:17 ulli d3edf43e34b8[638]:   File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 545, in _stringify_state
Mar 10 14:45:17 ulli d3edf43e34b8[638]:     if (state := self.state) is None:
Mar 10 14:45:17 ulli d3edf43e34b8[638]:   File "/config/custom_components/eufy_security/alarm_control_panel.py", line 236, in state
Mar 10 14:45:17 ulli d3edf43e34b8[638]:     return CODES_TO_STATES[current_mode]
Mar 10 14:45:17 ulli d3edf43e34b8[638]: KeyError: -1#033[0m
Mar 10 14:45:18 ulli d3edf43e34b8[638]: #033[31m2022-03-10 14:45:18 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Mar 10 14:45:18 ulli d3edf43e34b8[638]: Traceback (most recent call last):
Mar 10 14:45:18 ulli d3edf43e34b8[638]:   File "/config/custom_components/eufy_security/__init__.py", line 60, in update
Mar 10 14:45:18 ulli d3edf43e34b8[638]:     coordinator.async_set_updated_data(coordinator.data)
Mar 10 14:45:18 ulli d3edf43e34b8[638]:   File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 287, in async_set_updated_data
Mar 10 14:45:18 ulli d3edf43e34b8[638]:     update_callback()
Mar 10 14:45:18 ulli d3edf43e34b8[638]:   File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 325, in _handle_coordinator_update
Mar 10 14:45:18 ulli d3edf43e34b8[638]:     self.async_write_ha_state()
Mar 10 14:45:18 ulli d3edf43e34b8[638]:   File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 539, in async_write_ha_state
Mar 10 14:45:18 ulli d3edf43e34b8[638]:     self._async_write_ha_state()
Mar 10 14:45:18 ulli d3edf43e34b8[638]:   File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 572, in _async_write_ha_state
Mar 10 14:45:18 ulli d3edf43e34b8[638]:     state = self._stringify_state()
Mar 10 14:45:18 ulli d3edf43e34b8[638]:   File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 545, in _stringify_state
Mar 10 14:45:18 ulli d3edf43e34b8[638]:     if (state := self.state) is None:
Mar 10 14:45:18 ulli d3edf43e34b8[638]:   File "/config/custom_components/eufy_security/alarm_control_panel.py", line 236, in state
Mar 10 14:45:18 ulli d3edf43e34b8[638]:     return CODES_TO_STATES[current_mode]
Mar 10 14:45:18 ulli d3edf43e34b8[638]: KeyError: -1#033[0m
Mar 10 14:45:19 ulli d3edf43e34b8[638]: #033[31m2022-03-10 14:45:19 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
```

Known issue ?

**Comment by geoffm39** [comment]
i am also having the same issue, 2k doorbell

**Comment by fuatakgun** [comment]
Resolving this as of noe, please comment back
