### ISSUE TITLE
Since eufy security integration HA is getting unstable and restarts sometimes

### ISSUE THREAD

**Issue by smartmatic** [fuatakgun/eufy_security#297]
Please check Services, Known Bug / Issues and Troubleshooting over here first: https://github.com/fuatakgun/eufy_security/blob/master/README.md

**Describe the bug**
Since i integrated eufy security my HA instance has restarted sometimes when i try to open a eufy stream

**To Reproduce**
1. Add eufy camera to lovelace with a picture entity
2. Try to open a eufy RTSP stream with below entity settings
3.  Check behaviour 

**Expected behavior**
No unexpetced restarts of HA instance except triggered

**Screenshots**
![eufy_security_picture entity](https://user-images.githubusercontent.com/74932663/157825827-8d24e495-8587-46de-8632-497395726b04.png)

![eufy_security_configuration](https://user-images.githubusercontent.com/74932663/157823875-b019e2ea-5912-4f9c-b2a6-1d3e4f8ebe30.png)

**Hardware Information about Home Assistant
RPI4 with HA OS 2022.3.3

**Hardware Information about Cameras
- eufy cam 2 and eufy cam 2c + Homebase 2
- Live Streaming Protocol: RTSP and checked in the configuration P2P

**Additional context**
Various error messages found in the log

This error originated from a custom integration.

Logger: homeassistant
Source: custom_components/eufy_security/alarm_control_panel.py:236
Integration: Eufy Security (documentation, issues)
First occurred: 6:47:04 AM (847 occurrences)
Last logged: 7:01:18 AM

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/eufy_security/__init__.py", line 60, in update
    coordinator.async_set_updated_data(coordinator.data)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 287, in async_set_updated_data
    update_callback()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 325, in _handle_coordinator_update
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 553, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 590, in _async_write_ha_state
    state = self._stringify_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 559, in _stringify_state
    if (state := self.state) is None:
  File "/config/custom_components/eufy_security/alarm_control_panel.py", line 236, in state
    return CODES_TO_STATES[current_mode]
KeyError: -1

Logger: homeassistant.components.alarm_control_panel
Source: custom_components/eufy_security/alarm_control_panel.py:236
Integration: Alarm control panel (documentation, issues)
First occurred: 6:47:03 AM (2 occurrences)
Last logged: 6:47:03 AM

Error adding entities for domain alarm_control_panel with platform eufy_security
Error while setting up eufy_security platform for alarm_control_panel
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 382, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 614, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 801, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 553, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 590, in _async_write_ha_state
    state = self._stringify_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 559, in _stringify_state
    if (state := self.state) is None:
  File "/config/custom_components/eufy_security/alarm_control_panel.py", line 236, in state
    return CODES_TO_STATES[current_mode]
KeyError: -1

2022-03-11 00:00:54.840  ERROR Status return code not 200 
{
  status: 423,
  statusText: 'Locked'
}
2022-03-11 00:00:54.851  INFO  No stations found. 
2022-03-11 05:45:49.512  INFO  Client disconnected with ip: 172.30.32.1 port: 52238 code: 1006 reason:  
2022-03-11 05:45:49.534  INFO  Client disconnected with ip: 172.30.32.1 port: 52234 code: 1006 reason:  
2022-03-11 05:45:49.542  INFO  Client disconnected with ip: 172.30.32.1 port: 52884 code: 1006 reason:  
2022-03-11 06:01:18.980  INFO  Alarm mode for station T8010N2319491418 changed to: HOME

**Comment by fuatakgun** [comment]
I believe this should have been resolved by now, please reopen if needed.
