### ISSUE TITLE
New Install on Home Assistant, Latest HA,

### ISSUE THREAD

**Issue by Vyloo** [fuatakgun/eufy_security#301]
`Logger: homeassistant.config_entries
Source: custom_components/eufy_security/coordinator.py:184
Integration: Eufy Security ([documentation](https://github.com/fuatakgun/eufy_security), [issues](https://github.com/fuatakgun/eufy_security/issues))
First occurred: 12:44:52 PM (7 occurrences)
Last logged: 2:41:43 PM

Error setting up entry 0.0.0.0 for eufy_security
Error setting up entry localhost for eufy_security
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 335, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/eufy_security/__init__.py", line 51, in async_setup_entry
    await coordinator.initialize()
  File "/config/custom_components/eufy_security/coordinator.py", line 87, in initialize
    await self.set_devices()
  File "/config/custom_components/eufy_security/coordinator.py", line 163, in set_devices
    if await self.async_get_device_properties() is False:
  File "/config/custom_components/eufy_security/coordinator.py", line 184, in async_get_device_properties
    for device in self.devices.values():
AttributeError: 'NoneType' object has no attribute 'values'`

I have RSTP Server Addon installed.
I have it all configured the way its supposed to according to the guide.

**Comment by Vyloo** [comment]
2022-03-18 12:38:34 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration eufy_security which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-03-18 12:44:52 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry 0.0.0.0 for eufy_security
File "/config/custom_components/eufy_security/__init__.py", line 51, in async_setup_entry
File "/config/custom_components/eufy_security/coordinator.py", line 87, in initialize
File "/config/custom_components/eufy_security/coordinator.py", line 163, in set_devices
File "/config/custom_components/eufy_security/coordinator.py", line 184, in async_get_device_properties
2022-03-18 14:35:45 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry 0.0.0.0 for eufy_security
File "/config/custom_components/eufy_security/__init__.py", line 51, in async_setup_entry
File "/config/custom_components/eufy_security/coordinator.py", line 87, in initialize
File "/config/custom_components/eufy_security/coordinator.py", line 163, in set_devices
File "/config/custom_components/eufy_security/coordinator.py", line 184, in async_get_device_properties
2022-03-18 14:36:30 ERROR (MainThread) [custom_components.eufy_security] eufy_security - Event received but device is missing, maybe not connected
2022-03-18 14:36:30 ERROR (MainThread) [custom_components.eufy_security] eufy_security - Event received but device is missing, maybe not connected
2022-03-18 14:38:21 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry localhost for eufy_security
File "/config/custom_components/eufy_security/__init__.py", line 51, in async_setup_entry
File "/config/custom_components/eufy_security/coordinator.py", line 87, in initialize
File "/config/custom_components/eufy_security/coordinator.py", line 163, in set_devices
File "/config/custom_components/eufy_security/coordinator.py", line 184, in async_get_device_properties
2022-03-18 14:40:31 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry localhost for eufy_security
File "/config/custom_components/eufy_security/__init__.py", line 51, in async_setup_entry
File "/config/custom_components/eufy_security/coordinator.py", line 87, in initialize
File "/config/custom_components/eufy_security/coordinator.py", line 163, in set_devices
File "/config/custom_components/eufy_security/coordinator.py", line 184, in async_get_device_properties
2022-03-18 14:40:48 ERROR (MainThread) [custom_components.eufy_security.config_flow] eufy_security Exception in login : Cannot connect to host locahost:3000 ssl:default [Try again] - traceback: Traceback (most recent call last):
File "/config/custom_components/eufy_security/config_flow.py", line 191, in _test_credentials
File "/config/custom_components/eufy_security/websocket.py", line 40, in connect
2022-03-18 14:40:54 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry localhost for eufy_security
File "/config/custom_components/eufy_security/__init__.py", line 51, in async_setup_entry
File "/config/custom_components/eufy_security/coordinator.py", line 87, in initialize
File "/config/custom_components/eufy_security/coordinator.py", line 163, in set_devices
File "/config/custom_components/eufy_security/coordinator.py", line 184, in async_get_device_properties
2022-03-18 14:41:12 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry localhost for eufy_security
File "/config/custom_components/eufy_security/__init__.py", line 51, in async_setup_entry
File "/config/custom_components/eufy_security/coordinator.py", line 87, in initialize
File "/config/custom_components/eufy_security/coordinator.py", line 163, in set_devices
File "/config/custom_components/eufy_security/coordinator.py", line 184, in async_get_device_properties
2022-03-18 14:41:38 ERROR (MainThread) [custom_components.eufy_security.config_flow] eufy_security Exception in login : Cannot connect to host locahost:3000 ssl:default [Try again] - traceback: Traceback (most recent call last):
File "/config/custom_components/eufy_security/config_flow.py", line 191, in _test_credentials
File "/config/custom_components/eufy_security/websocket.py", line 40, in connect
2022-03-18 14:41:43 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry localhost for eufy_security
File "/config/custom_components/eufy_security/__init__.py", line 51, in async_setup_entry
File "/config/custom_components/eufy_security/coordinator.py", line 87, in initialize
File "/config/custom_components/eufy_security/coordinator.py", line 163, in set_devices
File "/config/custom_components/eufy_security/coordinator.py", line 184, in async_get_device_properties
2022-03-18 14:49:18 ERROR (MainThread) [custom_components.eufy_security] eufy_security - Event received but device is missing, maybe not connected
2022-03-18 14:49:18 ERROR (MainThread) [custom_components.eufy_security] eufy_security - Event received but device is missing, maybe not connected

**Comment by Vyloo** [comment]
2022-03-18 19:53:50.782  INFO  Eufy Security server listening on host 0.0.0.0, port 3000 
2022-03-18 19:53:53.607  INFO  Connected to station T8410P31212804B4 on host 192.168.2.171 and port 19420 
2022-03-18 19:53:53.654  INFO  Connected to station T8410P3121300E4D on host 192.168.2.109 and port 19420 
imings: {
    start: 1647633239537,
    socket: 1647633239537,
    lookup: 1647633239537,
    connect: undefined,
    secureConnect: undefined,
    upload: undefined,
    response: undefined,
    end: undefined,
    error: 1647633239537,
    abort: undefined,
    phases: {
      wait: 0,
      dns: 0,
      tcp: undefined,
      tls: undefined,
      request: undefined,
      firstByte: undefined,
      download: undefined,
      total: 0
    }
  }
}
error stack:
• index.js:962 <anonymous>
    node_modules/got/dist/source/core/index.js:962:111
• node:events:640 onceWrapper
    node:events:640:26
• node:events:532 emit
    node:events:532:35
• index.js:43 origin.emit
    node_modules/@szmarczak/http-timer/dist/source/index.js:43:20
• node:_http_client:442 socketErrorListener
    node:_http_client:442:9
• node:events:520 emit
    node:events:520:28
• destroy:157 emitErrorNT
    node:internal/streams/destroy:157:8
• destroy:122 emitErrorCloseNT
    node:internal/streams/destroy:122:3
• task_queues:83 processTicksAndRejections
    node:internal/process/task_queues:83:21
2022-03-18 19:53:59.552  ERROR registerFid - Status return code not 200 
{
  status: undefined,
  statusText: undefined,
  data: undefined
}
2022-03-18 19:53:59.554  ERROR registerFid - Generic Error: 
 Error  FID registration failed with error: undefined
error stack:
• service.ts:88 registerFid
    node_modules/eufy-security-client/src/push/service.ts:88:23
• task_queues:96 processTicksAndRejections
2022-03-18 19:53:59.561  INFO  Push notification connection closed 
    node:internal/process/task_queues:96:5
• service.ts:145 createPushCredentials
    node_modules/eufy-security-client/src/push/service.ts:145:16
2022-03-18 19:53:59.563  INFO  Retry to register/login for push notification in 5 seconds... 
• service.ts:528 _open
    node_modules/eufy-security-client/src/push/service.ts:528:32
• service.ts:592 open
    node_modules/eufy-security-client/src/push/service.ts:592:13
2022-03-18 19:53:59.558  ERROR Create push credentials Error: 
 Error  FID registration failed with error: Error: FID registration failed with error: undefined
error stack:
• service.ts:92 registerFid
    node_modules/eufy-security-client/src/push/service.ts:92:19
• task_queues:96 processTicksAndRejections
    node:internal/process/task_queues:96:5
• service.ts:145 createPushCredentials
    node_modules/eufy-security-client/src/push/service.ts:145:16
• service.ts:528 _open
    node_modules/eufy-security-client/src/push/service.ts:528:32
• service.ts:592 open
    node_modules/eufy-security-client/src/push/service.ts:592:13
2022-03-18 19:53:59.562  ERROR Push notifications are disabled, because the registration failed! 
2022-03-18 19:54:04.564  INFO  Retry to register/login for push notification
