### ISSUE TITLE
Unable to Connect Eufy Security Add On: 20028 Failed to request

### ISSUE THREAD

**Issue by jiayuandeng** [fuatakgun/eufy_security#302]
**Describe the bug**
I am doing a new installation, following the add-on installation guide 6.1. When I tried to start the add on, I'm getting 20028 error in log:

```2022-03-24 09:38:50.948  INFO  Eufy Security server listening on host 0.0.0.0, port 3000 
2022-03-24 09:38:56.535  INFO  Push notification connection successfully established 
2022-03-24 09:38:56.655  ERROR Station T8510Q1021210C08 - Response code not ok 
{
  code: 20028,
  msg: 'Failed to request.'
}
node:internal/errors:464
    ErrorCaptureStackTrace(err);
    ^
TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received undefined
    at new NodeError (node:internal/errors:371:5)
    at Function.from (node:buffer:322:9)
    at stringWithLength (/usr/src/app/node_modules/eufy-security-client/build/p2p/utils.js:25:35)
    at p2pDidToBuffer (/usr/src/app/node_modules/eufy-security-client/build/p2p/utils.js:49:18)
    at buildLookupWithKeyPayload (/usr/src/app/node_modules/eufy-security-client/build/p2p/utils.js:53:26)
    at P2PClientProtocol.lookupByAddress (/usr/src/app/node_modules/eufy-security-client/build/p2p/session.js:242:63)
    at /usr/src/app/node_modules/eufy-security-client/build/p2p/session.js:226:51
    at Array.map (<anonymous>)
    at P2PClientProtocol.lookup (/usr/src/app/node_modules/eufy-security-client/build/p2p/session.js:226:29)
    at Socket.<anonymous> (/usr/src/app/node_modules/eufy-security-client/build/p2p/session.js:305:26) {
  code: 'ERR_INVALID_ARG_TYPE'
}```

Googling it does not give any useful result. Is there any workaround?

**Comment by jiayuandeng** [comment]
Solved, see https://github.com/bropat/eufy-security-ws/issues/20

Your account cannot have bluetooth-only locks (another reason to use a separate eufy account).
