### ISSUE TITLE
Error doing job: Task exception was never retrieved

### ISSUE THREAD

**Issue by divebeer** [fuatakgun/eufy_security#328]
In my error log i get the error Error doing job: Task exception was never retrieved every second.
Eufy seems to work ok but the system is very busy to generate these error.
 i have a homebase T8010
a doorbell T8210
a camera T8114
a camera T-8114-Z

here a copy of my log

Error doing job: Task exception was never retrieved

Traceback (most recent call last):
  File "/config/custom_components/eufy_security/__init__.py", line 60, in update
    coordinator.async_set_updated_data(coordinator.data)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 292, in async_set_updated_data
    update_callback()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 330, in _handle_coordinator_update
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 533, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 571, in _async_write_ha_state
    state = self._stringify_state(available)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 539, in _stringify_state
    if (state := self.state) is None:
  File "/config/custom_components/eufy_security/alarm_control_panel.py", line 236, in state
    return CODES_TO_STATES[current_mode]
KeyError: -1

**Comment by mojodmonkey** [comment]
I'm getting this same issue when trying to view one of my cameras Solo IndoorCam C24 (2K, Plug-in)

My doorbell from Eufy works just fine. 
This started happening after the update to HA 2022.7.0

I am currently on 
Home Assistant 2022.7.5
Supervisor 2022.07.0
Operating System 8.2
Frontend 20220707.1 - latest


This error originated from a custom integration.

Logger: homeassistant
Source: custom_components/eufy_security/alarm_control_panel.py:236
Integration: Eufy Security (documentation, issues)
First occurred: 2:24:57 PM (28 occurrences)
Last logged: 2:25:25 PM

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/eufy_security/__init__.py", line 60, in update
    coordinator.async_set_updated_data(coordinator.data)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 304, in async_set_updated_data
    self.async_update_listeners()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 110, in async_update_listeners
    update_callback()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 339, in _handle_coordinator_update
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 532, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 570, in _async_write_ha_state
    state = self._stringify_state(available)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 538, in _stringify_state
    if (state := self.state) is None:
  File "/config/custom_components/eufy_security/alarm_control_panel.py", line 236, in state
    return CODES_TO_STATES[current_mode]
KeyError: -1

**Comment by fuatakgun** [comment]
can you retest please?
