### ISSUE TITLE
T8520 lock state is no longer updating

### ISSUE THREAD

**Issue by alexeiw123** [fuatakgun/eufy_security#376]
Please check Services, Known Bug / Issues and Troubleshooting over here first: https://github.com/fuatakgun/eufy_security/blob/master/README.md

**Describe the bug**
T8520 (Smart Lock Touch + WiFi) can no longer be reliably controlled through HA dashboard.
By opening entity control manual lock/unlock commands work but the lock state is not updated, or any action appearing in the logbook.

This was working previously on both v2.2.5 (definitely) and v2.2.6 (I'm pretty sure). Unsure on what conditions changed that coincide with it stopping working.

I have tried downgrading to 2.2.5, various reboots and removing and re-adding the integration.

When re-installing the integration, the correct state is displayed initially but it does not get updated through use.

**To Reproduce**
1. Go to dashboard with door lock.
2. Click on 'lock' or 'unlock' - door may lock or unlock depending on state.
3. Button state will not update
4. Open entity
5. Test individual lock/unlock buttons
6. Confirm actions are not in logbook.

**Expected behavior**
Dashboard lock card to reflect actual lock state.
lock.front_door state to update as expected in developer tools

**Screenshots**

![image](https://user-images.githubusercontent.com/77809797/176306949-39647016-8f40-4c29-b7f2-58a07c82950f.png)
![image](https://user-images.githubusercontent.com/77809797/176307136-d68a35fa-e384-4523-946c-0cbbe69c7912.png)
![image](https://user-images.githubusercontent.com/77809797/176307300-32e1fec0-b7ae-4305-8d79-6c6fc8c0e2f7.png)
![image](https://user-images.githubusercontent.com/77809797/176308952-292e6fc9-2cad-4ee7-a2ab-44ebd76d4f18.png)

**Hardware Information about Home Assistant
Rasp pi 3B+ 64bit (SSD)

**Hardware Information about Cameras
N/A

**Additional context**
Pretty new to HA - happy to provide logs but will need a dummy's guide on how to do that in a helpful way.

**Comment by alexeiw123** [comment]
I'm not sure if this is helpful, here's an excerpt from my homeassistant.log after unlocking and locking the lock from HA (although status didn't update).

There was a LOT of content like this in the logs that I haven't copied. I can provide the whole thing if needed.

```
2022-07-12 08:24:07 DEBUG (MainThread) [custom_components.eufy_security] eufy_security - set_event_for_entity - device / T8520Q2021370971 / locked / False
2022-07-12 08:24:07 DEBUG (MainThread) [custom_components.eufy_security] Manually updated eufy_security data
2022-07-12 08:24:07 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/eufy_security/__init__.py", line 60, in update
    coordinator.async_set_updated_data(coordinator.data)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 304, in async_set_updated_data
    self.async_update_listeners()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 110, in async_update_listeners
    update_callback()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 339, in _handle_coordinator_update
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 532, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 570, in _async_write_ha_state
    state = self._stringify_state(available)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 538, in _stringify_state
    if (state := self.state) is None:
  File "/config/custom_components/eufy_security/alarm_control_panel.py", line 236, in state
    return CODES_TO_STATES[current_mode]
KeyError: -1
2022-07-12 08:24:08 DEBUG (MainThread) [custom_components.eufy_security] Manually updated eufy_security data
2022-07-12 08:24:08 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/eufy_security/__init__.py", line 60, in update
    coordinator.async_set_updated_data(coordinator.data)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 304, in async_set_updated_data
    self.async_update_listeners()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 110, in async_update_listeners
    update_callback()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 339, in _handle_coordinator_update
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 532, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 570, in _async_write_ha_state
    state = self._stringify_state(available)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 538, in _stringify_state
    if (state := self.state) is None:
  File "/config/custom_components/eufy_security/alarm_control_panel.py", line 236, in state
    return CODES_TO_STATES[current_mode]
KeyError: -1
2022-07-12 08:24:08 DEBUG (MainThread) [custom_components.eufy_security] eufy_security - set_event_for_entity - device / T8520Q2021370971 / lockStatus / 3
2022-07-12 08:24:09 DEBUG (MainThread) [custom_components.eufy_security] Manually updated eufy_security data
2022-07-12 08:24:09 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
```

**Comment by alexeiw123** [comment]
a-ha! this error only occurs while the eufy app is set to geofencing mode.
If I change the mode to 'home' then it behaves normally.

**Comment by fuatakgun** [comment]
Nice finding let me investigate this

**Comment by fuatakgun** [comment]
i need someone to share the lock with me (you can find account details on README) and let me debug the issue

**Comment by fuatakgun** [comment]
merging threads: https://github.com/fuatakgun/eufy_security/issues/349

**Comment by alexeiw123** [comment]
> i need someone to share the lock with me (you can find account details on README) and let me debug the issue

Noting this issue is now closed, do you still need access to debug or have you got it sorted?

**Comment by fuatakgun** [comment]
I have just merged it into another issue, did not resolve this specifically
