### ISSUE TITLE
Eufy Security Add-On 0.9.4 Crashes on Start

### ISSUE THREAD

**Issue by kardboard604** [fuatakgun/eufy_security#410]
New fresh HASS 2022.7.7 install on Raspberry Pi 4 B, following the instructions and after installing the add-on, found that it doesn't stay loaded. Logs show:

`2022-08-01 04:41:25.409  INFO  Eufy Security server listening on host 0.0.0.0, port 3000 
/usr/src/app/node_modules/eufy-security-client/build/http/device.js:51
            this.rawDevice.params.forEach(param => {
                                  ^
TypeError: Cannot read properties of null (reading 'forEach')
    at UnknownDevice.update (/usr/src/app/node_modules/eufy-security-client/build/http/device.js:51:35)
    at UnknownDevice.initializeState (/usr/src/app/node_modules/eufy-security-client/build/http/device.js:30:14)
    at Function.initialize (/usr/src/app/node_modules/eufy-security-client/build/http/device.js:1810:17)
    at EufySecurity.handleDevices (/usr/src/app/node_modules/eufy-security-client/build/eufysecurity.js:449:57)
    at HTTPApi.<anonymous> (/usr/src/app/node_modules/eufy-security-client/build/eufysecurity.js:117:50)
    at HTTPApi.emit (node:events:527:28)
    at HTTPApi.refreshDeviceData (/usr/src/app/node_modules/eufy-security-client/build/http/api.js:517:22)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async HTTPApi.refreshAllData (/usr/src/app/node_modules/eufy-security-client/build/http/api.js:530:9)
    at async EufySecurity.refreshCloudData (/usr/src/app/node_modules/eufy-security-client/build/eufysecurity.js:499:9)`

Can restart it and immediately do the config with a second Eufy Security account as suggested. Tried restarting HASS many times but no change, won't stay running. Tried another fresh install and same thing. Can follow the rest of the readme to get HACS, Eufy Security integration, RTSP Simple Server add-on, but obviously not fully working as Eufy Security Add-On just won't stay running.

New to all this, and not sure what this all means.

**Comment by fuatakgun** [comment]
Please create a issue under eufy-security-ws repository, error is originated under that library, repository owner would release a new version and i will do the same after fix.
