### ISSUE TITLE
Addon Service Fail After Update

### ISSUE THREAD

**Issue by kobioneil** [fuatakgun/eufy_security#417]
![image](https://user-images.githubusercontent.com/88595725/183069090-e398d8a6-33d9-462a-a7ef-6588e061d961.png)

2022-08-05 11:33:32.104  INFO  Eufy Security server listening on host 0.0.0.0, port 3000 
2022-08-05 11:33:35.592  INFO  MQTT connection successfully established 
2022-08-05 11:33:35.600  INFO  Connected to station T8010N13202418F1 on host 10.0.0.46 and port 10204 
2022-08-05 11:33:35.677  INFO  Successfully registered to MQTT notifications for lock T8510Q1021260FCB 
2022-08-05 11:33:42.374  ERROR Station T8510Q1021260FCB - Response code not ok 
{
  code: 20028,
  msg: 'Failed to request.'
}
node:internal/errors:465
    ErrorCaptureStackTrace(err);
    ^
TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received undefined
    at new NodeError (node:internal/errors:372:5)
    at Function.from (node:buffer:323:9)
    at stringWithLength (/usr/src/app/node_modules/eufy-security-client/build/p2p/utils.js:22:35)
    at p2pDidToBuffer (/usr/src/app/node_modules/eufy-security-client/build/p2p/utils.js:48:18)
    at buildLookupWithKeyPayload (/usr/src/app/node_modules/eufy-security-client/build/p2p/utils.js:52:26)
    at P2PClientProtocol.lookupByAddress (/usr/src/app/node_modules/eufy-security-client/build/p2p/session.js:257:63)
    at /usr/src/app/node_modules/eufy-security-client/build/p2p/session.js:241:51
    at Array.map (<anonymous>)
    at P2PClientProtocol.lookup (/usr/src/app/node_modules/eufy-security-client/build/p2p/session.js:241:29)
    at Socket.<anonymous> (/usr/src/app/node_modules/eufy-security-client/build/p2p/session.js:308:26) {
  code: 'ERR_INVALID_ARG_TYPE'
}

**Comment by kobioneil** [comment]
I created a new user account through the eufy app and shared the devices with that account, which is what I was already doing, but doing it again seemed to be the trick
