### ISSUE TITLE
Lock state and alarm state not updating when mode is away.

### ISSUE THREAD

**Issue by alexeiw123** [fuatakgun/eufy_security#424]
**Describe the bug**
Lock T8520 lock state stops updating when my eufy alarm state changes to away. Alarm state changes also do not update in HA.
If I restart the integration, the lock and alarm state start working again, until the next time the bug is triggered.

**To Reproduce**
1. Test lock state is updating on 'home' alarm state
2. Change alarm state to 'away' in eufy app
3. Confirm that lock state is no longer updating and observe pop up error: "failed to call service lock/lock. Exception: Host/port is not reachable localhost 3000!" This error stops occurring after a few attempts.
4. Confirm that alarm state in HA has changed to 'away' but register further changes
5. Restart integration from HA
6. Confirm lock state is updating again

**Expected behavior**
Lock and alarm status to update as they are changed.

**Additional context**
Integration version 2.6.3
Eufy Security Add-on 0.9.4
Lock can be controlled by calling lock/unlock service but status doesn't update, which breaks lovelace lock card behaviour.

**Comment by fuatakgun** [comment]
Can you check and share if there are any error or warn logs from integration and add-on?

**Comment by alexeiw123** [comment]
> Can you check and share if there are any error or warn logs from integration and add-on?

Yes, there is.

I did a few different lock and unlocks as well as attempts to lock/unlock with the state shown wrong.

I also turned on debug logging but there was a lot of unrelated things in the log, I figured they system > logs output will be of more use to you know. Let me know if you want something more specific.

```
This error originated from a custom integration.

Logger: custom_components.eufy_security
Source: custom_components/eufy_security/coordinator.py:381
Integration: Eufy Security (documentation, issues)
First occurred: 8:09:03 AM (5 occurrences)
Last logged: 8:10:17 AM

eufy_security - Event received but device is missing, maybe not connected - 'T8422N10xx'
eufy_security - Event received but device is missing, maybe not connected - 'T8520Q20xx'
```

```
This error originated from a custom integration.

Logger: custom_components.eufy_security
Source: custom_components/eufy_security/coordinator.py:381
Integration: Eufy Security (documentation, issues)
First occurred: 8:09:03 AM (3 occurrences)
Last logged: 8:09:07 AM

eufy_security - Event received but device is missing, maybe not connected - 'T8422N1021320AE8'
eufy_security - Event received but device is missing, maybe not connected - 'T8520Q2021370971'
```

```
This error originated from a custom integration.

Logger: custom_components.eufy_security
Source: custom_components/eufy_security/websocket.py:59
Integration: Eufy Security (documentation, issues)
First occurred: 8:09:00 AM (1 occurrences)
Last logged: 8:09:00 AM

eufy_security - Exception - process_messages: 'result' - traceback: Traceback (most recent call last): File "/config/custom_components/eufy_security/websocket.py", line 57, in process_messages await self.on_message(msg) File "/config/custom_components/eufy_security/websocket.py", line 68, in on_message await self.message_callback(message) File "/config/custom_components/eufy_security/coordinator.py", line 297, in on_message message_result = payload[message_type] KeyError: 'result' - message: WSMessage(type=<WSMsgType.TEXT: 1>, data='{"type":"result","success":false,"messageId":"lock_device","errorCode":"device_not_found"}', extra='')
```

Didn't see anything of interest in the add-on logs.

**Comment by fuatakgun** [comment]
Have you tried to remove everything and install from scratch? Apparently, integration and add-on are out of sync.

**Comment by alexeiw123** [comment]
No, I haven't yet. By everything, do you mean in HA? Or also removing devices from eufy?

**Comment by fuatakgun** [comment]
Removing the integration and adding it back

**Comment by alexeiw123** [comment]
I'm just about to remove and re-add - but thought to test the bug exists before so. Picked up something more length in the logs:

Again, this is before removing the integration.

```
Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/eufy_security/coordinator.py:114
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 8:01:03 AM (2 occurrences)
Last logged: 8:01:12 AM

[547295101184] Exception: Host/port is not reachable localhost 3000!
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 986, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 1064, in create_connection
    raise exceptions[0]
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 1049, in create_connection
    sock = await self._connect_sock(
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 960, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/local/lib/python3.10/asyncio/selector_events.py", line 500, in sock_connect
    return await fut
  File "/usr/local/lib/python3.10/asyncio/selector_events.py", line 535, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 111] Connect call failed ('127.0.0.1', 3000)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/eufy_security/coordinator.py", line 112, in connect
    await self.ws.connect()
  File "/config/custom_components/eufy_security/websocket.py", line 41, in connect
    self.ws: aiohttp.ClientWebSocketResponse = await self.session.ws_connect(
  File "/usr/local/lib/python3.10/site-packages/aiohttp/client.py", line 776, in _ws_connect
    resp = await self.request(
  File "/usr/local/lib/python3.10/site-packages/aiohttp/client.py", line 535, in _request
    conn = await self._connector.connect(
  File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 542, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 907, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 1175, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
  File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 992, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:3000 ssl:default [Connect call failed ('127.0.0.1', 3000)]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 199, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1713, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1750, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 204, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 676, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 930, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 713, in _handle_entity_call
    await result
  File "/config/custom_components/eufy_security/lock.py", line 54, in async_unlock
    await self.coordinator.async_set_lock(self.device.serial_number, False)
  File "/config/custom_components/eufy_security/coordinator.py", line 536, in async_set_lock
    await self.async_send_message(json.dumps(message))
  File "/config/custom_components/eufy_security/coordinator.py", line 423, in async_send_message
    await self.connect()
  File "/config/custom_components/eufy_security/coordinator.py", line 114, in connect
    raise ConfigEntryNotReady(
homeassistant.exceptions.ConfigEntryNotReady: Exception: Host/port is not reachable localhost 3000!
```

**Comment by alexeiw123** [comment]
> Removing the integration and adding it back

I removed the integration, removed it from HACS and re-added and set up.
The issues still exists. It worked while in away mode but as soon as I changed the mode in eufy, it stopped responding again.

It seems the bug is more related to changing modes than it is to the 'away' mode specifically.

**Comment by fuatakgun** [comment]
i need to debug this after you share this device with me following readme.

If you prefer simultaneous sharing and debugging together, i will try to set a fixed time every weekends, we can work together
