### ISSUE TITLE
Add on crasches and system doesn't respond aymore SINCE update 2022.8

### ISSUE THREAD

**Issue by sbeukers** [fuatakgun/eufy_security#438]
Hi, 
Can you please help me with the following problem?

The addon crasches since 2022.8
The system works for a while (form a few hours to a few days but never more than 2 days)
The system was rock solid before
The system does not respond to any status change anymore.
Doors opening or closing doesn't register.

After rebooting the addon everything is fine again.
I've enabled watchdog.

LOG
2022-08-22 10:50:45.268  INFO  Eufy Security server listening on host 0.0.0.0, port 3000 
2022-08-22 10:50:55.430  INFO  Connected to station T8010Pxxxxxxxx on host 192.168.0.xx and port 12050 
2022-08-22 10:50:55.549  INFO  Push notification connection successfully established 
2022-08-22 10:51:03.441  INFO  Disconnected from station T8010Pxxxxxxxx 
2022-08-22 10:51:08.485  INFO  Connected to station T8010Pxxxxxxxx on host 192.168.0.xx and port 14370 
2022-08-22 10:51:16.583  INFO  Disconnected from station T8010Pxxxxxxxx 
2022-08-22 10:51:21.630  INFO  Connected to station T8010Pxxxxxxxx on host 192.168.0.xx and port 29019 
2022-08-22 10:51:29.654  INFO  Disconnected from station T8010Pxxxxxxxx 
2022-08-22 10:51:34.700  INFO  Connected to station T8010Pxxxxxxxx on host 192.168.0.xx and port 21930 
2022-08-22 10:51:42.743  INFO  Disconnected from station T8010Pxxxxxxxx 
2022-08-22 10:51:47.780  INFO  Connected to station T8010Pxxxxxxxx on host 192.168.0.xx and port 24872 
2022-08-22 10:51:55.847  INFO  Disconnected from station T8010Pxxxxxxxx 
2022-08-22 10:52:00.883  INFO  Connected to station T8010Pxxxxxxxx on host 192.168.0.xx and port 17407 
2022-08-22 10:52:08.891  INFO  Disconnected from station T8010Pxxxxxxxx 
2022-08-22 10:52:13.932  INFO  Connected to station T8010Pxxxxxxxx on host 192.168.0.xx and port 24746 
2022-08-22 10:52:21.975  INFO  Disconnected from station T8010Pxxxxxxxx 
2022-08-22 10:52:27.009  INFO  Connected to station T8010Pxxxxxxxx on host 192.168.0.xx and port 18056 
2022-08-22 10:52:35.083  INFO  Disconnected from station T8010Pxxxxxxxx 
2022-08-22 10:52:40.115  INFO  Connected to station T8010Pxxxxxxxx on host 192.168.0.xx and port 25532 
undefined:1
SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at /usr/src/app/node_modules/eufy-security-client/build/push/client.js:207:38
    at Array.forEach (<anonymous>)
    at PushClient.convertPayloadMessage (/usr/src/app/node_modules/eufy-security-client/build/push/client.js:205:17)
    at PushClient.handleParsedMessage (/usr/src/app/node_modules/eufy-security-client/build/push/client.js:154:43)
    at PushClientParser.<anonymous> (/usr/src/app/node_modules/eufy-security-client/build/push/client.js:56:63)
    at PushClientParser.emit (node:events:527:28)
    at PushClientParser.onGotMessageBytes (/usr/src/app/node_modules/eufy-security-client/build/push/parser.js:137:14)
    at PushClientParser.handleFullMessage (/usr/src/app/node_modules/eufy-security-client/build/push/parser.js:66:22)
    at PushClientParser.waitForData (/usr/src/app/node_modules/eufy-security-client/build/push/parser.js:51:18)

Virtual Machine (HyperV)
Home Assistant 2022.8.6
Supervisor 2022.08.3
Operating System 8.4
Frontend-versie: 20220802.0 - latest

HomeBase 2 version 3.1.9.0h
subsystem 1.3.0.9

Can you please help me with this problem?

It seems like it is constantly disconnecting
I also rebooted the HomeBase

And please let me know if you need anything else.

Best Regards,

Sjoerd Beukers

**Comment by fuatakgun** [comment]
please create an issue under eufy-security-ws repository
