### ISSUE TITLE
Add on stop on alarm mode update

### ISSUE THREAD

**Issue by fschneider-wedge** [fuatakgun/eufy_security#450]
When I switch alarm mode, Eufy add-on stop with this logs:
```
2022-09-02 14:56:12.616  INFO  Alarm mode for station T8010T25251501F3 changed to: AWAY 
/usr/src/app/node_modules/eufy-security-client/build/http/station.js:528
            const securitySettingsData = this.getPropertyValue(propertyName).toString();
                                                                            ^
TypeError: Cannot read properties of undefined (reading 'toString')
    at Station.getArmDelay (/usr/src/app/node_modules/eufy-security-client/build/http/station.js:528:77)
    at Station.onAlarmMode (/usr/src/app/node_modules/eufy-security-client/build/http/station.js:501:31)
    at P2PClientProtocol.<anonymous> (/usr/src/app/node_modules/eufy-security-client/build/http/station.js:33:57)
    at P2PClientProtocol.emit (node:events:527:28)
    at P2PClientProtocol.handleDataControl (/usr/src/app/node_modules/eufy-security-client/build/p2p/session.js:1185:22)
    at P2PClientProtocol.handleData (/usr/src/app/node_modules/eufy-security-client/build/p2p/session.js:899:18)
    at P2PClientProtocol.parseDataMessage (/usr/src/app/node_modules/eufy-security-client/build/p2p/session.js:891:26)
    at P2PClientProtocol.handleMsg (/usr/src/app/node_modules/eufy-security-client/build/p2p/session.js:718:26)
    at Socket.<anonymous> (/usr/src/app/node_modules/eufy-security-client/build/p2p/session.js:76:56)
    at Socket.emit (node:events:527:28)
```

**Hardware Information about Home Assistant**
Home Assistant 2022.8.7
Supervisor 2022.08.5
Operating System 8.5
Frontend 20220802.0 - latest

**Hardware Information about Cameras**
- Camera Model : 2C Pro 
- version du système 3.3.8

**Comment by fschneider-wedge** [comment]
I've found an issue on **eufy-security-client**: https://github.com/bropat/eufy-security-client/issues/196

**Comment by fschneider-wedge** [comment]
After rebooting Home Assistant pb do not occured anymore
