### ISSUE TITLE
Integration problem

### ISSUE THREAD

**Issue by Simppen** [fuatakgun/eufy_security#458]
I got the error below and could not really find any info on what I did wrong. My skills are not very advanced so there is a slight risk that I am polluting the forum.. anyway… 

Logger: homeassistant.setup
Source: setup.py:291 
First occurred: 13:53:16 (1 occurrences) 
Last logged: 13:53:16

Unable to prepare setup for platform eufy_security.camera: Platform not found (cannot import name 'CameraEntityFeature' from 'homeassistant.components.camera' (/usr/src/homeassistant/homeassistant/components/camera/__init__.py))

**Comment by Simppen** [comment]
This one as well:

Logger: homeassistant
Source: custom_components/eufy_security/alarm_control_panel.py:240 
Integration: Eufy Security ([documentation](https://github.com/fuatakgun/eufy_security), [issues](https://github.com/fuatakgun/eufy_security/issues)) 
First occurred: 16:14:56 (47 occurrences) 
Last logged: 16:15:39

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/eufy_security/__init__.py", line 60, in update
    coordinator.async_set_updated_data(coordinator.data)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 287, in async_set_updated_data
    update_callback()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 325, in _handle_coordinator_update
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 505, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 538, in _async_write_ha_state
    state = self._stringify_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 511, in _stringify_state
    if (state := self.state) is None:
  File "/config/custom_components/eufy_security/alarm_control_panel.py", line 240, in state
    return CODES_TO_STATES[current_mode]
KeyError: -1

**Comment by fuatakgun** [comment]
i need to debug this after you share this device with me following readme.

If you prefer simultaneous sharing and debugging together, i will try to set a fixed time every weekends, we can work together

**Comment by Simppen** [comment]
Hi,

Thanks for your reply. However, I now found that the ”Unable to prepare setup…” disappeared after system update. The other one still appears but the integration still works, at least for my purposes. So I think debugging is not needed at this point.
