### ISSUE TITLE
Different but Simular Eufy Security Add-on Failure to Start

### ISSUE THREAD

**Issue by kobioneil** [fuatakgun/eufy_security#478]
Im running Home Assistant Blue (a.k.a., ODROID N2+) 
After a restart I have to manually go into the addon and press start, and then I get this..

![image](https://user-images.githubusercontent.com/88595725/194441013-4ca2ce06-af60-49fc-8bb4-6c4f85f9fd2b.png)

Eufy Security Add-on
    node:_tls_wrap:1532:34
• node:events:527 emit
    node:events:527:28
• node:_tls_wrap:946 TLSSocket._finishInit
    node:_tls_wrap:946:8
• node:_tls_wrap:727 ssl.onhandshakedone
    node:_tls_wrap:727:12
2022-10-07 00:00:31.949  INFO  MQTT connection closed 
2022-10-07 00:00:33.141  ERROR MQTT Error 
 Error  certificate has expired
details:
{
  code: 'CERT_HAS_EXPIRED'
}
error stack:
• node:_tls_wrap:1532 onConnectSecure
    node:_tls_wrap:1532:34
• node:events:527 emit
    node:events:527:28
• node:_tls_wrap:946 TLSSocket._finishInit
    node:_tls_wrap:946:8
• node:_tls_wrap:727 ssl.onhandshakedone
    node:_tls_wrap:727:12
2022-10-07 00:00:33.144  INFO  MQTT connection closed 
2022-10-07 00:00:34.342  ERROR MQTT Error 
 Error  certificate has expired
details:
{
  code: 'CERT_HAS_EXPIRED'
}
error stack:
• node:_tls_wrap:1532 onConnectSecure
    node:_tls_wrap:1532:34
• node:events:527 emit
    node:}
error stack:
• node:_tls_wrap:1532 onConnectSecure
    node:_tls_wrap:1532:34
• node:events:527 emit
    node:events:527:28
• node:_tls_wrap:946 TLSSocket._finishInit
    node:_tls_wrap:946:8
• node:_tls_wrap:727 ssl.onhandshakedone
    node:_tls_wrap:727:12
2022-10-07 00:00:34.344  INFO  MQTT connection closed 
2022-10-07 00:00:35.534  ERROR MQTT Error 
 Error  certificate has expired
details:
{
  code: 'CERT_HAS_EXPIRED'
}
error stack:
• node:_tls_wrap:1532 onConnectSecure
    node:_tls_wrap:1532:34
• node:events:527 emit
    node:events:527:28
• node:_tls_wrap:946 TLSSocket._finishInit
    node:_tls_wrap:946:8
• node:_tls_wrap:727 ssl.onhandshakedone
    node:_tls_wrap:727:12
2022-10-07 00:00:35.536  INFO  MQTT connection closed 
2022-10-07 00:00:36.798  INFO  MQTT connection successfully established 
2022-10-07 00:00:36.871  INFO  Successfully registered to MQTT notifications for lock T8510Q1021260FCB 
2022-10-07 00:00:37.591  ERROR Station T8510Q1021260FCB - Response code not ok 
{
  code: 20028,
  msg: 'Failed to request.'
}
node:internal/errors:465
    ErrorCaptureStackTrace(err);
    ^
TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received undefined
    at new NodeError (node:internal/errors:372:5)
    at Function.from (node:buffer:323:9)
    at stringWithLength (/usr/src/app/node_modules/eufy-security-client/build/p2p/utils.js:22:35)
    at p2pDidToBuffer (/usr/src/app/node_modules/eufy-security-client/build/p2p/utils.js:48:18)
    at buildLookupWithKeyPayload (/usr/src/app/node_modules/eufy-security-client/build/p2p/utils.js:52:26)
    at P2PClientProtocol.lookupByAddress (/usr/src/app/node_modules/eufy-security-client/build/p2p/session.js:257:63)
    at /usr/src/app/node_modules/eufy-security-client/build/p2p/session.js:241:51
    at Array.map (<anonymous>)
    at P2PClientProtocol.lookup (/usr/src/app/node_modules/eufy-security-client/build/p2p/session.js:241:29)
    at Socket.<anonymous> (/usr/src/app/node_modules/eufy-security-client/build/p2p/session.js:308:26) {
  code: 'ERR_INVALID_ARG_TYPE'
}

**Comment by clownyhobo** [comment]
Same issue here

**Comment by fuatakgun** [comment]
This will be resolved after I update the integration with latest add-on from downstream repository (https://github.com/bropat/eufy-security-ws/), wait for couple of days

**Comment by jamesreid01** [comment]
I'm getting a "Requested verification code for 2FA" error in the log file and an email with an authentication code each time I start (new installation) - will this fix fix that?

**Comment by jamesreid01** [comment]
Ahhh... ok - could you put that in the install notes?
