### ISSUE TITLE
No stations/devices found. 

### ISSUE THREAD

**Issue by tomasenskede** [fuatakgun/eufy_security#489]
I have two T8210 and one Home Base 2 units in my network and My Eufy Addon in HA cant find any... why?

![image](https://user-images.githubusercontent.com/32595351/196055015-0ece7f3c-187b-4c71-b799-66a401d3e075.png)

![image](https://user-images.githubusercontent.com/32595351/196055023-beffb905-69df-4c33-8f56-252afbd3d51c.png)

Please advice how to get this working, thanks!

**Comment by cdnninja** [comment]
https://github.com/fuatakgun/eufy_security/issues/407 MFA isn't supported.

**Comment by tomasenskede** [comment]
MFA?

**Comment by tomasenskede** [comment]
![image](https://user-images.githubusercontent.com/32595351/196120125-418f63fa-2d28-49a7-9db8-3cf4869ddf22.png)

**Comment by tomasenskede** [comment]
I reinstalled Eufy addon and followed the instructions and the log says like this;

With "Country: US" I get:
2022-10-25 08:39:47.212  INFO  Eufy Security server listening on host 0.0.0.0, port 3000 
2022-10-25 08:39:49.740  INFO  No stations found. 
2022-10-25 08:39:50.128  INFO  No devices found. 
2022-10-25 08:39:57.625  INFO  Push notification connection successfully established 

With "Country: Sweden" I get;

Unable to start driver InvalidCountryCodeError: Invalid ISO 3166-1 Alpha-2 country code
    at Function.initialize (/usr/src/app/node_modules/eufy-security-client/build/http/api.js:167:15)
    at EufySecurity._initializeInternals (/usr/src/app/node_modules/eufy-security-client/build/eufysecurity.js:112:40)
    at Function.initialize (/usr/src/app/node_modules/eufy-security-client/build/eufysecurity.js:50:28)
    at /usr/src/app/dist/bin/server.js:52:62
    at Object.<anonymous> (/usr/src/app/dist/bin/server.js:78:3)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)

With "Country: SE" I get:

2022-10-25 08:40:38.112  INFO  Country property changed, invalidate saved cloud token. 
2022-10-25 08:40:38.214  INFO  Eufy Security server listening on host 0.0.0.0, port 3000 

I do have one Eufy HomeBase 2 at 192.168.1.65 in the same LAN as the HA. Isnt the HomeBase 2 supported maybe?

When I log into https://mysecurity.eufylife.com/ with "Sweden" and my credentials I can see my cameras...
![image](https://user-images.githubusercontent.com/32595351/197726863-3dc6eaa9-e40e-412a-b758-a9726c907853.png)

**Comment by fuatakgun** [comment]
At the end of add-on initialization, you should see some logs like this, otherwise, it seems that either country is wrong or devices are not shared `properly` and it is best to remove them and add back again. 

By the way, country codes are expected to be 2 characters, such as `SE` not full name, but I see that you have already tried it.

Until add-on can see devices, there is not much we can do here but @bropat can help here: https://github.com/bropat/eufy-security-ws/
```
2022-11-03 20:19:49.887  INFO  Eufy Security server listening on host 0.0.0.0, port 3000 
2022-11-03 20:19:59.331  INFO  Connected to station T8010N2320460480 on host 78.141.157.96 and port 21647 
2022-11-03 20:20:00.209  INFO  Connected to station T8410P20210912B3 on host 78.141.157.96 and port 15532 
```
