### ISSUE TITLE
New User *Failed on start up*

### ISSUE THREAD

**Issue by umutcelebi** [fuatakgun/eufy_security#528]
Hi,

I just installed the addon and changed the configuration. Country is EU but im getting this error:

Unable to start driver InvalidCountryCodeError: Invalid ISO 3166-1 Alpha-2 country code
    at Function.initialize (/usr/src/app/node_modules/eufy-security-client/build/http/api.js:167:15)
    at EufySecurity._initializeInternals (/usr/src/app/node_modules/eufy-security-client/build/eufysecurity.js:122:40)
    at Function.initialize (/usr/src/app/node_modules/eufy-security-client/build/eufysecurity.js:53:28)
    at /usr/src/app/dist/bin/server.js:52:62
    at Object.<anonymous> (/usr/src/app/dist/bin/server.js:78:3)
    at Module._compile (node:internal/modules/cjs/loader:1155:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1209:10)
    at Module.load (node:internal/modules/cjs/loader:1033:32)
    at Function.Module._load (node:internal/modules/cjs/loader:868:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)

Can anyone help me?

**Comment by umutcelebi** [comment]
Country must be the country and not like US. Fixed
