### ISSUE TITLE
Error thrown with door sensor and Homebase 3

### ISSUE THREAD

**Issue by KyleDoherty1** [fuatakgun/eufy_security#536]
Please check Services, Known Bug / Issues and Troubleshooting over here first: https://github.com/fuatakgun/eufy_security/blob/master/README.md

**Describe the bug**
When door sensor opens or closes an error is thrown in the addon. Could be related to schema change.

Have the new homebase 3. Everything updated.

```
2022-11-18 14:32:40.797  ERROR Station T8030P2_____ - CMD_NOTIFY_PAYLOAD Error: 
{
  error: SyntaxError: Unexpected token  in JSON at position 35
      at JSON.parse (<anonymous>)
      at P2PClientProtocol.handleDataControl (/usr/src/app/node_modules/eufy-security-client/build/p2p/session.js:1416:43)
      at P2PClientProtocol.handleData (/usr/src/app/node_modules/eufy-security-client/build/p2p/session.js:1019:18)
      at P2PClientProtocol.parseDataMessage (/usr/src/app/node_modules/eufy-security-client/build/p2p/session.js:1007:26)
      at P2PClientProtocol.handleMsg (/usr/src/app/node_modules/eufy-security-client/build/p2p/session.js:839:26)
      at Socket.<anonymous> (/usr/src/app/node_modules/eufy-security-client/build/p2p/session.js:1697:56)
      at Socket.emit (node:events:513:28)
      at UDP.onMessage [as onmessage] (node:dgram:930:8),
  payload: '{"cmd":1550,"payload":{"status":1}}\x00'
}
```

**Comment by binarybuddha** [comment]
I am also getting this error on my brand new homebase 3:
2022-12-01 03:31:17.143  ERROR Station {ID}- CMD_NOTIFY_PAYLOAD Error: 
{
  error: SyntaxError: Unexpected token  in JSON at position 35
      at JSON.parse (<anonymous>)
      at P2PClientProtocol.handleDataControl (/usr/src/app/node_modules/eufy-security-client/build/p2p/session.js:1416:43)
      at P2PClientProtocol.handleData (/usr/src/app/node_modules/eufy-security-client/build/p2p/session.js:1019:18)
      at P2PClientProtocol.parseDataMessage (/usr/src/app/node_modules/eufy-security-client/build/p2p/session.js:1007:26)
      at P2PClientProtocol.handleMsg (/usr/src/app/node_modules/eufy-security-client/build/p2p/session.js:839:26)
      at Socket.<anonymous> (/usr/src/app/node_modules/eufy-security-client/build/p2p/session.js:1697:56)
      at Socket.emit (node:events:513:28)
      at UDP.onMessage [as onmessage] (node:dgram:930:8),
  payload: '{"cmd":1550,"payload":{"status":1}}\x00'
}

**Comment by KyleDoherty1** [comment]
@fuatakgun ☝️, still the same here as well.

**Comment by fuatakgun** [comment]
https://github.com/fuatakgun/eufy_security/issues/591

**Comment by fuatakgun** [comment]
@KyleDoherty1 , if you are interested, you can share these devices with me and I can debug.

Or, you can get the Alpha version of integration and see locally.

**Comment by fuatakgun** [comment]
Updates from alpha version;
- door sensor is created (I cannot test if it is reacting)
- home base is also functional (switched between home to disarmed)
![image](https://user-images.githubusercontent.com/11085566/210132031-dffc2c49-4025-47bb-b335-9ebaf76b93f1.png)

![image](https://user-images.githubusercontent.com/11085566/210132037-1705218b-ba83-44ea-aae5-76348373b1b7.png)

**Comment by fuatakgun** [comment]
Did you enable the push notifications for door sensor events?

**Comment by fuatakgun** [comment]
Ah see, please create an issue under eufy-security-ws repository with above error, it needs to be fixed down there
