### ISSUE TITLE
Arm Status unknown - after restart of Home Assistant

### ISSUE THREAD

**Issue by dMopp** [fuatakgun/eufy_security#542]
Since the beginning, I see the following error after fresh starting or restarting home assistant:

```
Nov 22 15:23:00 ulli01 homeassistant[621]: #033[31m2022-11-22 15:23:00.700 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Nov 22 15:23:00 ulli01 homeassistant[621]: Traceback (most recent call last):
Nov 22 15:23:00 ulli01 homeassistant[621]:   File "/config/custom_components/eufy_security/__init__.py", line 60, in update
Nov 22 15:23:00 ulli01 homeassistant[621]:     coordinator.async_set_updated_data(coordinator.data)
Nov 22 15:23:00 ulli01 homeassistant[621]:   File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 313, in async_set_updated_data
Nov 22 15:23:00 ulli01 homeassistant[621]:     self.async_update_listeners()
Nov 22 15:23:00 ulli01 homeassistant[621]:   File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 110, in async_update_listeners
Nov 22 15:23:00 ulli01 homeassistant[621]:     update_callback()
Nov 22 15:23:00 ulli01 homeassistant[621]:   File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 348, in _handle_coordinator_update
Nov 22 15:23:00 ulli01 homeassistant[621]:     self.async_write_ha_state()
Nov 22 15:23:00 ulli01 homeassistant[621]:   File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 545, in async_write_ha_state
Nov 22 15:23:00 ulli01 homeassistant[621]:     self._async_write_ha_state()
Nov 22 15:23:00 ulli01 homeassistant[621]:   File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 583, in _async_write_ha_state
Nov 22 15:23:00 ulli01 homeassistant[621]:     state = self._stringify_state(available)
Nov 22 15:23:00 ulli01 homeassistant[621]:   File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 551, in _stringify_state
Nov 22 15:23:00 ulli01 homeassistant[621]:     if (state := self.state) is None:
Nov 22 15:23:00 ulli01 homeassistant[621]:   File "/config/custom_components/eufy_security/alarm_control_panel.py", line 240, in state
Nov 22 15:23:00 ulli01 homeassistant[621]:     return CODES_TO_STATES[current_mode]
Nov 22 15:23:00 ulli01 homeassistant[621]: KeyError: -1#033[0m
```

My fix is the following automation:

```
alias: Fix Eufy
description: ""
trigger:
  - platform: homeassistant
    event: start
condition: []
action:
  - if:
      - condition: state
        entity_id: alarm_control_panel.hwr_homebase
        state: unavailable
    then:
      - service: eufy_security.alarm_guard_schedule
        data: {}
        target:
          entity_id: alarm_control_panel.hwr_homebase
mode: single
```

The target state and service needs to be adjusted to the wished state.

Maybe this can be fixed somehow different, because the status is unknown until the status changed (or is set again) Might be an issue in the add-on instead of the custom component here, I don't know.

**Comment by Ditskys** [comment]
I also had this issue and wouldn't update via geo profile

**Comment by fuatakgun** [comment]
if you have time, please try alpha version (v5.x.x)

**Comment by fuatakgun** [comment]
https://github.com/fuatakgun/eufy_security/issues/594

**Comment by fuatakgun** [comment]
while I could not find a super great solution, I let alarm control panel to be shown to you with Unknown status.

Please get alpha version of integration, give it a try
