### ISSUE TITLE
Country Code Error?

### ISSUE THREAD

**Issue by dankmanone** [fuatakgun/eufy_security#554]
Trying to setup for the first time, created a 2nd Eufy account with shared permissions. Account is in the "UK" as well. But on load I see the following in the log:

Unable to start driver InvalidCountryCodeError: Invalid ISO 3166-1 Alpha-2 country code
    at Function.initialize (/usr/src/app/node_modules/eufy-security-client/build/http/api.js:167:15)
    at EufySecurity._initializeInternals (/usr/src/app/node_modules/eufy-security-client/build/eufysecurity.js:122:40)
    at Function.initialize (/usr/src/app/node_modules/eufy-security-client/build/eufysecurity.js:53:28)
    at /usr/src/app/dist/bin/server.js:52:62
    at Object.<anonymous> (/usr/src/app/dist/bin/server.js:78:3)
    at Module._compile (node:internal/modules/cjs/loader:1155:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1209:10)
    at Module.load (node:internal/modules/cjs/loader:1033:32)
    at Function.Module._load (node:internal/modules/cjs/loader:868:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)

When changing the country code to "US" in the config, log looks as follows -

2022-11-29 15:37:22.617  INFO  Authentication properties changed, invalidate saved cloud token. 
2022-11-29 15:37:22.725  INFO  Eufy Security server listening on host 0.0.0.0, port 3000 
2022-11-29 15:37:25.483  INFO  No stations found. 
2022-11-29 15:37:25.818  INFO  No devices found. 
2022-11-29 15:37:33.427  INFO  Push notification connection successfully established 

Any ideas?

**Comment by fuatakgun** [comment]
Have you tried GB?

**Comment by dankmanone** [comment]
Of course. I’m an idiot. Thank you. For what it’s worth Eufy refers to the region as United Kingdom not Great Britain thus the assumption on my part. On Nov 29, 2022, at 6:10 PM, Fuat Akgün ***@***.***> wrote:﻿
Have you tried GB?
