### ISSUE TITLE
Error on addon notification switch mode

### ISSUE THREAD

**Issue by Ditskys** [fuatakgun/eufy_security#559]
2022-12-03 19:05:11.565  INFO  Eufy Security server listening on host 0.0.0.0, port 3000 
2022-12-03 19:05:15.651  ERROR Convert Error: 
{
  property: {
    key: 1283,
    name: 'notificationSwitchModeGeofence',
    label: 'Notification Switch Mode Geofence',
    readable: true,
    writeable: true,
    type: 'boolean'
  },
  value: '80',
  error: PropertyNotSupportedError: Property notificationSwitchModeGeofence not supported for station  with software version 1.0.3.8
      at Station.convertRawPropertyValue (/usr/src/app/node_modules/eufy-security-client/build/http/station.js:227:43)
      at Station.updateRawProperty (/usr/src/app/node_modules/eufy-security-client/build/http/station.js:189:65)
      at /usr/src/app/node_modules/eufy-security-client/build/http/station.js:108:22
      at Array.forEach (<anonymous>)
      at Station.update (/usr/src/app/node_modules/eufy-security-client/build/http/station.js:107:36)
      at new Station (/usr/src/app/node_modules/eufy-security-client/build/http/station.js:62:14)
      at Function.initialize (/usr/src/app/node_modules/eufy-security-client/build/http/station.js:73:25)
      at EufySecurity.handleHubs (/usr/src/app/node_modules/eufy-security-client/build/eufysecurity.js:360:51)
      at HTTPApi.<anonymous> (/usr/src/app/node_modules/eufy-security-client/build/eufysecurity.js:126:44)
      at HTTPApi.emit (node:events:513:28)
}
2022-12-03 19:05:15.672  ERROR Convert Error: 
{
  property: {
    key: 1283,
    name: 'notificationSwitchModeApp',
    label: 'Notification Switch Mode App',
    readable: true,
    writeable: true,
    type: 'boolean'
  },
  value: '80',
  error: PropertyNotSupportedError: Property notificationSwitchModeApp not supported for station  with software version 1.0.3.8
      at Station.convertRawPropertyValue (/usr/src/app/node_modules/eufy-security-client/build/http/station.js:232:43)
      at Station.updateRawProperty (/usr/src/app/node_modules/eufy-security-client/build/http/station.js:189:65)
      at /usr/src/app/node_modules/eufy-security-client/build/http/station.js:108:22
      at Array.forEach (<anonymous>)
      at Station.update (/usr/src/app/node_modules/eufy-security-client/build/http/station.js:107:36)
      at new Station (/usr/src/app/node_modules/eufy-security-client/build/http/station.js:62:14)
      at Function.initialize (/usr/src/app/node_modules/eufy-security-client/build/http/station.js:73:25)
      at EufySecurity.handleHubs (/usr/src/app/node_modules/eufy-security-client/build/eufysecurity.js:360:51)
      at HTTPApi.<anonymous> (/usr/src/app/node_modules/eufy-security-client/build/eufysecurity.js:126:44)
      at HTTPApi.emit (node:events:513:28)
}
2022-12-03 19:05:15.681  ERROR Convert Error: 
{
  property: {
    key: 1283,
    name: 'notificationSwitchModeKeypad',
    label: 'Notification Switch Mode Keypad',
    readable: true,
    writeable: true,
    type: 'boolean'
  },
  value: '80',
  error: PropertyNotSupportedError: Property notificationSwitchModeKeypad not supported for station with software version 1.0.3.8
      at Station.convertRawPropertyValue (/usr/src/app/node_modules/eufy-security-client/build/http/station.js:237:43)
      at Station.updateRawProperty (/usr/src/app/node_modules/eufy-security-client/build/http/station.js:189:65)
      at /usr/src/app/node_modules/eufy-security-client/build/http/station.js:108:22
      at Array.forEach (<anonymous>)
      at Station.update (/usr/src/app/node_modules/eufy-security-client/build/http/station.js:107:36)
      at new Station (/usr/src/app/node_modules/eufy-security-client/build/http/station.js:62:14)
      at Function.initialize (/usr/src/app/node_modules/eufy-security-client/build/http/station.js:73:25)
      at EufySecurity.handleHubs (/usr/src/app/node_modules/eufy-security-client/build/eufysecurity.js:360:51)
      at HTTPApi.<anonymous> (/usr/src/app/node_modules/eufy-security-client/build/eufysecurity.js:126:44)
      at HTTPApi.emit (node:events:513:28)
}
2022-12-03 19:05:21.855  INFO  Connected to station on host 192.168.0.20 and port 25459 
2022-12-03 19:05:21.883  INFO  Connected to station  on host 192.168.0.41 and port 18572 
2022-12-03 19:05:22.280  INFO  Push notification connection successfully established 
2022-12-03 19:06:03.336  INFO  Client disconnected with ip: 172.30.32.1 port: 55890 code: 1000 reason: Normal Closure 
2022-12-03 19:06:21.420  INFO  Client disconnected with ip: 172.30.32.1 port: 55832 code: 1000 reason: Normal Closure 
2022-12-03 19:06:44.487  INFO  Client disconnected with ip: 172.30.32.1 port: 59536 code: 1000 reason: Normal Closure

**Comment by Ditskys** [comment]
This seems to be stopping the integration from loading as get an error "Retrying setup: Start Listening was not completed in timely manner"

**Comment by fuatakgun** [comment]
I could not be helpful much here, please raise an issue under eufy-security-ws reposiroty
