### ISSUE TITLE
No Cloud snapshot

### ISSUE THREAD

**Issue by dewoert** [fuatakgun/eufy_security#567]
Since yesterday the cloud snapshot from my T8210 doesn't show anymore in HA.
On the phone app it is still visible.
Streaming video from the doorbell is working fine.

I saw that there was an update on the HomeBase2 a few days ago, perhaps that has something to do with is ?

Rebooted Doorbell, HomeBase2 and HA, but still no cloud snapshot.

Tried to find a logfile with erros, but can't find detailed logging 

```
2022-12-10 06:34:18.270  INFO  Connected to station T8010P2321383BDE on host 192.168.2.68 and port 17881 
2022-12-10 06:35:22.088  INFO  Disconnected from station T8010P2321383BDE 
2022-12-10 06:35:27.752  INFO  Connected to station T8010P2321383BDE on host 192.168.2.68 and port 28484 
2022-12-10 06:37:09.942  INFO  Disconnected from station T8010P2321383BDE 
2022-12-10 06:37:15.490  INFO  Connected to station T8010P2321383BDE on host 192.168.2.68 and port 19724

```
(The cloud snapshot also doesn't work on the HomeBridge plugin that was also working till yesterday)

**Comment by lankymat** [comment]
Hi,

I have started to have trouble with this too. I have added the log entry which seems to be linked to the issue below.  It occurred a couple of times yesterday and I restarted the integration which seemed to fix it for a short time but it seems to be happening quite regularly. 


```
This error originated from a custom integration.

Logger: homeassistant.helpers.script.websocket_api_script
Source: custom_components/eufy_security/camera.py:435
Integration: Eufy Security (documentation, issues)
First occurred: 18:29:39 (8 occurrences)
Last logged: 18:45:44

websocket_api script: Error executing script. Unexpected error for call_service at pos 1: T8010P232105162B~/media/mmcblk0p1/video/20221210165648_c00.jpg
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 451, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 684, in _async_call_service_step
    await service_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1744, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1781, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 208, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 678, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 943, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 715, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/components/camera/__init__.py", line 909, in async_handle_snapshot_service
    image = await camera.async_camera_image()
  File "/config/custom_components/eufy_security/camera.py", line 435, in async_camera_image
    async with async_get_clientsession(self.coordinator.hass).get(
  File "/usr/local/lib/python3.10/site-packages/aiohttp/client.py", line 1138, in __aenter__
    self._resp = await self._coro
  File "/usr/local/lib/python3.10/site-packages/aiohttp/client.py", line 507, in _request
    req = self._request_class(
  File "/usr/local/lib/python3.10/site-packages/aiohttp/client_reqrep.py", line 305, in __init__
    self.update_host(url)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/client_reqrep.py", line 366, in update_host
    raise InvalidURL(url)
aiohttp.client_exceptions.InvalidURL: T8010P232105162B~/media/mmcblk0p1/video/20221210165648_c00.jpg
```

**Comment by Adrian-Harris** [comment]
I strongly suspect that this is a change made by eufy in response to these criticisms https://www.zdnet.com/home-and-office/smart-home/eufy-responds-to-security-concerns/

since yesterday, I also noticed that there are no thumbnails in https://mysecurity.eufylife.com, which suggests to me that there are no thumbnails to retrieve.

**Comment by stanogustafik** [comment]
The same issue... no thumbnail or even snapshot, stream works properly. The change occurred after the homebase firmware upgrade today morning...

**Comment by Beer17HWAM** [comment]
Same here. I guess it's over with the thumbnail option. :-(

**Comment by Menz01** [comment]
same issue here as well, however mine is just slightly different (i think)..
1) on my PC when i go to my HA there is no thumbnail in the dashboard and when i click it to stream, the box opens but no video is shown, no errors either, just no video. the video box will open for a second and will be black and then the box will just disappear
2) on my phone when i use the HA companion app, still no thumbnail on the dashboard like my PC, however, unlike my PC when i click the box the video will stream

**Comment by Beer17HWAM** [comment]
I have exactly the same. Streaming on Android is working but all the thumbnails are gone.

**Comment by martijnpoppen** [comment]
I noticed the same for the Homey integration. See: https://github.com/bropat/eufy-security-client/issues/273

**Comment by on4ami** [comment]
Same here

**Comment by LonelyNoah** [comment]
Still the same problem here. Live streaming works completely fine, but the thumbnail gets removed whenever it stops.

**Comment by fuatakgun** [comment]
https://github.com/fuatakgun/eufy_security/issues/569
