### ISSUE TITLE
No picture or live stream anymore - since last week - other options of the integration works well

### ISSUE THREAD

**Issue by jboesh** [fuatakgun/eufy_security#580]
the integration works on my Home Assistant, I can use all the options that come with it, but I can't see a picture or (live stream) video of the doorbell.
this has always worked until a week ago...
Ive seen some of the recent issues and added a new environment value (my phone model):
- TRUSTED_DEVICE_NAME=SM-G996B/DS

but this doesn't seem to be the solution

What I see in the logging:
```
19-12-2022 10:48:54
2022-12-19 09:48:54.204  INFO  Push notification connection closed 
19-12-2022 10:48:59
2022-12-19 09:48:59.726  INFO  Push notification connection successfully established 
19-12-2022 13:26:32
2022-12-19 12:26:31.971  INFO  Client disconnected with ip: 172.29.40.1 port: 41924 code: 1006 reason: Abnormal Closure 
19-12-2022 13:26:32
2022-12-19 12:26:31.972  INFO  Client disconnected with ip: 172.29.40.1 port: 41600 code: 1006 reason: Abnormal Closure 
19-12-2022 13:26:32
2022-12-19 12:26:31.973  INFO  Client disconnected with ip: 172.29.40.1 port: 42304 code: 1006 reason: Abnormal Closure 
19-12-2022 13:26:32
```

What I see in the Home Assistant logging:
```
2022-12-19 15:49:45.203 ERROR (MainThread) [homeassistant.components.camera] Error requesting stream: camera.deurbel does not support play stream service
2022-12-19 15:49:48.914 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 433, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 222, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 81, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 236, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 136, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/camera/__init__.py", line 724, in get
    return await self.handle(request, camera)
  File "/usr/src/homeassistant/homeassistant/components/camera/__init__.py", line 764, in handle
    stream = await camera.handle_async_mjpeg_stream(request)
  File "/config/custom_components/eufy_security/camera.py", line 458, in handle_async_mjpeg_stream
    await stream.close()
  File "/usr/local/lib/python3.10/site-packages/haffmpeg/core.py", line 158, in close
    await self._loop.run_in_executor(None, _close)
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.10/site-packages/haffmpeg/core.py", line 153, in _close
    self._proc.stdin.write(b"q")
BrokenPipeError: [Errno 32] Broken pipe

```

Screenshot of the options page:
![image](https://user-images.githubusercontent.com/71582854/208454840-fa608520-53c9-4963-a645-294c59a71d05.png)

**Comment by zadigre** [comment]
I didn't check my log yet... but I have the same problem... no pictures of the camera. 
but today, I cannot arm/disarm cameras. This was working fine 1-2 days ago.

**Comment by wimb0** [comment]
Same issue here.
No weird things in the logfiles.

**Comment by sythesigh** [comment]
I have no image. If I click through I still get the video stream fine, but it will not display an image preview at all. 
![68C99CFB-53BB-4B7F-9203-D84DEBFD7F8C](https://user-images.githubusercontent.com/107685183/208686893-6f7f7c4d-ab70-47a4-a251-17d3772ab325.jpeg)

**Comment by on4ami** [comment]
Same issue here

**Comment by Zeunas** [comment]
Someone hinted that could actually be related with the privacy issues Eufy been criticised of https://github.com/fuatakgun/eufy_security/issues/567#issuecomment-1345406950 . In fact very recently they have updated their app to add a disclaimer related to the thumbnail for the notification which needs to be temporarily stored in the cloud.

**Comment by jboesh** [comment]
> Someone hinted that could actually be related with the privacy issues Eufy been criticised of [#567 (comment)](https://github.com/fuatakgun/eufy_security/issues/567#issuecomment-1345406950) . In fact very recently they have updated their app to add a disclaimer related to the thumbnail for the notification which needs to be temporarily stored in the cloud.

in my case it's not just the thumbnail, also no video wants to play from the doorbell anymore.  but it could indeed be related.

**Comment by alanizat** [comment]
12/23/2022
I am seeing same issue here.
No picture for any on my 2K indoor security cams.
Also,no feed when I click on the camera tile.
No changes made to my specific setup, but I have been updating HA available.

Love Eufy cameras, but specifically went with them as they were shown to be reliable in HAnuse cases!

Integration reports:
Retrying setup: Start Listening was not completed in timely manner
Repeats hundreds of times in the log files.

**Comment by jboesh** [comment]
Now the integration has stopped working too. The message: Retrying setup: Start Listening was not completed in timely manner

I will disable the integration for now

**Comment by kongo09** [comment]
With the latest update of the add-on, the integration starts working again. But not the camera stream

**Comment by fuatakgun** [comment]
merging into https://github.com/fuatakgun/eufy_security/issues/567
