### ISSUE TITLE
HOME ASSISTANT INTEGRATION STOP WORKING

### ISSUE THREAD

**Issue by multinet33** [fuatakgun/eufy_security#596]
Hello

I've updated eufy security add hone and restarted Home assistant and I get this error 👍 
Logger: homeassistant.config_entries
Source: custom_components/eufy_security/eufy_security_api/camera.py:132
Integration: Eufy Security ([documentation](https://github.com/fuatakgun/eufy_security), [issues](https://github.com/fuatakgun/eufy_security/issues))
First occurred: 23:03:35 (1 occurrences)
Last logged: 23:03:35

Error setting up entry 127.0.0.1 for eufy_security
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 372, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/eufy_security/__init__.py", line 45, in async_setup_entry
    await coordinator.initialize()
  File "/config/custom_components/eufy_security/coordinator.py", line 39, in initialize
    await self.api.connect()
  File "/config/custom_components/eufy_security/eufy_security_api/api_client.py", line 66, in connect
    await self._set_products()
  File "/config/custom_components/eufy_security/eufy_security_api/api_client.py", line 123, in _set_products
    self.devices = await self._get_product(ProductType.device, result[MessageField.STATE.value]["devices"])
  File "/config/custom_components/eufy_security/eufy_security_api/api_client.py", line 141, in _get_product
    product = Camera(self, serial_no, properties, metadata, commands)
  File "/config/custom_components/eufy_security/eufy_security_api/camera.py", line 35, in __init__
    self.set_stream_prodiver(StreamProvider.P2P)
  File "/config/custom_components/eufy_security/eufy_security_api/camera.py", line 132, in set_stream_prodiver
    url = url.replace("{server_address}", str(self.config.rtsp_server_address))
AttributeError: 'NoneType' object has no attribute 'rtsp_server_address'

Any help ?

**Comment by fuatakgun** [comment]
thanks for testing new version, please try with 5.1.0 version

**Comment by fuatakgun** [comment]
resolving now, will open these back soon
