### ISSUE TITLE
6.0.0 Update broke the alarm panel card and automations

### ISSUE THREAD

**Issue by WvanWaas** [fuatakgun/eufy_security#645]
With updating Eufy to 6.0.0 the Alarm Panel Card has stopped working. I'm also missing my alarm_control_panel.<alarm name> entity

Alarm Panel Card Configuration
No matching entities found

1. Install 6.0.0 via HACS
2. Try to find alarm_control_panel

1. Install 6.0.0 via HACS
2. Add Alarm Panel Card Configuration

**Expected behavior**

I want my control card back and I would like to know my alarm state for the type: picture-elements card I am using.

- Home Assistant 2022.12.9
- Supervisor 2022.12.1
- Operating System 9.4
- Home Assistant Core Version: 2022.12.9
- Frontend 20221213.1 - latest

- Live Streaming Protocol (RTSP/P2P): 

- Debug Logs from Home Assistant (https://github.com/fuatakgun/eufy_security/discussions/624)
`Logger: homeassistant.components.alarm_control_panel
Source: custom_components/eufy_security/alarm_control_panel.py:166
Integration: Alarm control panel ([documentation](https://www.home-assistant.io/integrations/alarm_control_panel), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+alarm_control_panel%22))
First occurred: 10:40:19 AM (6 occurrences)
Last logged: 2:09:37 PM

Error adding entities for domain alarm_control_panel with platform eufy_security
Error while setting up eufy_security platform for alarm_control_panel
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 428, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 692, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 789, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 545, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 583, in _async_write_ha_state
    state = self._stringify_state(available)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 551, in _stringify_state
    if (state := self.state) is None:
  File "/config/custom_components/eufy_security/alarm_control_panel.py", line 166, in state
    return CurrentModeToStateValue[CurrentModeToState(current_mode).name].value
  File "/usr/local/lib/python3.10/enum.py", line 385, in __call__
    return cls.__new__(cls, value)
  File "/usr/local/lib/python3.10/enum.py", line 710, in __new__
    raise ve_exc
ValueError: 6 is not a valid CurrentModeToState`

`Logger: homeassistant
Source: custom_components/eufy_security/alarm_control_panel.py:166
Integration: Eufy Security ([documentation](https://github.com/fuatakgun/eufy_security), [issues](https://github.com/fuatakgun/eufy_security/issues))
First occurred: 10:50:19 AM (16 occurrences)
Last logged: 1:27:07 PM

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 168, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 316, in _async_refresh
    self.async_update_listeners()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 121, in async_update_listeners
    update_callback()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 381, in _handle_coordinator_update
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 545, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 583, in _async_write_ha_state
    state = self._stringify_state(available)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 551, in _stringify_state
    if (state := self.state) is None:
  File "/config/custom_components/eufy_security/alarm_control_panel.py", line 166, in state
    return CurrentModeToStateValue[CurrentModeToState(current_mode).name].value
  File "/usr/local/lib/python3.10/enum.py", line 385, in __call__
    return cls.__new__(cls, value)
  File "/usr/local/lib/python3.10/enum.py", line 710, in __new__
    raise ve_exc
ValueError: 6 is not a valid CurrentModeToState`

**Comment by fuatakgun** [comment]
thanks, fix is merged, either wait for new version or get latest from master

**Comment by fuatakgun** [comment]
https://github.com/fuatakgun/eufy_security/commit/0ce1349e874d73f3eff715e8eef99fb822c1b93c

**Comment by sagilo** [comment]
@fuatakgun which version should this be fixed in?
I'm running 6.1.0 and my doorbell status isn't working as well
I can set the mode and it updates correctly, but the sensors values are "unknown"

![Screenshot_20230105-082806~2](https://user-images.githubusercontent.com/5019344/210716202-690439a2-7750-479f-a3c5-9d458ca87dee.png)

**Comment by fuatakgun** [comment]
Yours is a different problem. It was not created at all, you are saying that, it is always unknown.

Are you sure you have enabled notifications for `Switch modes` in eufy app? Without it, you won't get updates

**Comment by sagilo** [comment]
@fuatakgun I don't see any notification setting for the mode switch. 
I also didn't find it in the readme 
Can you please point me to it?

**Comment by fuatakgun** [comment]
Readme says that `enable all notifications because integration relies on it`.

I have this;

![Screenshot_2023-01-05-09-04-24-858_com.oceanwing.battery.cam.jpg](https://user-images.githubusercontent.com/11085566/210731221-e875a543-4444-4148-ab27-b4fc517409fa.jpg)

**Comment by fuatakgun** [comment]
**As we already called out earlier, add-on heavily relies on push notifications, so you must enable all kind of push notifications (motion detected, person detected, lock events, alarm events etc) in your mobile app. These notifications are not user based but device based so after enabling all these notifications, your main account will probably bloated with many push notifications. In android, there is a setting to disable specific notifications, please use it. **

**Comment by sagilo** [comment]
@fuatakgun my pan&tilt camera has a "mode switch" notification toggle but the doorbell doesn't. (model T8200, firmware is up to date, so is the android app)
Should I file a separate issue?

![image](https://user-images.githubusercontent.com/5019344/210736080-6c1973ad-0d1d-480c-9b79-b5ebf0238238.png)

**Comment by fuatakgun** [comment]
Yes, because, this issue was about having no alarm panel card

**Comment by fuatakgun** [comment]
New template will ask you to fill additional fields, i need them

**Comment by spaceboy76** [comment]
Still not working for me. Both devices show as unavailable and was working before the update

**Comment by fuatakgun** [comment]
Logs please @spaceboy76 or didn't happen :-)

**Comment by spaceboy76** [comment]
On mobile at present but I see this in the HA logs. The add on appears to be working fine

This error originated from a custom integration.

Logger: custom_components.eufy_security
Source: custom_components/eufy_security/eufy_security_api/web_socket_client.py:84 
Integration: Eufy Security (documentation, issues) 
First occurred: 10:13:47 (25 occurrences) 
Last logged: 12:13:47

Unexpected error fetching eufy_security data:
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 225, in _async_refresh
    self.data = await self._async_update_data()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 181, in _async_update_data
    return await self.update_method()
  File "/config/custom_components/eufy_security/coordinator.py", line 81, in _update_local
    await self._api.poll_refresh()
  File "/config/custom_components/eufy_security/eufy_security_api/api_client.py", line 381, in poll_refresh
    await self._send_message_get_response(OutgoingMessage(command_type, command=command))
  File "/config/custom_components/eufy_security/eufy_security_api/api_client.py", line 366, in _send_message_get_response
    await self.send_message(message.content)
  File "/config/custom_components/eufy_security/eufy_security_api/api_client.py", line 375, in send_message
    await self._client.send_message(json.dumps(message))
  File "/config/custom_components/eufy_security/eufy_security_api/web_socket_client.py", line 84, in send_message
    raise WebSocketConnectionError()
custom_components.eufy_security.eufy_security_api.exceptions.WebSocketConnectionError

**Comment by fuatakgun** [comment]
this is a log for a broken state, I need logs from initial startup and I need logs, not only error statements, check issue template for log generation

**Comment by WvanWaas** [comment]
Had the same issue again at 6.1.0 removed the device and reloaded with logs

Fixed with reload no idea why but it's working again.

At first had an error like this: (I hope it helps for others)
Logger: homeassistant.components.alarm_control_panel
Source: custom_components/eufy_security/alarm_control_panel.py:165
Integration: Alarm control panel ([documentation](https://www.home-assistant.io/integrations/alarm_control_panel), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+alarm_control_panel%22))
First occurred: 3:18:26 PM (4 occurrences)
Last logged: 3:24:50 PM

Error adding entities for domain alarm_control_panel with platform eufy_security
Error while setting up eufy_security platform for alarm_control_panel
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 438, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 709, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 804, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 556, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 597, in _async_write_ha_state
    state = self._stringify_state(available)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 562, in _stringify_state
    if (state := self.state) is None:
  File "/config/custom_components/eufy_security/alarm_control_panel.py", line 165, in state
    return CurrentModeToStateValue[CurrentModeToState.DISARMED].value
  File "/usr/local/lib/python3.10/enum.py", line 440, in __getitem__
    return cls._member_map_[name]
KeyError: <CurrentModeToState.DISARMED: 63>

**Comment by fuatakgun** [comment]
wow, what a simple mistake :( 

please get latest code from master or wait for next version release

**Comment by spaceboy76** [comment]
should i just remove and re-add the integration then?

**Comment by WvanWaas** [comment]
I can confirm this fix works! Thanks @fuatakgun
