### ISSUE TITLE
Camera control using the service eufy_security.send_message

### ISSUE THREAD

**Issue by DivanX10** [fuatakgun/eufy_security#71]
As I understand it, you can use the hijack_security.send_message service to control the camera, but you need to use JSON for this. Could you give examples of how to properly use the service to control the camera?

In particular, I am interested in PTZ control, LED on/off, human tracking on/off, volume control.

For example, I can look at json in iobroker, but I don't understand how to properly insert uefi_security.send_message into the service to turn something on or off.

![image](https://user-images.githubusercontent.com/64090632/135890049-f4a1e849-239f-4957-8517-bff6646624e3.png)
![image](https://user-images.githubusercontent.com/64090632/135900312-59d98b00-2cc7-48db-b4e1-cfcadb281eb7.png)

**Comment by fuatakgun** [comment]
Please replace serial number & values and try out below.  I have shared only 4 different examples, but, you can find out the rest using the documentation from this page (https://github.com/bropat/eufy-security-ws#device-level-commands).

One warning: we are still using version 0.3.3, as there are some problems with latest version in terms of web-sockets. You will not be able to play with newest features until I solve the issues and migrate to new version.

`message_id` is used for tracking purposes, you are not required to put anything there.

- Enable/Disable Camera
```
service: eufy_security.send_message
data:
  message: >-
    {
      "messageId": "message_id_do_not_add_value_here", 
      "command": "device.enable_device",
      "serialNumber": "YOUR_SERIAL_NUMBER_GOES_HERE", 
      "value": true
    }
```

- Enable/Disable Status LED
```
service: eufy_security.send_message
data:
  message: >-
    {
      "messageId": "message_id_do_not_add_value_here", 
      "command": "device.set_status_led",
      "serialNumber": "YOUR_SERIAL_NUMBER_GOES_HERE", 
      "value": true
    }
```

- Enable/Disable Motion Detection
```
service: eufy_security.send_message
data:
  message: >-
    {
      "messageId": "message_id_do_not_add_value_here", 
      "command": "device.set_motion_detection",
      "serialNumber": "YOUR_SERIAL_NUMBER_GOES_HERE", 
      "value": true
    }
```

- Enable/Disable Sound Detection
```
service: eufy_security.send_message
data:
  message: >-
    {
      "messageId": "message_id_do_not_add_value_here", 
      "command": "device.set_sound_detection",
      "serialNumber": "YOUR_SERIAL_NUMBER_GOES_HERE", 
      "value": true
    }
```

**Comment by DivanX10** [comment]
Not everything can be turned on in the camera. Below is a list and examples of what works and what doesn't work
Camera LED - works
```
service: eufy_security.send_message
data:
  message: |-
    {
      "messageId": "message_id_do_not_add_value_here", 
      "command": "device.set_status_led",
      "serialNumber": "T8410PXXX", 
      "value": 
         {%- set led = states("input_boolean.eufy_camera_hall_led") %}
         {%- if led == 'on' %} true
         {% else %} false
         {% endif %}
    }
```
Camera Power - works
```
service: eufy_security.send_message
data:
  message: |-
    {
      "messageId": "message_id_do_not_add_value_here", 
      "command": "device.set_status_led",
      "serialNumber": "T8410PXXX", 
      "value":
         {%- set led = states("input_boolean.eufy_camera_hall_power") %}
         {%- if led == 'on' %} true
         {% else %} false
         {% endif %}
    }
```

Camera Motion Tracking - does not work
```
service: eufy_security.send_message
data:
  message: |-
    {
      "messageId": "message_id_do_not_add_value_here", 
      "command": "device.set_motion_tracking",
      "serialNumber": "T8410PXXX", 
      "value":
         {%- set led = states("input_boolean.eufy_camera_hall_motion_tracking") %}
         {%- if led == 'on' %} true
         {% else %} false
         {% endif %}
    }
```

I have made automation that enables or disables a particular function. So far , only work: Camera LED and Camera Power
```
alias: Camera Control
description: ''
trigger:
  - platform: state
    entity_id: input_boolean.eufy_camera_hall_led
    id: Camera LED
  - platform: state
    entity_id: input_boolean.eufy_camera_hall_power
    id: Camera Power
  - platform: state
    entity_id: input_boolean.eufy_camera_hall_motion_tracking
    id: Camera Motion Tracking
condition: []
action:
  - choose:
      - conditions:
          - condition: trigger
            id: Camera LED
        sequence:
          - service: eufy_security.send_message
            data:
              message: |-
                {
                  "messageId": "message_id_do_not_add_value_here", 
                  "command": "device.set_status_led",
                  "serialNumber": "T8410PXXX", 
                  "value":
                     {%- set led = states("input_boolean.eufy_camera_hall_led") %}
                     {%- if led == 'on' %} true
                     {% else %} false
                     {% endif %}
                }
      - conditions:
          - condition: trigger
            id: Camera Power
        sequence:
          - service: eufy_security.send_message
            data:
              message: |-
                {
                  "messageId": "message_id_do_not_add_value_here", 
                  "command": "device.enable_device",
                  "serialNumber": "T8410PXXX", 
                  "value":
                     {%- set led = states("input_boolean.eufy_camera_hall_power") %}
                     {%- if led == 'on' %} true
                     {% else %} false
                     {% endif %}
                }
      - conditions:
          - condition: trigger
            id: Camera Motion Tracking
        sequence:
          - service: eufy_security.send_message
            data:
              message: |-
                {
                  "messageId": "message_id_do_not_add_value_here", 
                  "command": "device.set_motion_tracking",
                  "serialNumber": "T8410PXXX", 
                  "value":
                     {%- set led = states("input_boolean.eufy_camera_hall_motion_tracking") %}
                     {%- if led == 'on' %} true
                     {% else %} false
                     {% endif %}
                }
    default: []
mode: parallel
max: 10
```

**Comment by bropat** [comment]
@DivanX10 This should work:

```
service: eufy_security.send_message
data:
  message: |-
    {
      "messageId": "cmdMotionTracking", 
      "command": "device.set_property",
      "serialNumber": "T8410XXX",
      "name": "motionTracking",
      "value":
         {%- set led = states("input_boolean.eufy_camera_hall_motion_tracking") %}
         {%- if led == 'on' %} true
         {% else %} false
         {% endif %}
    }
```

**Comment by DivanX10** [comment]
Hooray, it worked🥳.  So, now we need to figure out the rest of the functions. Camera control via PTZ


```
{
  "type": "state",
  "common": {
    "name": "Tilt Up",
    "type": "boolean",
    "role": "button.start",
    "read": false,
    "write": true
  },
  "native": {},
  "from": "system.adapter.eufy-security.0",
  "user": "system.user.admin",
  "ts": 1633523418618,
  "_id": "eufy-security.0.T8410XXX.cameras.T8410XXX.tilt_up"
}
```

**Comment by DivanX10** [comment]
And it worked 🥳. So, how do I change the volume level?

```
{
  "type": "state",
  "common": {
    "name": "Speaker Volume",
    "type": "number",
    "role": "value",
    "read": true,
    "write": true,
    "min": 0,
    "max": 100
  },
  "native": {
    "key": 1230,
    "name": "speakerVolume",
    "timestamp": 1630530476000
  },
  "from": "system.adapter.eufy-security.0",
  "user": "system.user.admin",
  "ts": 1633523418567,
  "_id": "eufy-security.0.T8410XXX.cameras.T8410XXX.speaker_volume"
} 
```

**Comment by DivanX10** [comment]
I can't call the service if I use input_number. The error "Failed to call the eufy_security.send_message. Unknown error" pops up

```
service: eufy_security.send_message
data:
  message: |-
    {
      "messageId": "cmdspeakerVolume", 
      "command": "device.set_property",
      "serialNumber": "T8410XXX",
      "name": "speakerVolume",
      "value": {{ states("input_number.eufy_camera_hall_speaker_volume")|round }}
    }
```

If I specify only digits instead of input_number, then it works. How do I use input_number?
```
service: eufy_security.send_message
data:
  message: |-
    {
      "messageId": "cmdspeakerVolume", 
      "command": "device.set_property",
      "serialNumber": "T8410XXX",
      "name": "speakerVolume",
      "value": 100
    }
```



```
Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/eufy_security/websocket.py:103
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 01:19:00 (3 occurrences)
Last logged: 01:20:48


[140538598935712] Error handling message: Unknown error
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 26, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 525, in handle_execute_script
    await script_obj.async_run(msg.get("variables"), context=context)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 1219, in async_run
    await asyncio.shield(run.async_run())
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 353, in async_run
    await self._async_step(log_exceptions=False)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 371, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 571, in _async_call_service_step
    await service_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1491, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1526, in _execute_service
    await handler.job.target(service_call)
  File "/config/custom_components/eufy_security/__init__.py", line 28, in async_handle_send_message
    await coordinator.async_send_message(message)
  File "/config/custom_components/eufy_security/coordinator.py", line 234, in async_send_message
    await self.ws.send_message(message)
  File "/config/custom_components/eufy_security/websocket.py", line 103, in send_message
    await self.ws.send_str(message)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client_ws.py", line 149, in send_str
    raise TypeError("data argument must be str (%r)" % type(data))
TypeError: data argument must be str (<class 'homeassistant.helpers.template.gen_result_wrapper.<locals>.Wrapper'>)
```

**Comment by DivanX10** [comment]
How do I reboot the camera? So it does not work to reboot

```
service: eufy_security.send_message
data:
  message: |-
    {
     "messageId": "string", 
     "command": "device.reboot",
     "serialNumber": "T8410XXXX",
    }

```

**Comment by DivanX10** [comment]
The camera control panel is assembled using integration [multiple-entity-row](https://github.com/benct/lovelace-multiple-entity-row).  Not all functions are listed here yet.


![image](https://user-images.githubusercontent.com/64090632/136478345-cacada0e-c491-4d8c-8061-72423f19c4b5.png)

```
type: entities
entities:
  - entity: input_boolean.eufy_camera_hall_power
    show_state: false
    toggle: false
    name: Camera Control
    type: custom:multiple-entity-row
    icon: mdi:camera
    entities:
      - entity: ''
        name: Down
        type: button
        tap_action:
          action: call-service
          service: eufy_security.send_message
          service_data:
            message: |-
              {
                "messageId": "cmd Pan And Tilt Down", 
                "command": "device.pan_and_tilt",
                "serialNumber": "T8410XXXXX",
                "direction": 3
              }
        icon: mdi:camera-control
      - entity: ''
        name: Left
        type: button
        tap_action:
          action: call-service
          service: eufy_security.send_message
          service_data:
            message: |-
              {
               "messageId": "cmd Pan And Tilt Left", 
               "command": "device.pan_and_tilt",
               "serialNumber": "T8410XXXXX",
               "direction": 1
              }
        icon: mdi:camera-control
      - entity: ''
        name: Right
        type: button
        tap_action:
          action: call-service
          service: eufy_security.send_message
          service_data:
            message: |-
              {
                "messageId": "cmd Pan And Tilt Right", 
                "command": "device.pan_and_tilt",
                "serialNumber": "T8410XXXXX",
                "direction": 2
              }
        icon: mdi:camera-control
      - entity: ''
        name: Up
        type: button
        tap_action:
          action: call-service
          service: eufy_security.send_message
          service_data: null
          message: |-
            {
              "messageId": "cmd Pan And Tilt Up", 
              "command": "device.pan_and_tilt",
              "serialNumber": "T8410XXXXX",
              "direction": 4
            }
        icon: mdi:camera-control
  - entity: input_boolean.eufy_camera_hall_power
    name: Camera
    show_state: true
    toggle: true
  - entity: input_boolean.eufy_camera_hall_led
    name: LED
  - entity: input_boolean.eufy_camera_hall_auto_nightvision
    name: Auto Nightvision
  - entity: input_boolean.eufy_camera_hall_motion_tracking
    name: Motion Tracking
  - entity: input_boolean.eufy_camera_hall_motion_detection
    name: Motion Detection
title: Camera
show_header_toggle: false
state_color: true

```

**Comment by bropat** [comment]
> How do I reboot the camera? So it does not work to reboot
> 
> ```
> service: eufy_security.send_message
> data:
>   message: |-
>     {
>      "messageId": "string", 
>      "command": "device.reboot",
>      "serialNumber": "T8410XXXX",
>     }
> ```

```
service: eufy_security.send_message
data:
  message: |-
    {
     "messageId": "string", 
     "command": "station.reboot",
     "serialNumber": "T8410XXXX",
    }
```

**Comment by SmartM-ui** [comment]
Hi @DivanX10 
I was looking at how to sync the settings imparted by the eufy app to Home Assistant.
I have enabled additional binary sensors (e.g. motion tracking): https://github.com/fuatakgun/eufy_security/issues/62#issuecomment-937319169 and then, taking a cue from this topic, I created the boolean inputs for the sensors of interest.
However, I have seen that the switches report the correct data only if the data is sent from Home Assistant to the cam.

To overcome, in addition to your automation, I created these other two, in order to position the switch as per app eufy:

```
  - id: eufy_motion_tracking_off_binary_sensor_off
    alias: eufy_motion_tracking_off_binary_sensor_off
    description: ''
    mode: single
    trigger:
      - platform: state
        entity_id: binary_sensor.salone_motion_tracking
        from: 'True'
        to: 'False'
    condition: []
    action:
      - service: input_boolean.turn_off
        target:
          entity_id: input_boolean.eufy_camera_salotto_motion_tracking

  - id: eufy_motion_tracking_on_binary_sensor_on
    alias: eufy_motion_tracking_on_binary_sensor_on
    description: ''
    mode: single
    trigger:
      - platform: state
        entity_id: binary_sensor.salone_motion_tracking
        from: 'False'
        to: 'True'
    condition: []
    action:
      - service: input_boolean.turn_on
        target:
          entity_id: input_boolean.eufy_camera_salotto_motion_tracking
```
In this way the switches, after 10 minutes of waiting provided by the add-on to get the status from the eufy app, you get the correct status of the switch.

Forcing the refresh of the update service:

```
service: eufy_security.send_message
date:
  message: | -
    {
      "messageId": "message_id_do_not_add_value_here",
      "command": "driver.poll_refresh"
    }
```
you can get the status in real time, without waiting for the 10 minute wait provided by Eufy. (I would like to force the update every time I view the Home Assistant page where the cam switches are present).

Try to see if you can find a better solution

**Comment by DivanX10** [comment]
> > How do I reboot the camera? So it does not work to reboot
> > ```
> > service: eufy_security.send_message
> > data:
> >   message: |-
> >     {
> >      "messageId": "string", 
> >      "command": "device.reboot",
> >      "serialNumber": "T8410XXXX",
> >     }
> > ```
> 
> ```
> service: eufy_security.send_message
> data:
>   message: |-
>     {
>      "messageId": "string", 
>      "command": "station.reboot",
>      "serialNumber": "T8410XXXX",
>     }
> ```

it doesn't work, and if I click in the iobroker itself, it works fine there

```
{
  "type": "state",
  "common": {
    "name": "Reboot station",
    "type": "boolean",
    "role": "button.start",
    "read": false,
    "write": true
  },
  "native": {},
  "from": "system.adapter.eufy-security.0",
  "user": "system.user.admin",
  "ts": 1633523418116,
  "_id": "eufy-security.0.T8410XXXX.station.reboot"
}
```

**Comment by fuatakgun** [comment]
So, I am resolving this, @DivanX10 can you create an issue to track a feature request as `standardized way of calling set functions`
