### ISSUE TITLE
Door Sensors Always Report Closed

### ISSUE THREAD

**Issue by BillyFKidney** [fuatakgun/eufy_security#730]
**Describe the bug**

All door sensors report closed, despite Eufy showing them opening and closing. This may be related to the [MaxListeners](https://github.com/fuatakgun/eufy_security/discussions/698#discussion-4772934) issue _but_ this warning no longer appears in the logs.

![8F421947-3732-47EA-AA8F-60C706E726C2_1_105_c](https://user-images.githubusercontent.com/65253277/217326976-1ef6c0b6-6ba7-41c1-a489-ca3a0a55efde.jpeg)
![AEE9CDF3-164F-4A46-9A4E-DA26FA02769E_1_105_c](https://user-images.githubusercontent.com/65253277/217326990-4a48eabf-fdf9-4569-99db-7cf40367cc57.jpeg)

**Additional information**

Go to Settings -> System -> Repairs -> Click on 3 dots (...) -> System Information and get Version and Installation Type to below fields;
- Home Assistant Installation Type (OS - Supvervised - Core): OS
- Home Assistant Core Version: 2023.1.7
- Eufy Security Add-on Version: 1.3.0
- Eufy Security Integration Version: 6.2.0

<img width="1713" alt="image" src="https://user-images.githubusercontent.com/65253277/217327531-8347955a-668f-492a-b015-6211d3cd0ea6.png">

**Comment by KillaDreams** [comment]
Same, very frustrating and I've been unable to figure it working for a few months now

**Comment by ANDuff** [comment]
Same for me, while the alarm is in off mode. I can see this in the logs and it corresponds with opening/closing of the doors, plus the status of 1 vs 0 would make sense for open/close: 

`2023-02-28 17:02:41.427  ERROR Station <STATION ID> - CMD_NOTIFY_PAYLOAD Error: 
{
  error: SyntaxError: Unexpected token  in JSON at position 35
      at JSON.parse (<anonymous>)
      at P2PClientProtocol.handleDataControl (/usr/src/app/node_modules/eufy-security-client/build/p2p/session.js:1450:43)
      at P2PClientProtocol.handleData (/usr/src/app/node_modules/eufy-security-client/build/p2p/session.js:1043:18)
      at P2PClientProtocol.parseDataMessage (/usr/src/app/node_modules/eufy-security-client/build/p2p/session.js:1031:26)
      at P2PClientProtocol.handleMsg (/usr/src/app/node_modules/eufy-security-client/build/p2p/session.js:868:26)
      at Socket.<anonymous> (/usr/src/app/node_modules/eufy-security-client/build/p2p/session.js:1732:56)
      at Socket.emit (node:events:513:28)
      at UDP.onMessage [as onmessage] (node:dgram:930:8),
  payload: '{"cmd":1550,"payload":{"status":1}}\x00'
}
2023-02-28 17:02:51.219  ERROR Station <STATION ID> - CMD_NOTIFY_PAYLOAD Error: 
{
  error: SyntaxError: Unexpected token  in JSON at position 35
      at JSON.parse (<anonymous>)
      at P2PClientProtocol.handleDataControl (/usr/src/app/node_modules/eufy-security-client/build/p2p/session.js:1450:43)
      at P2PClientProtocol.handleData (/usr/src/app/node_modules/eufy-security-client/build/p2p/session.js:1043:18)
      at P2PClientProtocol.parseDataMessage (/usr/src/app/node_modules/eufy-security-client/build/p2p/session.js:1031:26)
      at P2PClientProtocol.handleMsg (/usr/src/app/node_modules/eufy-security-client/build/p2p/session.js:868:26)
      at Socket.<anonymous> (/usr/src/app/node_modules/eufy-security-client/build/p2p/session.js:1732:56)
      at Socket.emit (node:events:513:28)
      at UDP.onMessage [as onmessage] (node:dgram:930:8),
  payload: '{"cmd":1550,"payload":{"status":0}}\x00'
}`

**Comment by ANDuff** [comment]
It seems that a fix for this is in progress: https://github.com/bropat/eufy-security-ws/issues/192

**Comment by ginge78** [comment]
The error is not reported in version 1.3.4, but when running with the debug on the command is not processed.

DEBUG [P2PClientProtocol.handleDataControl] Station T8010NXXXXXXXXXX - CMD_NOTIFY_PAYLOAD - Not implemented 
{
  commandIdName: 'CMD_ENTRY_SENSOR_STATUS',
  commandId: 1550,
  message: '{"cmd":1550,"payload":{"status":1}}\x00'
}

**Comment by KillaDreams** [comment]
Still not fix, hasn't been a fix

**Comment by gboxxx** [comment]
Same issue here.

**Comment by fliespl** [comment]
@ginge78 i was digging into it today, but failed to find one crucial info for it to be useful - device id that triggered "open/close" event.

If I am right the only solution is to use this cmd as trigger to do full sync of all sensors and update states of them using properties data. Still it only makes sense with limited amt of sensors.

**Comment by NotCarr** [comment]
+1

**Comment by KillaDreams** [comment]
This was ACTUALLY FIXED on bropats repo

**Comment by fliespl** [comment]
I think Eufy becomes somehow unreliable lately after their security issues.

I have started having problems in eufy app:
- I get open event notification (randomly), but no closed event after that,
- Events screen shows info one out of 20 times (most of the time I get no events, but after refreshing a few times it loads),
- Basement door sensor changes state randomly (new battery, proper setup - was working fine for 3 years).

That could also be a reason why many people report errors.

**Comment by KillaDreams** [comment]
https://github.com/bropat/eufy-security-ws/releases/tag/1.3.5 once this update was installed door sensors status started working again I only use @fuatakgun version for HACS https://github.com/fuatakgun/eufy_security

**Comment by fuatakgun** [comment]
Thanks for sharing the updates @KillaDreams

**Comment by fliespl** [comment]
Just a sidenote, if someone else struggles. I had a long conversation with Eufy Team about sensor issues (even within the app) whole April & part of may. They did push quite a few firmware test updates on my end and it finally started to behave normally.

So if you ever notice strange things happening in the Eufy app (in my case I had push notifications about door open, but never closed, notification about motion, but it was never recorded in history log) it's worth "pushing" them for a fix.
