### ISSUE TITLE
Unexpected error fetching eufy_security data:

### ISSUE THREAD

**Issue by tempus2016** [fuatakgun/eufy_security#733]
Please check existing (open or closed) issues before creating a new one. (https://github.com/fuatakgun/eufy_security/issues?q=is%3Aissue+)

If this is not an issue, you can use `Discussions` (https://github.com/fuatakgun/eufy_security/discussions) section.

**Describe the bug**

Unexpected error fetching eufy_security data:

**To reproduce**

**Expected behavior**

**Additional information**

Go to Settings -> System -> Repairs -> Click on 3 dots (...) -> System Information and get Version and Installation Type to below fields;
- Home Assistant Installation Type (OS - Supvervised - Core): HAOS
- Home Assistant Core Version: 2023.2.3
- Eufy Security Add-on Version: 1.3.0
- Eufy Security Integration Version: 6.2.0

Hardware Information;
- Camera Model: 2K Doorbell

- Live Streaming Protocol (RTSP/P2P): 

- Debug Logs from Home Assistant (https://github.com/fuatakgun/eufy_security/discussions/624)
- ```
This error originated from a custom integration.

Logger: custom_components.eufy_security
Source: custom_components/eufy_security/eufy_security_api/web_socket_client.py:86
Integration: Eufy Security (documentation, issues)
First occurred: 00:20:46 (201 occurrences)
Last logged: 11:22:59

Unexpected error fetching eufy_security data:
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 239, in _async_refresh
    self.data = await self._async_update_data()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 195, in _async_update_data
    return await self.update_method()
  File "/config/custom_components/eufy_security/coordinator.py", line 85, in _update_local
    await self._api.poll_refresh()
  File "/config/custom_components/eufy_security/eufy_security_api/api_client.py", line 160, in poll_refresh
    await self._send_message_get_response(OutgoingMessage(OutgoingMessageType.poll_refresh))
  File "/config/custom_components/eufy_security/eufy_security_api/api_client.py", line 343, in _send_message_get_response
    await self.send_message(message.content)
  File "/config/custom_components/eufy_security/eufy_security_api/api_client.py", line 352, in send_message
    await self._client.send_message(json.dumps(message))
  File "/config/custom_components/eufy_security/eufy_security_api/web_socket_client.py", line 86, in send_message
    raise WebSocketConnectionError()
custom_components.eufy_security.eufy_security_api.exceptions.WebSocketConnectionError
```

- Logs from Eufy Security Add-on (either from Add-ons page of Home Assistant or Docker output):
- ```
2023-02-09 10:30:56.537  INFO  Disconnected from station T8010P232124193A 
2023-02-09 10:31:01.593  INFO  Connected to station T8010P232124193A on host 192.168.1.109 and port 15510 
2023-02-09 10:32:05.729  INFO  Disconnected from station T8010P232124193A 
2023-02-09 10:32:10.801  INFO  Connected to station T8010P232124193A on host 192.168.1.109 and port 29424 
2023-02-09 10:33:14.922  INFO  Disconnected from station T8010P232124193A 
2023-02-09 10:33:19.973  INFO  Connected to station T8010P232124193A on host 192.168.1.109 and port 19291 
2023-02-09 10:34:24.097  INFO  Disconnected from station T8010P232124193A 
2023-02-09 10:34:29.152  INFO  Connected to station T8010P232124193A on host 192.168.1.109 and port 18493 
2023-02-09 10:35:33.261  INFO  Disconnected from station T8010P232124193A 
2023-02-09 10:35:38.317  INFO  Connected to station T8010P232124193A on host 192.168.1.109 and port 27711 
2023-02-09 10:36:42.405  INFO  Disconnected from station T8010P232124193A 
2023-02-09 10:36:47.461  INFO  Connected to station T8010P232124193A on host 192.168.1.109 and port 11232 
2023-02-09 10:37:51.605  INFO  Disconnected from station T8010P232124193A 
2023-02-09 10:37:56.655  INFO  Connected to station T8010P232124193A on host 192.168.1.109 and port 11085 
2023-02-09 10:39:00.763  INFO  Disconnected from station T8010P232124193A 
2023-02-09 10:39:05.993  INFO  Connected to station T8010P232124193A on host 192.168.1.109 and port 16121 
2023-02-09 10:40:10.092  INFO  Disconnected from station T8010P232124193A 
2023-02-09 10:40:15.146  INFO  Connected to station T8010P232124193A on host 192.168.1.109 and port 26404 
2023-02-09 10:41:19.237  INFO  Disconnected from station T8010P232124193A 
2023-02-09 10:41:24.286  INFO  Connected to station T8010P232124193A on host 192.168.1.109 and port 19526 
2023-02-09 10:42:28.380  INFO  Disconnected from station T8010P232124193A 
2023-02-09 10:42:33.441  INFO  Connected to station T8010P232124193A on host 192.168.1.109 and port 27338 
2023-02-09 10:43:37.541  INFO  Disconnected from station T8010P232124193A 
2023-02-09 10:43:42.591  INFO  Connected to station T8010P232124193A on host 192.168.1.109 and port 22541 
2023-02-09 10:44:46.529  INFO  Disconnected from station T8010P232124193A 
2023-02-09 10:44:51.591  INFO  Connected to station T8010P232124193A on host 192.168.1.109 and port 18624 
2023-02-09 10:45:55.481  INFO  Disconnected from station T8010P232124193A 
2023-02-09 10:46:00.539  INFO  Connected to station T8010P232124193A on host 192.168.1.109 and port 13012 
2023-02-09 10:47:04.644  INFO  Disconnected from station T8010P232124193A 
2023-02-09 10:47:09.699  INFO  Connected to station T8010P232124193A on host 192.168.1.109 and port 12670 
2023-02-09 10:48:13.805  INFO  Disconnected from station T8010P232124193A 
2023-02-09 10:48:18.857  INFO  Connected to station T8010P232124193A on host 192.168.1.109 and port 12141 
2023-02-09 10:49:22.793  INFO  Disconnected from station T8010P232124193A 
2023-02-09 10:49:27.854  INFO  Connected to station T8010P232124193A on host 192.168.1.109 and port 14774 
2023-02-09 10:50:31.960  INFO  Disconnected from station T8010P232124193A 
2023-02-09 10:50:37.008  INFO  Connected to station T8010P232124193A on host 192.168.1.109 and port 21335 
2023-02-09 10:51:41.130  INFO  Disconnected from station T8010P232124193A 
2023-02-09 10:51:46.191  INFO  Connected to station T8010P232124193A on host 192.168.1.109 and port 23931 
2023-02-09 10:52:50.288  INFO  Disconnected from station T8010P232124193A 
2023-02-09 10:52:55.346  INFO  Connected to station T8010P232124193A on host 192.168.1.109 and port 15936 
2023-02-09 10:53:59.453  INFO  Disconnected from station T8010P232124193A 
2023-02-09 10:54:04.500  INFO  Connected to station T8010P232124193A on host 192.168.1.109 and port 18845 
2023-02-09 10:55:08.421  INFO  Disconnected from station T8010P232124193A 
2023-02-09 10:55:13.479  INFO  Connected to station T8010P232124193A on host 192.168.1.109 and port 24230 
2023-02-09 10:56:17.373  INFO  Disconnected from station T8010P232124193A 
2023-02-09 10:56:22.424  INFO  Connected to station T8010P232124193A on host 192.168.1.109 and port 15876 
2023-02-09 10:57:26.316  INFO  Disconnected from station T8010P232124193A 
2023-02-09 10:57:31.368  INFO  Connected to station T8010P232124193A on host 192.168.1.109 and port 15467 
2023-02-09 10:58:35.476  INFO  Disconnected from station T8010P232124193A 
2023-02-09 10:58:40.536  INFO  Connected to station T8010P232124193A on host 192.168.1.109 and port 20334 
2023-02-09 10:59:44.476  INFO  Disconnected from station T8010P232124193A 
2023-02-09 10:59:49.535  INFO  Connected to station T8010P232124193A on host 192.168.1.109 and port 19934 
2023-02-09 11:00:53.864  INFO  Disconnected from station T8010P232124193A 
2023-02-09 11:00:58.917  INFO  Connected to station T8010P232124193A on host 192.168.1.109 and port 18288 
2023-02-09 11:02:03.011  INFO  Disconnected from station T8010P232124193A 
2023-02-09 11:02:08.077  INFO  Connected to station T8010P232124193A on host 192.168.1.109 and port 20927 
2023-02-09 11:03:12.208  INFO  Disconnected from station T8010P232124193A 
2023-02-09 11:03:17.259  INFO  Connected to station T8010P232124193A on host 192.168.1.109 and port 19755 
2023-02-09 11:04:21.368  INFO  Disconnected from station T8010P232124193A 
2023-02-09 11:04:26.414  INFO  Connected to station T8010P232124193A on host 192.168.1.109 and port 16586 
2023-02-09 11:05:30.541  INFO  Disconnected from station T8010P232124193A 
2023-02-09 11:05:35.598  INFO  Connected to station T8010P232124193A on host 192.168.1.109 and port 16157 
2023-02-09 11:06:39.520  INFO  Disconnected from station T8010P232124193A 
2023-02-09 11:06:44.570  INFO  Connected to station T8010P232124193A on host 192.168.1.109 and port 17839 
2023-02-09 11:07:48.476  INFO  Disconnected from station T8010P232124193A 
2023-02-09 11:07:53.535  INFO  Connected to station T8010P232124193A on host 192.168.1.109 and port 28482 
2023-02-09 11:08:57.435  INFO  Disconnected from station T8010P232124193A 
2023-02-09 11:09:02.490  INFO  Connected to station T8010P232124193A on host 192.168.1.109 and port 15175 
2023-02-09 11:10:06.615  INFO  Disconnected from station T8010P232124193A 
2023-02-09 11:10:11.851  INFO  Connected to station T8010P232124193A on host 192.168.1.109 and port 18134 
2023-02-09 11:11:15.731  INFO  Disconnected from station T8010P232124193A 
2023-02-09 11:11:20.793  INFO  Connected to station T8010P232124193A on host 192.168.1.109 and port 20364 
2023-02-09 11:12:24.709  INFO  Disconnected from station T8010P232124193A 
2023-02-09 11:12:29.770  INFO  Connected to station T8010P232124193A on host 192.168.1.109 and port 12204 
2023-02-09 11:13:33.851  INFO  Disconnected from station T8010P232124193A 
2023-02-09 11:13:38.905  INFO  Connected to station T8010P232124193A on host 192.168.1.109 and port 28456 
2023-02-09 11:13:58.177  INFO  Push notification connection closed 
2023-02-09 11:14:03.764  INFO  Push notification connection successfully established 
2023-02-09 11:14:43.031  INFO  Disconnected from station T8010P232124193A 
2023-02-09 11:14:48.099  INFO  Connected to station T8010P232124193A on host 192.168.1.109 and port 20342 
2023-02-09 11:15:52.197  INFO  Disconnected from station T8010P232124193A 
2023-02-09 11:15:57.248  INFO  Connected to station T8010P232124193A on host 192.168.1.109 and port 21906 
2023-02-09 11:17:01.367  INFO  Disconnected from station T8010P232124193A 
2023-02-09 11:17:06.430  INFO  Connected to station T8010P232124193A on host 192.168.1.109 and port 27244 
2023-02-09 11:18:10.519  INFO  Disconnected from station T8010P232124193A 
2023-02-09 11:18:15.575  INFO  Connected to station T8010P232124193A on host 192.168.1.109 and port 11593 
2023-02-09 11:19:19.671  INFO  Disconnected from station T8010P232124193A 
2023-02-09 11:19:24.741  INFO  Connected to station T8010P232124193A on host 192.168.1.109 and port 19605 
2023-02-09 11:20:28.819  INFO  Disconnected from station T8010P232124193A 
2023-02-09 11:20:33.871  INFO  Connected to station T8010P232124193A on host 192.168.1.109 and port 27078 
2023-02-09 11:21:37.975  INFO  Disconnected from station T8010P232124193A 
2023-02-09 11:21:43.032  INFO  Connected to station T8010P232124193A on host 192.168.1.109 and port 27620 
2023-02-09 11:22:47.372  INFO  Disconnected from station T8010P232124193A 
2023-02-09 11:22:52.431  INFO  Connected to station T8010P232124193A on host 192.168.1.109 and port 11088 
2023-02-09 11:23:56.532  INFO  Disconnected from station T8010P232124193A 
2023-02-09 11:24:01.596  INFO  Connected to station T8010P232124193A on host 192.168.1.109 and port 20373 
2023-02-09 11:25:05.713  INFO  Disconnected from station T8010P232124193A 
2023-02-09 11:25:10.786  INFO  Connected to station T8010P232124193A on host 192.168.1.109 and port 26871 
2023-02-09 11:26:14.847  INFO  Disconnected from station T8010P232124193A 
2023-02-09 11:26:19.895  INFO  Connected to station T8010P232124193A on host 192.168.1.109 and port 21161 
```

- Would you share your device with me in case further debugging required? (Yes/No): 

**Additional context**

Add any other context about the problem goes here.

**Comment by mattheeussen** [comment]
i have the same issue, updated everything but no differance.

**Comment by MPowerData** [comment]
same problem here, anyone found a solution for this?

**Comment by 5olu7ion** [comment]
I get the exact same messages in the HomeAssistant Logs, but I don't see **corresponding** disconnection issues in eufy-security-ws container:
![image](https://user-images.githubusercontent.com/113297102/231101088-ac95ea9a-edc2-42e2-9d37-e884e764125b.png)
![IMG_0191](https://user-images.githubusercontent.com/113297102/231103267-6c6667eb-b53d-4be3-9a65-dfe8b2f176b6.jpeg)

**Comment by saschachina** [comment]
I have got the same issue

**Comment by Gennapium** [comment]
Same issue overhere.

**Comment by GentleGiantSoftware** [comment]
Same issue here.

**Comment by Nusserdt** [comment]
Same issue. Updated everything (Addon V 1.5.2) works for 30 min, then error occurs:

**
![image](https://github.com/fuatakgun/eufy_security/assets/35678990/3b4f00a8-6468-4d66-ab4b-9d8648972f84)
**

**Comment by ZerdaFawkes** [comment]
I am having the same issue, but it is not even working for 30min for me. I have an automation to reload the addon when the locks show unavailable and it triggers every 5-15min.

**Comment by fuatakgun** [comment]
I am working on a bug fix to restart to add-on if integration gets disconnected from it.

**Comment by fuatakgun** [comment]
please give a try with latest version
