### ISSUE TITLE
Error during setup of component eufy

### ISSUE THREAD

**Issue by cmjennnings21** [fuatakgun/eufy_security#750]
I've had this error appear, probably a month or so back. I did have an issue with not being able to connect to cameras so reinstalled the module, but the setup error remained. This is the log file associated

Logger: homeassistant.setup
Source: components/eufy/__init__.py:61
First occurred: 18:07:56 (1 occurrences)
Last logged: 18:07:56

Error during setup of component eufy
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 256, in _async_setup_component
    result = await task
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/components/eufy/__init__.py", line 61, in setup
    data = lakeside.get_devices(
  File "/usr/local/lib/python3.10/site-packages/lakeside/__init__.py", line 39, in get_devices
    token = r.json()['access_token']
KeyError: 'access_token'

Does this mean anything to anyone and can it be fixed?

**Comment by fuatakgun** [comment]
This is an issue coming from eufy component of home assistant core, nothing about this custom integration. Ask help on home assistant community.

**Comment by CatalinGB** [comment]
Hi *,

I had the same issue and the fix, at least for me, was quite stupid.
I've changed the credentials in homeassistant/secrets.yaml from ' ' to " ".
