### ISSUE TITLE
ECONNREFUSED when setting up.

### ISSUE THREAD

**Issue by bakeronline** [fuatakgun/eufy_security#765]
i am trying to setup Eufy for the first time but seem to be getting an error wen i add it.  the ip address seems to be that of my router instead of the homebase.  

i use an Eero router which i try and block everything i can for my smart home.  does anyone know what i need to add to the whitelist to enable this integration to work?  everything seems fine if i have no filtering enabled.

Unable to start driver RequestError: connect ECONNREFUSED 192.168.4.1:443
    at ClientRequest.<anonymous> (/usr/src/app/node_modules/got/dist/source/core/index.js:970:111)
    at Object.onceWrapper (node:events:628:26)
    at ClientRequest.emit (node:events:525:35)
    at ClientRequest.origin.emit (/usr/src/app/node_modules/@szmarczak/http-timer/dist/source/index.js:43:20)
    at TLSSocket.socketErrorListener (node:_http_client:494:9)
    at TLSSocket.emit (node:events:513:28)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1278:16) {
  code: 'ECONNREFUSED',
  timings: {
    start: 1678555676807,
    socket: 1678555676808,
    lookup: 1678555676808,
    connect: undefined,
    secureConnect: undefined,
    upload: undefined,
    response: undefined,
    end: undefined,
    error: 1678555676810,
    abort: undefined,
    phases: {
      wait: 1,
      dns: 0,
      tcp: undefined,
      tls: undefined,
      request: undefined,
      firstByte: undefined,
      download: undefined,
      total: 3
    }
  }
}

**Comment by fuatakgun** [comment]
I would go and ask help on community forum, this is not an issue
