### ISSUE TITLE
Regular Reports in HA for FailedCommandException When Turning on Livestream

### ISSUE THREAD

**Issue by Colorado4Wheeler** [fuatakgun/eufy_security#783]
Please check existing (open or closed) issues before creating a new one. (https://github.com/fuatakgun/eufy_security/issues?q=is%3Aissue+)

If this is not an issue, you can use `Discussions` (https://github.com/fuatakgun/eufy_security/discussions) section.

**Describe the bug**

Whenever I try to force my doorbell to start the livestream I get an error.  I have some triggers that tell the livestream to begin and use the "Start Live Stream over P2P" service to start the stream.  I do this because another action in the flow is to notify my SecuritySpy that the RTSP feed is live and can be recorded.  Even though Eufy captures the video proprietarily, I also record it on my house security camera system because I can broadcast that anywhere in my house, whereas the Eufy stream is only viewable on their apps.

The live stream DOES start, everything DOES work fine, but this error persists in my logs.

**To reproduce**

1. Execute the service for "Start Live Stream over P2P" (developer, trigger, etc)

**Expected behavior**

No error if it worked :)

**Additional information**

Go to Settings -> System -> Repairs -> Click on 3 dots (...) -> System Information and get Version and Installation Type to below fields;
- Home Assistant Installation Type (OS - Supvervised - Core): Core
- Home Assistant Core Version: 2023.4.2
- Eufy Security Add-on Version: Latest (no HACS update available, can't determine the installed version)
- Eufy Security Integration Version:

Hardware Information;
- Camera Model: T8213 Dual Doorbell

- Live Streaming Protocol (RTSP/P2P): 
P2P

- Debug Logs from Home Assistant (https://github.com/fuatakgun/eufy_security/discussions/624)
```Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 452, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 685, in _async_call_service_step
    await service_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1820, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1857, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 809, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 798, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 977, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 838, in _handle_entity_call
    await result
  File "/config/custom_components/eufy_security/camera.py", line 175, in _start_livestream
    if await self.product.start_livestream() is False:
  File "/config/custom_components/eufy_security/eufy_security_api/camera.py", line 143, in start_livestream
    await self.api.start_livestream(self.product_type, self.serial_no)
  File "/config/custom_components/eufy_security/eufy_security_api/api_client.py", line 226, in start_livestream
    await self._send_message_get_response(OutgoingMessage(OutgoingMessageType.start_livestream, serial_no=serial_no))
  File "/config/custom_components/eufy_security/eufy_security_api/api_client.py", line 345, in _send_message_get_response
    return await future
custom_components.eufy_security.eufy_security_api.exceptions.FailedCommandException: {'type': 'result', 'success': False, 'messageId': 'device.start_livestream.c52d2c7a20a147ad9bbd52ec7ad3ad40', 'errorCode': 'device_livestream_already_running'}```

- Logs from Eufy Security Add-on (either from Add-ons page of Home Assistant or Docker output):


- Would you share your device with me in case further debugging required? (Yes/No): 


**Additional context**

Add any other context about the problem goes here.

**Comment by fuatakgun** [comment]
you are probably trying to start the live stream on a camera, which is already running and this is an expected error.
