### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by eranvana** [fuatakgun/eufy_security#798]
hello
I have Eufy Doorbell and I installed eufy-security-ws and everything worked great.
Yesterday I removed the and reinstalled and the integration just doesn't connect.
What did I do wrong?
Please help me to
![346631821_1905646443146933_1923380603464623070_n](https://github.com/fuatakgun/eufy_security/assets/25964123/3249066f-06f8-4a46-9d13-9bbc7ed29d1f)
![346324042_1222325821767670_2115166428458746403_n](https://github.com/fuatakgun/eufy_security/assets/25964123/6e09421e-0358-4e70-8aa1-df8abc76a0b2)
![346331896_970991400921028_9021021547933964800_n](https://github.com/fuatakgun/eufy_security/assets/25964123/1f4337d8-f146-4007-b6a7-ee2b81a9d743)
![345611688_635464201312551_2172202772124321311_n](https://github.com/fuatakgun/eufy_security/assets/25964123/17daade9-d24b-4a2e-b5d6-adc1adc902c9)
![346590837_245831544694308_3772604993585645830_n](https://github.com/fuatakgun/eufy_security/assets/25964123/f037acc0-8b37-4775-a91a-6a6c7223cf56)
 install successfully
Thanks

**Comment by 0R2YPsALXTVed6y** [comment]
Same here

**Comment by StijnQ** [comment]
Same here

**Comment by kdill00** [comment]
try unchecking then rechecking the ffmpeg logs button.  Or just leave it unchecked.  That has worked for in the past.

**Comment by c0nt4x** [comment]
+1 on the above about unchecking the FFMPEG because that worked for me with a Eufy camera but, I'm also having an issue with integrating the Eufy doorbell since I got it 2 days ago. Unchecking the FFMPEG doesn't resolve it for me in this case.

**Comment by itaysp** [comment]
Same here.

**Comment by dewoert** [comment]
+1

**Comment by fuatakgun** [comment]
@dewoert please move into bropat's version of add-on (Current version: 1.5.2)

**Comment by itaysp** [comment]
After update to 6.3.0 with bropat's 1.5.2
`
This error originated from a custom integration.

Logger: homeassistant.config_entries
Source: custom_components/eufy_security/eufy_security_api/api_client.py:350
Integration: Eufy Security (documentation, issues)
First occurred: 07:07:28 (1 occurrences)
Last logged: 07:07:28

Error setting up entry 127.0.0.1 for eufy_security
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/eufy_security/__init__.py", line 50, in async_setup_entry
    await coordinator.initialize()
  File "/config/custom_components/eufy_security/coordinator.py", line 39, in initialize
    await self._api.connect()
  File "/config/custom_components/eufy_security/eufy_security_api/api_client.py", line 73, in connect
    await self._set_products()
  File "/config/custom_components/eufy_security/eufy_security_api/api_client.py", line 100, in _set_products
    result = await self._start_listening()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/eufy_security/eufy_security_api/api_client.py", line 147, in _start_listening
    return await self._send_message_get_response(OutgoingMessage(OutgoingMessageType.start_listening))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/eufy_security/eufy_security_api/api_client.py", line 350, in _send_message_get_response
    return await future
           ^^^^^^^^^^^^
asyncio.exceptions.CancelledError
`
I get verification code in the mail but I don't have where to put it because the integration fails

**Comment by fuatakgun** [comment]
Please follow #795

**Comment by dewoert** [comment]
> @dewoert please move into bropat's version of add-on (Current version: 1.5.2)

Removed and installed the bropat add-on, and that working now.
Only left with issue with the true/false in the RTSP stream.
Looking into that issue now. Saw allready other info about it.

**Comment by fuatakgun** [comment]
I do not have a solution for true/false in config window, please manually update `/config/.storage/core.config_entries` file carefully.
