### ISSUE TITLE
Person / Motion detected not working anymore

### ISSUE THREAD

**Issue by MarshallRDC** [fuatakgun/eufy_security#801]
**Describe the bug**

Hello,

Since a couple of weeks I don't get the person/motion detected visible in HA anymore. Rtsp stream still works but my automation based on person/motion detection was not working anymore.

I've updated tot latest version but no improvement.

**Aditional Information**

Home Assistant OS : on raspberry pi 3
Eufy security integration : v6.2.0
Add-on: eufy-security-ws v1.5.2
Home Assistant 2023.4.6 
Supervisor 2023.04.1 
Operating System 10.1 
Frontend-versie: 20230411.1 - latest 

**Hardware information**

HAOS runnning on RPi 3
Eufy Cam 2
Eufy Pan/Tilt indoor cam
Eufy Homebase 2

**Configuration**

![afbeelding](https://github.com/fuatakgun/eufy_security/assets/14992567/87cd958a-61b0-4541-bc49-4051a0a8c0bf)
![afbeelding](https://github.com/fuatakgun/eufy_security/assets/14992567/b875ff15-a34a-43da-8a3e-a51e522c9d56)

**Logs**

```
Deze fout is ontstaan door een aangepaste integratie.

Logger: custom_components.eufy_security
Source: custom_components/eufy_security/eufy_security_api/web_socket_client.py:86
Integration: Eufy Security (documentation, issues)
First occurred: 23:30:33 (1 occurrences)
Last logged: 23:30:33

Unexpected error fetching eufy_security data:
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 250, in _async_refresh
    self.data = await self._async_update_data()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 206, in _async_update_data
    return await self.update_method()
  File "/config/custom_components/eufy_security/coordinator.py", line 85, in _update_local
    await self._api.poll_refresh()
  File "/config/custom_components/eufy_security/eufy_security_api/api_client.py", line 160, in poll_refresh
    await self._send_message_get_response(OutgoingMessage(OutgoingMessageType.poll_refresh))
  File "/config/custom_components/eufy_security/eufy_security_api/api_client.py", line 343, in _send_message_get_response
    await self.send_message(message.content)
  File "/config/custom_components/eufy_security/eufy_security_api/api_client.py", line 352, in send_message
    await self._client.send_message(json.dumps(message))
  File "/config/custom_components/eufy_security/eufy_security_api/web_socket_client.py", line 86, in send_message
    raise WebSocketConnectionError()
custom_components.eufy_security.eufy_security_api.exceptions.WebSocketConnectionError

``` 

If more info is needed I can provide.

Thank you.

BR,
Robin

**Comment by fuatakgun** [comment]
https://github.com/fuatakgun/eufy_security/issues/803
