### ISSUE TITLE
Issue running eufy_security plug-in after installation.

### ISSUE THREAD

**Issue by JimboJamez** [fuatakgun/eufy_security#802]
Hi there

I have Home Assistant installed on my Synology NAS and am trying to integrate my Eufy cameras. I have installed the eufy-security-ws  add-on and configured it using the following settings, as per the directions on the [Eufy Security](https://github.com/fuatakgun/eufy_security) repo:

![image](https://github.com/fuatakgun/eufy_security/assets/25968238/6e7f591b-1480-444c-9961-d6ef1ff923ac)

I have also checked the configuration on the settings > devices & services page and can see the following:

![image](https://github.com/fuatakgun/eufy_security/assets/25968238/9ac553d1-51f2-4fd6-b2c3-10d3399d6f35)

When I start or reload the add-on, it stays on the "Initializing" stage for a few minutes, then errors,

![image](https://github.com/fuatakgun/eufy_security/assets/25968238/0335f61a-f922-400a-9841-6c6cb8f71ab6)

The error I am getting in the logs is below.

**Describe the bug**

This error originated from a custom integration.

Logger: homeassistant.config_entries
Source: custom_components/eufy_security/eufy_security_api/api_client.py:345
Integration: Eufy Security (documentation, issues)
First occurred: 1:10:09 AM (1 occurrences)
Last logged: 1:10:09 AM

Error setting up entry 127.0.0.1 for eufy_security
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/eufy_security/__init__.py", line 50, in async_setup_entry
    await coordinator.initialize()
  File "/config/custom_components/eufy_security/coordinator.py", line 39, in initialize
    await self._api.connect()
  File "/config/custom_components/eufy_security/eufy_security_api/api_client.py", line 73, in connect
    await self._set_products()
  File "/config/custom_components/eufy_security/eufy_security_api/api_client.py", line 100, in _set_products
    result = await self._start_listening()
  File "/config/custom_components/eufy_security/eufy_security_api/api_client.py", line 145, in _start_listening
    return await self._send_message_get_response(OutgoingMessage(OutgoingMessageType.start_listening))
  File "/config/custom_components/eufy_security/eufy_security_api/api_client.py", line 345, in _send_message_get_response
    return await future
asyncio.exceptions.CancelledError

**Additional information**

- Live Streaming Protocol (RTSP/P2P): RTSP

- Logs from Eufy Security Add-on (either from Add-ons page of Home Assistant or Docker output): [home-assistant_eufy_security_2023-05-20T14-56-33.553Z.log](https://github.com/fuatakgun/eufy_security/files/11522606/home-assistant_eufy_security_2023-05-20T14-56-33.553Z.log)

- Would you share your device with me in case further debugging required? Yes

Thanks in advance

**Comment by JimboJamez** [comment]
Closing as this is a duplicate of #795
