### ISSUE TITLE
Failing to load integration: Schema incompatible error in logs

### ISSUE THREAD

**Issue by ShayGus** [fuatakgun/eufy_security#812]
Integration fails to load on 6.3, works when reverted to 6.2
There's an error in the logs:

`This error originated from a custom integration.

Logger: homeassistant.config_entries
Source: custom_components/eufy_security/eufy_security_api/api_client.py:350
Integration: Eufy Security (documentation, issues)
First occurred: 12:32:05 (1 occurrences)
Last logged: 12:32:05

Error setting up entry localhost for eufy_security
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/eufy_security/__init__.py", line 50, in async_setup_entry
    await coordinator.initialize()
  File "/config/custom_components/eufy_security/coordinator.py", line 39, in initialize
    await self._api.connect()
  File "/config/custom_components/eufy_security/eufy_security_api/api_client.py", line 72, in connect
    await self._set_schema(SCHEMA_VERSION)
  File "/config/custom_components/eufy_security/eufy_security_api/api_client.py", line 150, in _set_schema
    await self._send_message_get_response(OutgoingMessage(OutgoingMessageType.set_api_schema, schema_version=schema_version))
  File "/config/custom_components/eufy_security/eufy_security_api/api_client.py", line 350, in _send_message_get_response
    return await future
           ^^^^^^^^^^^^
custom_components.eufy_security.eufy_security_api.exceptions.FailedCommandException: {'type': 'result', 'success': False, 'messageId': 'set_api_schema.fd37993729af45188cd1851cc1c24ef7', 'errorCode': 'schema_incompatible'}
`

**To reproduce**

**Expected behavior**

**Additional information**

Go to Settings -> System -> Repairs -> Click on 3 dots (...) -> System Information and get Version and Installation Type to below fields;
- Home Assistant Installation Type (OS - Supvervised - Core): Supervised
- Home Assistant Core Version: core-2023.6.1
- Eufy Security Add-on Version: 1.3.0
- Eufy Security Integration Version: 6.3

Hardware Information;
- Camera Model: Homebase, doorbel 2k

- Live Streaming Protocol (RTSP/P2P): P2P

- Debug Logs from Home Assistant (https://github.com/fuatakgun/eufy_security/discussions/624)
  details:
File "/config/custom_components/eufy_security/__init__.py", line 50, in async_setup_entry
File "/config/custom_components/eufy_security/coordinator.py", line 39, in initialize
File "/config/custom_components/eufy_security/eufy_security_api/api_client.py", line 72, in connect
File "/config/custom_components/eufy_security/eufy_security_api/api_client.py", line 150, in _set_schema
File "/config/custom_components/eufy_security/eufy_security_api/api_client.py", line 350, in _send_message_get_response
custom_components.eufy_security.eufy_security_api.exceptions.FailedCommandException: {'type': 'result', 'success': False, 'messageId': 'set_api_schema.ba4454e24a34473095054567999f25fa', 'errorCode': 'schema_incompatible'}
2023-06-13 12:49:51.139 DEBUG (MainThread) [custom_components.eufy_security.eufy_security_api] on_open - executed
2023-06-13 12:49:51.139 DEBUG (MainThread) [custom_components.eufy_security.eufy_security_api] domain - server - EventSourceType.server - set_api_schema - {'schema_version': 17} - {'schemaVersion': 17}
2023-06-13 12:49:51.140 DEBUG (MainThread) [custom_components.eufy_security.eufy_security_api] {'schemaVersion': 17, 'command': 'set_api_schema', 'messageId': 'set_api_schema.d2351d1f4e2f4048a64d78d78a6be5e4'}
2023-06-13 12:49:51.140 DEBUG (MainThread) [custom_components.eufy_security.eufy_security_api] send_message - {'schemaVersion': 17, 'command': 'set_api_schema', 'messageId': 'set_api_schema.d2351d1f4e2f4048a64d78d78a6be5e4'}
2023-06-13 12:49:51.142 DEBUG (MainThread) [custom_components.eufy_security.eufy_security_api] _on_message - {'type': 'version', 'driverVersion': '2.4.0', 'serverVersion': '1.3.0', 'minSchemaVersion': 0, 'maxSchemaVersion': 16}
2023-06-13 12:49:51.160 DEBUG (MainThread) [custom_components.eufy_security.eufy_security_api] _on_message - {'type': 'result', 'success': False, 'messageId': 'set_api_schema.d2351d1f4e2f4048a64d78d78a6be5e4', 'errorCode': 'schema_incompatible'}

- Logs from Eufy Security Add-on (either from Add-ons page of Home Assistant or Docker output):
{
  schemaId: 17,
  errorCode: 'schema_incompatible'
}
error stack:
• server.ts:91 receiveMessage
    src/lib/server.ts:91:27

• server.ts:68 <anonymous>
    src/lib/server.ts:68:53

• node:events:513 emit
    node:events:513:28

• websocket.js:1178 receiverOnMessage
    node_modules/ws/lib/websocket.js:1178:20

• node:events:513 emit
    node:events:513:28

• receiver.js:528 dataMessage
    node_modules/ws/lib/receiver.js:528:14

• receiver.js:446 getData
    node_modules/ws/lib/receiver.js:446:17

• receiver.js:148 startLoop
    node_modules/ws/lib/receiver.js:148:22

• receiver.js:83 _write
    node_modules/ws/lib/receiver.js:83:10

• writable:391 writeOrBuffer
    node:internal/streams/writable:391:12

- Would you share your device with me in case further debugging required? (Yes/No): 

**Additional context**

Add any other context about the problem goes here.

**Comment by Gilbertonl** [comment]
Same here. It stopped working after update to 6.3

**Comment by eberhardtconsulting** [comment]
Same here.

**Comment by Ringo982** [comment]
same problem here

**Comment by Ringo982** [comment]
meanwhile we wait for a solution, can anyone explain me better what does the "enable event picture" functionality means? I really don't understand..

**Comment by fuatakgun** [comment]
#809
