### ISSUE TITLE
Error schema_incompatible

### ISSUE THREAD

**Issue by floow77** [fuatakgun/eufy_security#815]
Hello,

I have this error:

Logger: homeassistant.config_entries
Source: custom_components/eufy_security/eufy_security_api/api_client.py:350
Integration: Eufy Security (documentation, issues)
First occurred: 21:32:41 (5 occurrences)
Last logged: 21:40:10

Error setting up entry 102.120.1.11 for eufy_security
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/eufy_security/__init__.py", line 50, in async_setup_entry
    await coordinator.initialize()
  File "/config/custom_components/eufy_security/coordinator.py", line 39, in initialize
    await self._api.connect()
  File "/config/custom_components/eufy_security/eufy_security_api/api_client.py", line 72, in connect
    await self._set_schema(SCHEMA_VERSION)
  File "/config/custom_components/eufy_security/eufy_security_api/api_client.py", line 150, in _set_schema
    await self._send_message_get_response(OutgoingMessage(OutgoingMessageType.set_api_schema, schema_version=schema_version))
  File "/config/custom_components/eufy_security/eufy_security_api/api_client.py", line 350, in _send_message_get_response
    return await future
           ^^^^^^^^^^^^
custom_components.eufy_security.eufy_security_api.exceptions.FailedCommandException: {'type': 'result', 'success': False, 'messageId': 'set_api_schema.9e360c88810b42d7aba014b96e4e2109', 'errorCode': 'schema_incompatible'}

**Additional information**

- Home Assistant Installation : Home Assistant OS
- Supervisor: supervisor-2023.06.2
- Home Assistant Core Version: core-2023.6.1
- Eufy Security Add-on Version: 
- Eufy Security Integration Version: v.6.3.0

**Comment by outrun0506** [comment]
Same here!
