### ISSUE TITLE
Failed to Setup

### ISSUE THREAD

**Issue by Jazza159** [fuatakgun/eufy_security#816]
**Describe the bug**

I updated to version 6.3.0 through HACS this morning and after restarting Eufy devices are offline.
Under integrations, Eufy Security shows "Failed to set up"
![image](https://github.com/fuatakgun/eufy_security/assets/96936843/2e0380e5-0797-4310-acd3-c15d66e7002b)

The Eufy security add-on starts and appears to connect to the base station before it errors.

I have tried restarting HA multiple times hoping that would fix the error. 
I was not able to find the same error in other issues so I have posted here. Thank you in advance 🙏

**To reproduce**

Update to version 6.3.0

**Expected behaviour**

Devices work as they have on previous versions.

**Additional information**

Go to Settings -> System -> Repairs -> Click on 3 dots (...) -> System Information and get Version and Installation Type to below fields;
- Home Assistant Installation Type (**OS**): 
- Home Assistant Core Version:  Home Assistant 2023.6.1
- Eufy Security Add-on Version: Current version: 1.3.0
- Eufy Security Integration Version: v6.3.0

Hardware Information;

- Debug Logs from Home Assistant (https://github.com/fuatakgun/eufy_security/discussions/624)
-2023-06-15 10:26:45.320 ERROR (MainThread) [homeassistant.components.hassio.handler] /store return code 500
2023-06-15 10:26:45.326 ERROR (MainThread) [homeassistant.components.hassio] Failed to to call /store -
2023-06-15 10:26:56.017 DEBUG (MainThread) [custom_components.eufy_security.eufy_security_api] on_open - executed
2023-06-15 10:26:56.017 DEBUG (MainThread) [custom_components.eufy_security.eufy_security_api] domain - server - EventSourceType.server - set_api_schema - {'schema_version': 17} - {'schemaVersion': 17}
2023-06-15 10:26:56.017 DEBUG (MainThread) [custom_components.eufy_security.eufy_security_api] {'schemaVersion': 17, 'command': 'set_api_schema', 'messageId': 'set_api_schema.68509028649a465fb1d0e52b2cf01d37'}
2023-06-15 10:26:56.017 DEBUG (MainThread) [custom_components.eufy_security.eufy_security_api] send_message - {'schemaVersion': 17, 'command': 'set_api_schema', 'messageId': 'set_api_schema.68509028649a465fb1d0e52b2cf01d37'}
2023-06-15 10:26:56.032 DEBUG (MainThread) [custom_components.eufy_security.eufy_security_api] _on_message - {'type': 'version', 'driverVersion': '2.4.0', 'serverVersion': '1.3.0', 'minSchemaVersion': 0, 'maxSchemaVersion': 16}
2023-06-15 10:26:56.044 DEBUG (MainThread) [custom_components.eufy_security.eufy_security_api] _on_message - {'type': 'result', 'success': False, 'messageId': 'set_api_schema.68509028649a465fb1d0e52b2cf01d37', 'errorCode': 'schema_incompatible'}
2023-06-15 10:26:56.049 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry localhost for eufy_security
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
result = await component.async_setup_entry(hass, self)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/eufy_security/__init__.py", line 50, in async_setup_entry
await coordinator.initialize()
File "/config/custom_components/eufy_security/coordinator.py", line 39, in initialize
await self._api.connect()
File "/config/custom_components/eufy_security/eufy_security_api/api_client.py", line 72, in connect
await self._set_schema(SCHEMA_VERSION)
File "/config/custom_components/eufy_security/eufy_security_api/api_client.py", line 150, in _set_schema
await self._send_message_get_response(OutgoingMessage(OutgoingMessageType.set_api_schema, schema_version=schema_version))
File "/config/custom_components/eufy_security/eufy_security_api/api_client.py", line 350, in _send_message_get_response
return await future
^^^^^^^^^^^^
custom_components.eufy_security.eufy_security_api.exceptions.FailedCommandException: {'type': 'result', 'success': False, 'messageId': 
2023-06-15 10:28:06.455 DEBUG (MainThread) [custom_components.eufy_security.eufy_security_api] on_close - executed

- Logs from Eufy Security Add-on (either from Add-ons page of Home Assistant or Docker output):
2023-06-15 00:28:13.006  INFO  Eufy Security server listening on host 0.0.0.0, port 3000 
2023-06-15 00:28:24.276  INFO  Push notification connection successfully established 
2023-06-15 00:28:24.435  INFO  Connected to station T8010P1320081AA2 on host 192.168.20.43 and port 10348 
2023-06-15 00:28:44.424  ERROR Station T8010P1320081AA2 - CMD_NOTIFY_PAYLOAD Error: 
{
  error: SyntaxError: Unexpected token  in JSON at position 35
      at JSON.parse (<anonymous>)
      at P2PClientProtocol.handleDataControl (/usr/src/app/node_modules/eufy-security-client/build/p2p/session.js:1450:43)
      at P2PClientProtocol.handleData (/usr/src/app/node_modules/eufy-security-client/build/p2p/session.js:1043:18)
      at P2PClientProtocol.parseDataMessage (/usr/src/app/node_modules/eufy-security-client/build/p2p/session.js:1031:26)
      at P2PClientProtocol.handleMsg (/usr/src/app/node_modules/eufy-security-client/build/p2p/session.js:868:26)
      at Socket.<anonymous> (/usr/src/app/node_modules/eufy-security-client/build/p2p/session.js:84:56)
      at Socket.emit (node:events:513:28)
      at UDP.onMessage [as onmessage] (node:dgram:930:8),
  payload: '{"cmd":1550,"payload":{"status":1}}\x00'
}
2023-06-15 00:28:51.629  ERROR Station T8010P1320081AA2 - CMD_NOTIFY_PAYLOAD Error: 
{
  error: SyntaxError: Unexpected token  in JSON at position 35
      at JSON.parse (<anonymous>)
      at P2PClientProtocol.handleDataControl (/usr/src/app/node_modules/eufy-security-client/build/p2p/session.js:1450:43)
      at P2PClientProtocol.handleData (/usr/src/app/node_modules/eufy-security-client/build/p2p/session.js:1043:18)
      at P2PClientProtocol.parseDataMessage (/usr/src/app/node_modules/eufy-security-client/build/p2p/session.js:1031:26)
      at P2PClientProtocol.handleMsg (/usr/src/app/node_modules/eufy-security-client/build/p2p/session.js:868:26)
      at Socket.<anonymous> (/usr/src/app/node_modules/eufy-security-client/build/p2p/session.js:84:56)
      at Socket.emit (node:events:513:28)
      at UDP.onMessage [as onmessage] (node:dgram:930:8),
  payload: '{"cmd":1550,"payload":{"status":0}}\x00'
}
2023-06-15 00:29:28.163  INFO  Disconnected from station T8010P1320081AA2 
2023-06-15 00:29:33.329  INFO  Connected to station T8010P1320081AA2 on host 192.168.20.43 and port 14801 
2023-06-15 00:30:36.982  INFO  Disconnected from station T8010P1320081AA2 
2023-06-15 00:30:42.150  INFO  Connected to station T8010P1320081AA2 on host 192.168.20.43 and port 10447 
2023-06-15 00:31:45.867  INFO  Disconnected from station T8010P1320081AA2 
2023-06-15 00:31:51.030  INFO  Connected to station T8010P1320081AA2 on host 192.168.20.43 and port 27622 
2023-06-15 00:32:15.608  ERROR Station T8010P1320081AA2 - CMD_NOTIFY_PAYLOAD Error: 
{
  error: SyntaxError: Unexpected token  in JSON at position 35
      at JSON.parse (<anonymous>)
      at P2PClientProtocol.handleDataControl (/usr/src/app/node_modules/eufy-security-client/build/p2p/session.js:1450:43)
      at P2PClientProtocol.handleData (/usr/src/app/node_modules/eufy-security-client/build/p2p/session.js:1043:18)
      at P2PClientProtocol.parseDataMessage (/usr/src/app/node_modules/eufy-security-client/build/p2p/session.js:1031:26)
      at P2PClientProtocol.handleMsg (/usr/src/app/node_modules/eufy-security-client/build/p2p/session.js:868:26)
      at Socket.<anonymous> (/usr/src/app/node_modules/eufy-security-client/build/p2p/session.js:1732:56)
      at Socket.emit (node:events:513:28)
      at UDP.onMessage [as onmessage] (node:dgram:930:8),
  payload: '{"cmd":1550,"payload":{"status":1}}\x00'
}
2023-06-15 00:32:54.720  INFO  Disconnected from station T8010P1320081AA2 
2023-06-15 00:32:59.880  INFO  Connected to station T8010P1320081AA2 on host 192.168.20.43 and port 23678 
2023-06-15 00:34:03.527  INFO  Disconnected from station T8010P1320081AA2 
2023-06-15 00:34:08.691  INFO  Connected to station T8010P1320081AA2 on host 192.168.20.43 and port 28400 
2023-06-15 00:35:12.407  INFO  Disconnected from station T8010P1320081AA2 
2023-06-15 00:35:17.570  INFO  Connected to station T8010P1320081AA2 on host 192.168.20.43 and port 16362 
2023-06-15 00:36:21.232  INFO  Disconnected from station T8010P1320081AA2 
2023-06-15 00:36:26.395  INFO  Connected to station T8010P1320081AA2 on host 192.168.20.43 and port 23709 

- Would you share your device with me in case further debugging required? (No): 
Sorry it's running as a VM on a unraid server.

**Additional context**
Thanks!

**Comment by Jazza159** [comment]
Solved by reinstalling and updating to the new add-on version. https://github.com/bropat/hassio-eufy-security-ws
