### ISSUE TITLE
Error setting up entry localhost for eufy_security

### ISSUE THREAD

**Issue by TheUncas** [fuatakgun/eufy_security#817]
**Describe the bug**

Since the update of Home assistant in the latest version & EUFY on HAC, i got this error (was working fine before the update)

**To reproduce**

update to versions : 

Home Assistant 2023.6.1
Supervisor 2023.06.2
Operating System 10.2

EUFY : 6.3.0

**Additional information**

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/eufy_security/__init__.py", line 50, in async_setup_entry
    await coordinator.initialize()
  File "/config/custom_components/eufy_security/coordinator.py", line 39, in initialize
    await self._api.connect()
  File "/config/custom_components/eufy_security/eufy_security_api/api_client.py", line 72, in connect
    await self._set_schema(SCHEMA_VERSION)
  File "/config/custom_components/eufy_security/eufy_security_api/api_client.py", line 150, in _set_schema
    await self._send_message_get_response(OutgoingMessage(OutgoingMessageType.set_api_schema, schema_version=schema_version))
  File "/config/custom_components/eufy_security/eufy_security_api/api_client.py", line 350, in _send_message_get_response
    return await future
           ^^^^^^^^^^^^
custom_components.eufy_security.eufy_security_api.exceptions.FailedCommandException: {'type': 'result', 'success': False, 'messageId': 'set_api_schema.c9ee1b1c93af436b96aaccc100dc194b', 'errorCode': 'schema_incompatible'}

**Comment by fuatakgun** [comment]
This is probably the 10th time this issue has been opened and i am closing this one again.
