### ISSUE TITLE
Issue connecting integration

### ISSUE THREAD

**Issue by the-despised** [fuatakgun/eufy_security#821]
Please check existing (open or closed) issues before creating a new one. (https://github.com/fuatakgun/eufy_security/issues?q=is%3Aissue+)

If this is not an issue, you can use `Discussions` (https://github.com/fuatakgun/eufy_security/discussions) section.

attempting to setup integration.  security module seems to be working correctly:

I have Eufy Cam 2C and Base station, 3 2c cameras.
1 x eufy smart lock (the new one)

 Version details

Version | core-2023.6.2
-- | --
Installation Type | Home Assistant OS
Development | false
Supervisor | true
Docker | true
User | root
Virtual Environment | false
Python Version | 3.11.4
Operating System Family | Linux
Operating System Version | 6.1.34
CPU Architecture | x86_64
Timezone | America/Toronto
Configuration Directory | /config

</body>
</html>

Hardware Information;
- Camera Model:

- Live Streaming Protocol (RTSP/P2P): 
- RTSP? doesn't matter, does not connect

- Debug Logs from Home Assistant (https://github.com/fuatakgun/eufy_security/discussions/624)
`
This error originated from a custom integration.

Logger: homeassistant.config_entries
Source: custom_components/eufy_security/eufy_security_api/product.py:48
Integration: Eufy Security (documentation, issues)
First occurred: 1:07:08 AM (5 occurrences)
Last logged: 1:24:30 AM

Error setting up entry 127.0.0.1 for eufy_security
Error setting up entry localhost for eufy_security
Error setting up entry 0.0.0.0 for eufy_security
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/eufy_security/__init__.py", line 50, in async_setup_entry
    await coordinator.initialize()
  File "/config/custom_components/eufy_security/coordinator.py", line 39, in initialize
    await self._api.connect()
  File "/config/custom_components/eufy_security/eufy_security_api/api_client.py", line 73, in connect
    await self._set_products()
  File "/config/custom_components/eufy_security/eufy_security_api/api_client.py", line 106, in _set_products
    self._devices = await self._get_products(ProductType.device, result[MessageField.STATE.value]["devices"])
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/eufy_security/eufy_security_api/api_client.py", line 126, in _get_products
    product = Device(self, serial_no, properties, metadata, commands)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/eufy_security/eufy_security_api/product.py", line 164, in __init__
    super().__init__(
  File "/config/custom_components/eufy_security/eufy_security_api/product.py", line 41, in __init__
    self._set_properties(properties)
  File "/config/custom_components/eufy_security/eufy_security_api/product.py", line 48, in _set_properties
    self.name = properties[MessageField.NAME.value]
                ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'name'
`

A clear and concise description of what the bug is.

**To reproduce**

Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**

A clear and concise description of what you expected to happen.

**Additional information**



- Logs from Eufy Security Add-on (either from Add-ons page of Home Assistant or Docker output):
*eufy-security-ws*
```
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
2023-06-16 05:14:10.109  INFO  Eufy Security server listening on host 0.0.0.0, port 3000 
2023-06-16 05:14:12.027  INFO  MQTT connection successfully established 
2023-06-16 05:14:12.063  INFO  Successfully registered to MQTT notifications for lock T8530K1022290E64 
2023-06-16 05:14:20.234  INFO  Connected to station T8021P11222621CE on host 10.101.1.10 and port 26799 
2023-06-16 05:14:20.270  INFO  Connected to station T8010P1321242AB0 on host 10.101.1.2 and port 28786 
2023-06-16 05:14:23.202  INFO  Push notification connection successfully established 
2023-06-16 05:21:25.712  INFO  Client disconnected with ip: 127.0.0.1 port: 59370 code: 1000 reason: Normal Closure 
2023-06-16 05:23:32.777  INFO  Client disconnected with ip: 127.0.0.1 port: 44964 code: 1000 reason: Normal Closure 
2023-06-16 05:24:29.856  INFO  Client disconnected with ip: 127.0.0.1 port: 52400 code: 1000 reason: Normal Closure 
```

- Would you share your device with me in case further debugging required? (Yes/No): 
Yes

**Additional context**

Add any other context about the problem goes here.

**Comment by lpequigny** [comment]
Same issue here.

**Comment by fuatakgun** [comment]
latest version should mitigate the issue, but not fix.

issue is that, you have some devices which are not supported by eufy security add-on and you need to get support from @bropat to include the support. Until then,  I am just generating dummy devices and naming them as UNSUPPORTED so you can see the status.
