### ISSUE TITLE
Error setting up entry 127.0.0.1 for eufy_security

### ISSUE THREAD

**Issue by danymexi** [fuatakgun/eufy_security#822]
This error originated from a custom integration.

Logger: homeassistant.config_entries
Source: custom_components/eufy_security/eufy_security_api/product.py:48
Integration: Eufy Security (documentation, issues)
First occurred: June 15, 2023 at 20:32:27 (6 occurrences)
Last logged: 06:00:57

Error setting up entry 127.0.0.1 for eufy_security
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/eufy_security/__init__.py", line 50, in async_setup_entry
    await coordinator.initialize()
  File "/config/custom_components/eufy_security/coordinator.py", line 39, in initialize
    await self._api.connect()
  File "/config/custom_components/eufy_security/eufy_security_api/api_client.py", line 73, in connect
    await self._set_products()
  File "/config/custom_components/eufy_security/eufy_security_api/api_client.py", line 106, in _set_products
    self._devices = await self._get_products(ProductType.device, result[MessageField.STATE.value]["devices"])
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/eufy_security/eufy_security_api/api_client.py", line 126, in _get_products
    product = Device(self, serial_no, properties, metadata, commands)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/eufy_security/eufy_security_api/product.py", line 164, in __init__
    super().__init__(
  File "/config/custom_components/eufy_security/eufy_security_api/product.py", line 41, in __init__
    self._set_properties(properties)
  File "/config/custom_components/eufy_security/eufy_security_api/product.py", line 48, in _set_properties
    self.name = properties[MessageField.NAME.value]
                ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'name'


I have this issue with the custom components...  it used to work... I switch the repo for the addon as requested... and now it doesn't work anymore. Do you have any idea why I'm getting this error and how to solve it?

Thanks for helping

**Comment by markus88melli90** [comment]
@fuatakgun First thanks for keeping all this up and running:) 
What was the solution for this issue? I am seeing the same after changing the repo for the addon and this is marked as completed now
