### ISSUE TITLE
Integration Failing

### ISSUE THREAD

**Issue by ifflanb** [fuatakgun/eufy_security#858]
I am getting the following in my logs when trying to start the integration.

This error originated from a custom integration.

Logger: homeassistant.config_entries
Source: custom_components/eufy_security/eufy_security_api/api_client.py:350
Integration: Eufy Security (documentation, issues)
First occurred: July 28, 2023 at 9:24:59 PM (5 occurrences)
Last logged: 6:00:49 AM

Error setting up entry 127.0.0.1 for eufy_security
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 388, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/eufy_security/__init__.py", line 50, in async_setup_entry
    await coordinator.initialize()
  File "/config/custom_components/eufy_security/coordinator.py", line 39, in initialize
    await self._api.connect()
  File "/config/custom_components/eufy_security/eufy_security_api/api_client.py", line 73, in connect
    await self._set_products()
  File "/config/custom_components/eufy_security/eufy_security_api/api_client.py", line 100, in _set_products
    result = await self._start_listening()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/eufy_security/eufy_security_api/api_client.py", line 147, in _start_listening
    return await self._send_message_get_response(OutgoingMessage(OutgoingMessageType.start_listening))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/eufy_security/eufy_security_api/api_client.py", line 350, in _send_message_get_response
    return await future
           ^^^^^^^^^^^^
asyncio.exceptions.CancelledError: Global task timeout

**Comment by fuatakgun** [comment]
https://github.com/fuatakgun/eufy_security/issues/795
