### ISSUE TITLE
Error setting up entry

### ISSUE THREAD

**Issue by trullock** [fuatakgun/eufy_security#868]
**Describe the bug**

Having had a working integration with v6.something (does HA contain a log of integration upgrades so i can see exactly which version?) for ages, and I just updated to 6.3 and then again 7 and was getting the below under both versions

```
Error setting up entry 127.0.0.1 for eufy_security
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 388, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/eufy_security/__init__.py", line 50, in async_setup_entry
    await coordinator.initialize()
  File "/config/custom_components/eufy_security/coordinator.py", line 37, in initialize
    await self._api.connect()
  File "/config/custom_components/eufy_security/eufy_security_api/api_client.py", line 71, in connect
    await self._set_schema(SCHEMA_VERSION)
  File "/config/custom_components/eufy_security/eufy_security_api/api_client.py", line 147, in _set_schema
    await self._send_message_get_response(OutgoingMessage(OutgoingMessageType.set_api_schema, schema_version=schema_version))
  File "/config/custom_components/eufy_security/eufy_security_api/api_client.py", line 320, in _send_message_get_response
    return await future
           ^^^^^^^^^^^^
custom_components.eufy_security.eufy_security_api.exceptions.FailedCommandException: {'type': 'result', 'success': False, 'messageId': 'set_api_schema.01f2127709b84af4a6d2ee9f8b11e384', 'errorCode': 'schema_incompatible'}

```

**To reproduce**

Booting HA with my setup, which is per the docs (or as the docs where when I set this up, I cant see anything different in new versions - maybe ive missed something?

**Expected behavior**

Integration to boot properly :)

**Additional information**

HA Core 

- Home Assistant Installation Type (OS - Supvervised - Core): Home Assistant OS
- Home Assistant Core Version: 2023.7 and also 2023.8
- Eufy Security Add-on Version: 1.3.0
- Eufy Security Integration Version: 6.3.something and 7.0.1

Hardware Information;
- Camera Model:

Efy Cam 2K Battery

- Live Streaming Protocol (RTSP/P2P): 

RTSP

- Debug Logs from Home Assistant (https://github.com/fuatakgun/eufy_security/discussions/624) - 
```2023-08-04 15:24:59.813 DEBUG (MainThread) [custom_components.eufy_security.eufy_security_api] on_open - executed
2023-08-04 15:24:59.814 DEBUG (MainThread) [custom_components.eufy_security.eufy_security_api] domain - server - EventSourceType.server - set_api_schema - {'schema_version': 18} - {'schemaVersion': 18}
2023-08-04 15:24:59.814 DEBUG (MainThread) [custom_components.eufy_security.eufy_security_api] {'schemaVersion': 18, 'command': 'set_api_schema', 'messageId': 'set_api_schema.a22ab055130049c7b9ec1e53e51123eb'}
2023-08-04 15:24:59.814 DEBUG (MainThread) [custom_components.eufy_security.eufy_security_api] send_message - {'schemaVersion': 18, 'command': 'set_api_schema', 'messageId': 'set_api_schema.a22ab055130049c7b9ec1e53e51123eb'}
2023-08-04 15:24:59.821 DEBUG (MainThread) [custom_components.eufy_security.eufy_security_api] _on_message - {'type': 'version', 'driverVersion': '2.4.0', 'serverVersion': '1.3.0', 'minSchemaVersion': 0, 'maxSchemaVersion': 16}
2023-08-04 15:24:59.831 DEBUG (MainThread) [custom_components.eufy_security.eufy_security_api] _on_message - {'type': 'result', 'success': False, 'messageId': 'set_api_schema.a22ab055130049c7b9ec1e53e51123eb', 'errorCode': 'schema_incompatible'}
2023-08-04 15:24:59.836 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry 127.0.0.1 for eufy_security
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/config_entries.py", line 388, in async_setup
result = await component.async_setup_entry(hass, self)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/eufy_security/__init__.py", line 50, in async_setup_entry
await coordinator.initialize()
File "/config/custom_components/eufy_security/coordinator.py", line 37, in initialize
await self._api.connect()
File "/config/custom_components/eufy_security/eufy_security_api/api_client.py", line 71, in connect
await self._set_schema(SCHEMA_VERSION)
File "/config/custom_components/eufy_security/eufy_security_api/api_client.py", line 147, in _set_schema
await self._send_message_get_response(OutgoingMessage(OutgoingMessageType.set_api_schema, schema_version=schema_version))
File "/config/custom_components/eufy_security/eufy_security_api/api_client.py", line 320, in _send_message_get_response
return await future
^^^^^^^^^^^^
custom_components.eufy_security.eufy_security_api.exceptions.FailedCommandException: {'type': 'result', 'success': False, 'messageId': 'set_api_schema.a22ab055130049c7b9ec1e53e51123eb', 'errorCode': 'schema_incompatible'}
```

- Logs from Eufy Security Add-on (either from Add-ons page of Home Assistant or Docker output):

```
2023-08-04 14:24:59.817  ERROR Message error 
 Error  
details:
{
  schemaId: 18,
  errorCode: 'schema_incompatible'
}
error stack:
• server.ts:91 receiveMessage
    src/lib/server.ts:91:27
• server.ts:68 <anonymous>
    src/lib/server.ts:68:53
• node:events:513 emit
    node:events:513:28
• websocket.js:1178 receiverOnMessage
    node_modules/ws/lib/websocket.js:1178:20
• node:events:513 emit
    node:events:513:28
• receiver.js:528 dataMessage
    node_modules/ws/lib/receiver.js:528:14
• receiver.js:446 getData
    node_modules/ws/lib/receiver.js:446:17
• receiver.js:148 startLoop
    node_modules/ws/lib/receiver.js:148:22
• receiver.js:83 _write
    node_modules/ws/lib/receiver.js:83:10
• writable:391 writeOrBuffer
    node:internal/streams/writable:391:12
```

- Would you share your device with me in case further debugging required? (Yes/No):

N/A

**Comment by trullock** [comment]
Sorry, looks like im using an OOD add on, I'll update and close this if resolved (i expect so)

standby...

**Comment by trullock** [comment]
Yep, sorry, didnt spot the change in repos
