### ISSUE TITLE
JSON Parse Error

### ISSUE THREAD

**Issue by azztech1** [fuatakgun/eufy_security#876]
Hi guys, 

Noticed I'd lost control and the integration woiuldn't initialise so I checked the logs and saw the below when restarting the add-on. Running home assisant OS on Pi4, everything up to date including HACS integration, add-on, etc. 

Home Assistant 2023.8.1
Supervisor 2023.08.1
Operating System 10.4
Frontend 20230802.0 - latest

Eufy Integration 7.0.2
Eufy Add-on 1.6.2

This error is a bit above my pay grade, hoping you can help.

s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
2023-08-09 22:36:52.336  INFO  Eufy Security server listening on host 0.0.0.0, port 3010 
2023-08-09 22:36:53.407  ERROR JSON parse error 
{
  data: '�;B�ec`t��"\b\x02�)ʹ��+\t\'�n���,�\x01&\x15�\'y\x0F��K9�x~���uU5\r\x18w,P�MP�ץn�\x15���\x02�\x00z]�\x0E�������ͦs�.���%2���\t���5��\x02\x7FM\x18g���Ԥ\b�\x1Bm\x0FV\x1D\x01�YO+/V��\x00\x10��3L��:\n' +
    'Q\x1B�a�S?�\x14Q�R�}q�����A\bX�h*��,/�4��nӠsH:\x10-��YZ�����0��*-{����tv͊�\x15�w��CCY\x17\x16ȝv�gX/\x18�z�{���e�,\x15�\x11Fa�7׫�뗺�\b�\x19I\x0E\x05\x13��\x07�iu\x00��Z&',
  error: SyntaxError: Unexpected token � in JSON at position 0
      at JSON.parse (<anonymous>)
      at parseJSON (/usr/src/app/node_modules/eufy-security-client/build/utils.js:147:21)
      at HTTPApi.decryptAPIData (/usr/src/app/node_modules/eufy-security-client/build/http/api.js:1086:50)
      at HTTPApi.getPassportProfile (/usr/src/app/node_modules/eufy-security-client/build/http/api.js:1282:46)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at async HTTPApi.login (/usr/src/app/node_modules/eufy-security-client/build/http/api.js:385:33)
      at async EufySecurity.connect (/usr/src/app/node_modules/eufy-security-client/build/eufysecurity.js:737:9)
      at async EufySecurityServer.start (/usr/src/app/node_modules/eufy-security-ws/dist/lib/server.js:413:9)
      at async /usr/src/app/node_modules/eufy-security-ws/dist/bin/server.js:56:9
}
2023-08-09 22:36:53.431  ERROR Generic Error 
 TypeError  Cannot read properties of undefined (reading 'user_id')
error stack:
• api.ts:1272 getPassportProfile
    usr/src/app/node_modules/eufy-security-client/src/http/api.ts:1272:63
• task_queues:96 processTicksAndRejections
    node:internal/process/task_queues:96:5
• api.ts:384 login
    usr/src/app/node_modules/eufy-security-client/src/http/api.ts:384:33
• eufysecurity.ts:758 connect
    usr/src/app/node_modules/eufy-security-client/src/eufysecurity.ts:758:9
• server.ts:495 start
    usr/src/app/node_modules/eufy-security-ws/src/lib/server.ts:495:9
• server.ts:66 <anonymous>
    usr/src/app/node_modules/eufy-security-ws/src/bin/server.ts:66:9

**Comment by fuatakgun** [comment]
Wrong repo, open issue for add-on repository
