### ISSUE TITLE
No devices showing

### ISSUE THREAD

**Issue by v-mod** [fuatakgun/eufy_security#899]
**Describe the bug**

No devices are being displayed: 
![image](https://github.com/fuatakgun/eufy_security/assets/80989699/306f4617-9673-4d39-89af-bda7b0cdad4c)

**To reproduce**

1. Go to 'Devices & Services'
2. Click on 'Eufy Security'
3. See Missing Devices

**Expected behavior**

I have 3 eufy cameras and a doorbell yet none of them are showing. 

**Additional information**

Go to Settings -> System -> Repairs -> Click on 3 dots (...) -> System Information and get Version and Installation Type to below fields;
- Home Assistant Installation Type (OS - Supvervised - Core): 
- Home Assistant Core Version: 
- Eufy Security Add-on Version: 
- Eufy Security Integration Version:

Hardware Information;
- Camera Model:
EufyCam 2C Pro
Eufy Doorbell 2K HD Battery-Powered

- Live Streaming Protocol (RTSP/P2P): 
RTSP

- Debug Logs from Home Assistant (https://github.com/fuatakgun/eufy_security/discussions/624) - Without this, I will automatically resolve this issue
  
This error originated from a custom integration.

Logger: homeassistant
Source: custom_components/eufy_security/eufy_security_api/api_client.py:305
Integration: Eufy Security (documentation, issues)
First occurred: 16:06:51 (1 occurrences)
Last logged: 16:06:51

Error doing job: Exception in callback WebSocketClient._on_close(<Task finishe...> result=None>)
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/config/custom_components/eufy_security/eufy_security_api/web_socket_client.py", line 80, in _on_close
    self.close_callback(future)
  File "/config/custom_components/eufy_security/eufy_security_api/api_client.py", line 305, in _on_close
    self._on_error_callback(future)
TypeError: 'NoneType' object is not callable

- Logs from Eufy Security Add-on (either from Add-ons page of Home Assistant or Docker output):
2023-08-22 14:55:48.237  INFO  Eufy Security server listening on host 0.0.0.0, port 3000
2023-08-22 14:55:50.754  INFO  No stations found.
2023-08-22 14:55:51.147  INFO  No devices found.
2023-08-22 14:55:54.472  INFO  Push notification connection successfully established
2023-08-22 14:57:52.912  INFO  Client disconnected with ip: 127.0.0.1 port: 53918 code: 1000 reason: Normal Closure
2023-08-22 14:57:57.448  INFO  Client disconnected with ip: 127.0.0.1 port: 53922 code: 1000 reason: Normal Closure
2023-08-22 15:02:10.684  INFO  Client disconnected with ip: 127.0.0.1 port: 53926 code: 1006 reason: Abnormal Closure
2023-08-22 15:05:52.926  INFO  No stations found.
2023-08-22 15:05:53.446  INFO  No devices found.
2023-08-22 15:06:47.811  INFO  Client disconnected with ip: 127.0.0.1 port: 58026 code: 1000 reason: Normal Closure
2023-08-22 15:06:51.083  INFO  Client disconnected with ip: 127.0.0.1 port: 40048 code: 1000 reason: Normal Closure

- Would you share your device with me in case further debugging required? (Yes/No):
No

**Additional context**

I am running the eufy-security-ws as a container in docker compose with the following config:
  eufy-security-ws:
    container_name: eufy-security
    image: bropat/eufy-security-ws:latest
    network_mode: "host"
    restart: always
    environment:
      - USERNAME=************@********.com
      - PASSWORD=*******
      - PORT=3000
    volumes:
      - /data/eufy-security-ws:/data

**Comment by v-mod** [comment]
It turns out I had forgotten to pass the country to eufy-security-ws in my docker config. It now works.
