### ISSUE TITLE
On Adding Integration: Unexpected exception importing platform custom_components.eufy_security.config_flow

### ISSUE THREAD

**Issue by tne7laa** [fuatakgun/eufy_security#906]
I'm trying to add integration via HACS. Previously in the past it was successful but deleted integration.
Now i own a new camera I want to use it but get errors on adding (after added to HACS and restart) Integration.

**To reproduce**

1. Go to 'Integrations'
2. Click on 'Add' and search for Eufy Security
3. See error

Home Assistant 2023.3.3
Frontend 20230309.0 - latest
Eufy Security Add-on Version: latest 

Hardware Information;
Camera Model: Homebase 2 with doorbell

![Scherm­afbeelding 2023-08-26 om 11 29 51 normaal](https://github.com/fuatakgun/eufy_security/assets/805474/62ab4dab-05b3-43d8-aecb-8a30873ade7c)
![Scherm­afbeelding 2023-08-26 om 11 30 03 normaal](https://github.com/fuatakgun/eufy_security/assets/805474/b561be58-795d-4383-8d51-0d2b9a01551d)

Error in text:

```
This error originated from a custom integration.

Logger: homeassistant.loader
Source: custom_components/eufy_security/const.py:36 
Integration: Eufy Security (documentation, issues) 
First occurred: 11:25:30 (1 occurrences) 
Last logged: 11:25:30

Unexpected exception importing platform custom_components.eufy_security.config_flow
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 779, in get_platform
    cache[full_name] = self._import_platform(platform_name)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 796, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/config/custom_components/eufy_security/__init__.py", line 10, in <module>
    from .const import COORDINATOR, DOMAIN, PLATFORMS
  File "/config/custom_components/eufy_security/const.py", line 36, in <module>
    Platform.IMAGE,
  File "/usr/local/lib/python3.10/enum.py", line 437, in __getattr__
    raise AttributeError(name) from None
AttributeError: IMAGE
```

Because Integration does not show up in Integration UI I had to delete it from .storage/hacs.repositories manually. Because HASC complained about it that was till installed. Also uninstalled from HACS and afterwards installed it again. No luck and same error.

**Comment by fuatakgun** [comment]
You are using 5 to 6 months old version of HA, you need at least June or July version.

**Comment by tne7laa** [comment]
> You are using 5 to 6 months old version of HA, you need at least June or July version.

I'm really sorry. I always did HA update if there was any. What I didn't know that I also should update the docker image (??). I thought that was not necessary. I did that and now I'm on:
Home Assistant 2023.8.4
Frontend 20230802.1 - latest

And almost everything is working except playing stream in VLC. Getting error messages in VLC and in tsp-simple-server like:
```
2023/08/26 12:18:45 INF [RTSP] [session 29eefac3] created by 192.168.1.41:60654
2023/08/26 12:18:45 INF [RTSP] [conn 192.168.1.41:60654] closed (path of a SETUP request must end with a slash. This typically happens when VLC fails a request, and then switches to an unsupported RTSP dialect)
2023/08/26 12:18:45 INF [RTSP] [session 29eefac3] destroyed (not in use)
2023/08/26 12:18:45 INF [RTSP] [conn 192.168.1.41:60655] opened
2023/08/26 12:18:45 INF [RTSP] [conn 192.168.1.41:60655] closed (EOF)
```
Therefore I have to look into it further. Thanks.
