### ISSUE TITLE
Error Loading Home Assistant Integration

### ISSUE THREAD

**Issue by aaronbarnaby** [fuatakgun/eufy_security#907]
When I add (or reload) the Eufy Security integration into my home assistant instance I get the following log error:

Logger: homeassistant.config_entries
Source: custom_components/eufy_security/eufy_security_api/api_client.py:319
Integration: Eufy Security ([documentation](https://github.com/fuatakgun/eufy_security), [issues](https://github.com/fuatakgun/eufy_security/issues))
First occurred: 14:01:59 (1 occurrences)
Last logged: 14:01:59

Error setting up entry 127.0.0.1 for eufy_security
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 388, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/eufy_security/__init__.py", line 50, in async_setup_entry
    await coordinator.initialize()
  File "/config/custom_components/eufy_security/coordinator.py", line 37, in initialize
    await self._api.connect()
  File "/config/custom_components/eufy_security/eufy_security_api/api_client.py", line 71, in connect
    await self._set_schema(SCHEMA_VERSION)
  File "/config/custom_components/eufy_security/eufy_security_api/api_client.py", line 147, in _set_schema
    await self._send_message_get_response(OutgoingMessage(OutgoingMessageType.set_api_schema, schema_version=schema_version))
  File "/config/custom_components/eufy_security/eufy_security_api/api_client.py", line 319, in _send_message_get_response
    return await future
           ^^^^^^^^^^^^
custom_components.eufy_security.eufy_security_api.exceptions.FailedCommandException: {'type': 'result', 'success': False, 'messageId': 'set_api_schema.ae7a73cdce9549e4ad89a9656c82ad61', 'errorCode': 'schema_incompatible'}

I'm on the latest OS and software version for Home Assistant and guessing this is because of the upgrade to latest version as it was working before this upgrade.

**Comment by fuatakgun** [comment]
Follow bug template
