### ISSUE TITLE
Previously working integration now fails to start with 'schema_incompatible'

### ISSUE THREAD

**Issue by hfaran** [fuatakgun/eufy_security#925]
Please check existing (open or closed) issues before creating a new one. (https://github.com/fuatakgun/eufy_security/issues?q=is%3Aissue+)

If this is not an issue, you can use `Discussions` (https://github.com/fuatakgun/eufy_security/discussions) section.

Integration fails to start with 'schema_incompatible' when I check error logs. The integration had previously been working. 

Start Home Assistant, as normal.

Integration should start without issue (as it had been working previously).

**Additional information**

Go to Settings -> System -> Repairs -> Click on 3 dots (...) -> System Information and get Version and Installation Type to below fields;
- Home Assistant Installation Type (OS - Supvervised - Core):  Home Assistant OS
- Home Assistant Core Version: core-2023.9.1
- Eufy Security Add-on Version: v7.0.4
- Eufy Security Integration Version: v1.3.0

Hardware Information;
- Camera Model:
Eufy Smart Lock T8520

- Live Streaming Protocol (RTSP/P2P): 

- Debug Logs from Home Assistant (https://github.com/fuatakgun/eufy_security/discussions/624) - Without this, I will automatically resolve this issue
  
```
2023-09-10 11:46:47.054 DEBUG (MainThread) [custom_components.eufy_security.eufy_security_api] on_open - executed
2023-09-10 11:46:47.054 DEBUG (MainThread) [custom_components.eufy_security.eufy_security_api] domain - server - EventSourceType.server - set_api_schema - {'schema_version': 18} - {'schemaVersion': 18}
2023-09-10 11:46:47.057 DEBUG (MainThread) [custom_components.eufy_security.eufy_security_api] {'schemaVersion': 18, 'command': 'set_api_schema', 'messageId': 'set_api_schema.beb9d535c2e545929141bde7e09f09c5'}
2023-09-10 11:46:47.057 DEBUG (MainThread) [custom_components.eufy_security.eufy_security_api] send_message - {'schemaVersion': 18, 'command': 'set_api_schema', 'messageId': 'set_api_schema.beb9d535c2e545929141bde7e09f09c5'}
2023-09-10 11:46:47.062 DEBUG (MainThread) [custom_components.eufy_security.eufy_security_api] _on_message - {'type': 'version', 'driverVersion': '2.4.0', 'serverVersion': '1.3.0', 'minSchemaVersion': 0, 'maxSchemaVersion': 16}
2023-09-10 11:46:47.099 DEBUG (MainThread) [custom_components.eufy_security.eufy_security_api] _on_message - {'type': 'result', 'success': False, 'messageId': 'set_api_schema.beb9d535c2e545929141bde7e09f09c5', 'errorCode': 'schema_incompatible'}
2023-09-10 11:46:47.100 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry 127.0.0.1 for eufy_security
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 388, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/eufy_security/__init__.py", line 50, in async_setup_entry
    await coordinator.initialize()
  File "/config/custom_components/eufy_security/coordinator.py", line 37, in initialize
    await self._api.connect()
  File "/config/custom_components/eufy_security/eufy_security_api/api_client.py", line 71, in connect
    await self._set_schema(SCHEMA_VERSION)
  File "/config/custom_components/eufy_security/eufy_security_api/api_client.py", line 147, in _set_schema
    await self._send_message_get_response(OutgoingMessage(OutgoingMessageType.set_api_schema, schema_version=schema_version))
  File "/config/custom_components/eufy_security/eufy_security_api/api_client.py", line 319, in _send_message_get_response
    return await future
           ^^^^^^^^^^^^
custom_components.eufy_security.eufy_security_api.exceptions.FailedCommandException: {'type': 'result', 'success': False, 'messageId': 'set_api_schema.beb9d535c2e545929141bde7e09f09c5', 'errorCode': 'schema_incompatible'}
```

- Logs from Eufy Security Add-on (either from Add-ons page of Home Assistant or Docker output):

```
2023-09-10 18:46:22.025  INFO  Push notification connection successfully established 
2023-09-10 18:46:38.840  WARN Station T8520Q2021380E45 - Tried all hosts, no connection could be established 
2023-09-10 18:46:38.845  INFO  Timeout connecting to station T8520Q2021380E45 
2023-09-10 18:46:47.078  ERROR Message error 
 Error  
details:
{
  schemaId: 18,
  errorCode: 'schema_incompatible'
}
error stack:
• server.ts:91 receiveMessage
    src/lib/server.ts:91:27
• server.ts:68 <anonymous>
    src/lib/server.ts:68:53
• node:events:513 emit
    node:events:513:28
• websocket.js:1178 receiverOnMessage
    node_modules/ws/lib/websocket.js:1178:20
• node:events:513 emit
    node:events:513:28
• receiver.js:528 dataMessage
    node_modules/ws/lib/receiver.js:528:14
• receiver.js:446 getData
    node_modules/ws/lib/receiver.js:446:17
• receiver.js:148 startLoop
    node_modules/ws/lib/receiver.js:148:22
• receiver.js:83 _write
    node_modules/ws/lib/receiver.js:83:10
• writable:391 writeOrBuffer
    node:internal/streams/writable:391:12
2023-09-10 18:47:00.716  WARN Station T8520Q2021380E45 - Tried all hosts, no connection could be established 
2023-09-10 18:47:00.719  INFO  Timeout connecting to station T8520Q2021380E45 
2023-09-10 18:47:27.763  WARN Station T8520Q2021380E45 - Tried all hosts, no connection could be established 
2023-09-10 18:47:27.766  INFO  Timeout connecting to station T8520Q2021380E45 
2023-09-10 18:48:04.436  WARN Station T8520Q2021380E45 - Tried all hosts, no connection could be established 
2023-09-10 18:48:04.439  INFO  Timeout connecting to station T8520Q2021380E45 
2023-09-10 18:48:51.131  WARN Station T8520Q2021380E45 - Tried all hosts, no connection could be established 
2023-09-10 18:48:51.133  INFO  Timeout connecting to station T8520Q2021380E45 
2023-09-10 18:49:48.011  WARN Station T8520Q2021380E45 - Tried all hosts, no connection could be established 
2023-09-10 18:49:48.013  INFO  Timeout connecting to station T8520Q2021380E45 
2023-09-10 18:50:54.867  WARN Station T8520Q2021380E45 - Tried all hosts, no connection could be established 
2023-09-10 18:50:54.870  INFO  Timeout connecting to station T8520Q2021380E45 
2023-09-10 18:53:12.061  WARN Station T8520Q2021380E45 - Tried all hosts, no connection could be established 
2023-09-10 18:53:12.062  INFO  Timeout connecting to station T8520Q2021380E45 
2023-09-10 18:56:28.802  WARN Station T8520Q2021380E45 - Tried all hosts, no connection could be established 
2023-09-10 18:56:28.805  INFO  Timeout connecting to station T8520Q2021380E45 
2023-09-10 18:57:53.393  INFO  Client disconnected with ip: 172.30.32.1 port: 39174 code: 1006 reason: Abnormal Closure 
2023-09-10 18:59:28.897  ERROR Message error 
 Error  
details:
{
  schemaId: 18,
  errorCode: 'schema_incompatible'
}
error stack:
• server.ts:91 receiveMessage
    src/lib/server.ts:91:27
• server.ts:68 <anonymous>
    src/lib/server.ts:68:53
• node:events:513 emit
    node:events:513:28
• websocket.js:1178 receiverOnMessage
    node_modules/ws/lib/websocket.js:1178:20
• node:events:513 emit
    node:events:513:28
• receiver.js:528 dataMessage
    node_modules/ws/lib/receiver.js:528:14
• receiver.js:446 getData
    node_modules/ws/lib/receiver.js:446:17
• receiver.js:148 startLoop
    node_modules/ws/lib/receiver.js:148:22
• receiver.js:83 _write
    node_modules/ws/lib/receiver.js:83:10
• writable:391 writeOrBuffer
    node:internal/streams/writable:391:12
2023-09-10 19:00:45.544  WARN Station T8520Q2021380E45 - Tried all hosts, no connection could be established 
2023-09-10 19:00:45.547  INFO  Timeout connecting to station T8520Q2021380E45 
```

- Would you share your device with me in case further debugging required? (Yes/No):

**Additional context**

Add any other context about the problem goes here. Mainly, share everything as log files and use screenshots as last resort.

![image](https://github.com/fuatakgun/eufy_security/assets/2450496/aaa407f6-eb33-406c-8165-6c846d30f4d1)
![image](https://github.com/fuatakgun/eufy_security/assets/2450496/b490c097-6649-484a-9a58-b9a64d140e97)
![image](https://github.com/fuatakgun/eufy_security/assets/2450496/0cce337f-6c09-422b-8bd1-0da8bde74e34)

**Comment by hfaran** [comment]
Resolved this issue by installing the new Add-On (here: https://github.com/bropat/hassio-eufy-security-ws/tree/master/eufy-security-ws) and setting it up.
