### ISSUE TITLE
Installing via docker: Trying to setup Eufy Security Web Socket instance results in crash

### ISSUE THREAD

**Issue by tkhobbes** [fuatakgun/eufy_security#942]
**Describe the bug**

I get until step 3.5.
My Home Assistant is installed as a docker container (Core). I have installed a separate container for [bluenviron/mediamtx:latest](http://portainer.uzw18.net/#!/2/docker/images/bluenviron~2Fmediamtx%3Alatest) as per step 2.

When fill in the form in step 3.5 to connect to the eufy security web socket instance, I can see the following logs:

```
2023-10-03 11:49:12.358 ERROR (MainThread) [frontend.js.latest.202309110] Uncaught error from Safari 16.5 on Mac OS 10.15.7
Script error.
null

m
2023-10-03 11:49:17.555 ERROR (MainThread) [custom_components.eufy_security.config_flow] eufy_security Exception in login : Connection to add-on was broken. please reload the integration! - traceback: Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/aiohttp/connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 1085, in create_connection
    raise exceptions[0]
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 1069, in create_connection
    sock = await self._connect_sock(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 973, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/local/lib/python3.11/asyncio/selector_events.py", line 628, in sock_connect
    return await fut
           ^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/selector_events.py", line 668, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 111] Connect call failed ('127.0.0.1', 3000)
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/config/custom_components/eufy_security/eufy_security_api/web_socket_client.py", line 42, in connect
    self.socket = await self.session.ws_connect(f"ws://{self.host}:{self.port}", autoclose=False, autoping=True, heartbeat=60)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/client.py", line 779, in _ws_connect
    resp = await self.request(
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/client.py", line 536, in _request
    conn = await self._connector.connect(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/connector.py", line 1209, in _create_direct_connection
    raise last_exc
  File "/usr/local/lib/python3.11/site-packages/aiohttp/connector.py", line 1178, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host 127.0.0.1:3000 ssl:default [Connect call failed ('127.0.0.1', 3000)]
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/config/custom_components/eufy_security/config_flow.py", line 113, in _test_credentials
    await api_client.ws_connect()
  File "/config/custom_components/eufy_security/eufy_security_api/api_client.py", line 66, in ws_connect
    await self._client.connect()
  File "/config/custom_components/eufy_security/eufy_security_api/web_socket_client.py", line 44, in connect
    raise WebSocketConnectionException("Connection to add-on was broken. please reload the integration!") from exc
custom_components.eufy_security.eufy_security_api.exceptions.WebSocketConnectionException: Connection to add-on was broken. please reload the integration!
```

**To reproduce**

1. Go to "Settings" - "Devices and Services"
2. Click on "Add Integration"
3. Search for "Eufy Security" and select it
4. Enter any IP address and any port
5. Check docker logs to see error

**Expected behavior**

**Additional information**

Go to Settings -> System -> Repairs -> Click on 3 dots (...) -> System Information and get Version and Installation Type to below fields;
- Home Assistant Installation Type (OS - Supvervised - Core):  Core
- Home Assistant Core Version: core-2023.9.3

- Debug Logs from Home Assistant:
```
2023-10-03 12:04:22.095 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration eufy_security which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-10-03 12:04:22.095 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-10-03 12:04:46.129 ERROR (MainThread) [frontend.js.latest.202309110] Uncaught error from Safari 16.5 on Mac OS 10.15.7
Script error.
null
@:0:0
2023-10-03 12:04:47.829 DEBUG (MainThread) [custom_components.eufy_security.config_flow] eufy_security async_step_user - None - {'_errors': {}, 'init_step': 'user', 'hass': <homeassistant.core.HomeAssistant object at 0x7f1a694b3e90>, 'handler': 'eufy_security', 'flow_id': '7a62b404a17cb79e29a780aa3eff51d9', 'context': {'source': 'user', 'show_advanced_options': False}, 'init_data': None}
2023-10-03 12:04:49.778 DEBUG (MainThread) [custom_components.eufy_security.config_flow] eufy_security async_step_user - {'host': '127.0.0.1', 'port': 3000} - {'_errors': {}, 'init_step': 'user', 'hass': <homeassistant.core.HomeAssistant object at 0x7f1a694b3e90>, 'handler': 'eufy_security', 'flow_id': '7a62b404a17cb79e29a780aa3eff51d9', 'context': {'source': 'user', 'show_advanced_options': False}, 'init_data': None, 'cur_step': {'type': <FlowResultType.FORM: 'form'>, 'flow_id': '7a62b404a17cb79e29a780aa3eff51d9', 'handler': 'eufy_security', 'step_id': 'user', 'data_schema': <Schema({'host': <class 'str'>, 'port': <class 'int'>}, extra=PREVENT_EXTRA, required=False) object at 0x7f1a36b4a210>, 'errors': {}, 'description_placeholders': None, 'last_step': None, 'preview': None}}
2023-10-03 12:04:49.783 ERROR (MainThread) [custom_components.eufy_security.config_flow] eufy_security Exception in login : Connection to add-on was broken. please reload the integration! - traceback: Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/aiohttp/connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 1085, in create_connection
    raise exceptions[0]
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 1069, in create_connection
    sock = await self._connect_sock(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 973, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/local/lib/python3.11/asyncio/selector_events.py", line 628, in sock_connect
    return await fut
           ^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/selector_events.py", line 668, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 111] Connect call failed ('127.0.0.1', 3000)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/eufy_security/eufy_security_api/web_socket_client.py", line 42, in connect
    self.socket = await self.session.ws_connect(f"ws://{self.host}:{self.port}", autoclose=False, autoping=True, heartbeat=60)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/client.py", line 779, in _ws_connect
    resp = await self.request(
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/client.py", line 536, in _request
    conn = await self._connector.connect(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/connector.py", line 1209, in _create_direct_connection
    raise last_exc
  File "/usr/local/lib/python3.11/site-packages/aiohttp/connector.py", line 1178, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host 127.0.0.1:3000 ssl:default [Connect call failed ('127.0.0.1', 3000)]

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/eufy_security/config_flow.py", line 113, in _test_credentials
    await api_client.ws_connect()
  File "/config/custom_components/eufy_security/eufy_security_api/api_client.py", line 66, in ws_connect
    await self._client.connect()
  File "/config/custom_components/eufy_security/eufy_security_api/web_socket_client.py", line 44, in connect
    raise WebSocketConnectionException("Connection to add-on was broken. please reload the integration!") from exc
custom_components.eufy_security.eufy_security_api.exceptions.WebSocketConnectionException: Connection to add-on was broken. please reload the integration!
```

- Logs from Eufy Security Add-on (either from Add-ons page of Home Assistant or Docker output):
```
2023/10/03 09:30:36 INF MediaMTX v1.1.1
2023/10/03 09:30:36 INF [RTSP] listener opened on :8554 (TCP), :8000 (UDP/RTP), :8001 (UDP/RTCP)
2023/10/03 09:30:36 INF [RTMP] listener opened on :1935
2023/10/03 09:30:36 INF [HLS] listener opened on :8888
2023/10/03 09:30:36 INF [WebRTC] listener opened on :8889 (HTTP)
2023/10/03 09:30:36 INF [SRT] listener opened on :8890 (UDP)
2023/10/03 09:39:29 INF [RTSP] [conn 192.168.0.41:57266] opened
2023/10/03 09:39:29 INF [RTSP] [conn 192.168.0.41:57266] closed: invalid URL (/)
2023/10/03 09:39:46 INF [RTMP] [conn 192.168.0.41:50186] opened
2023/10/03 09:39:46 INF [RTMP] [conn 192.168.0.41:50186] closed: invalid rtmp version (71)
```

- Would you share your device with me in case further debugging required? (Yes/No): No (not possible)

**Comment by fuatakgun** [comment]
eufy security integration is not able to connect eufy security ws add-on.
you need to share the logs from eufy-security-ws add-on or docker instance in your case.
you have not reached a point to connect with bluenviron/mediamtx:latest, so logs from bluenviron/mediamtx:latest is irrelevant as of now.

Please check eufy-security-ws logs, but it is merely telling that connection between home assistant and eufy-security-ws is broken, not sure how I can help.
