### ISSUE TITLE
T8214 Doorbell Missing Most Properties and Functions

### ISSUE THREAD

**Issue by ianisms** [fuatakgun/eufy_security#965]
**Describe the bug**

I have a Eufy E340 Doorbell (T8214). When I add the eufy security integration, it finds and adds the device however, the device only has a debug sensor entity and disabled reset, trigger alarm entities.

![IMG_0067](https://github.com/fuatakgun/eufy_security/assets/1770935/da8f07e4-7c1a-4884-8412-6d91c46b35d1)

**To reproduce**

**Expected behavior**

Hoping to configure this device for P2P streaming 

**Additional information**

- Home Assistant Installation Type (OS - Supvervised - Core): OS
- Home Assistant Core Version: core-2023.10.5
- Eufy Security Add-on Version: 1.6.4
- Eufy Security Integration Version: 7.7.1

Hardware Information;
- Camera Model: T8214

- Live Streaming Protocol (RTSP/P2P): P2P

- Debug Logs from Home Assistant (https://github.com/fuatakgun/eufy_security/discussions/624) - Without this, I will automatically resolve this issue
- 
  2023-10-28 12:37:11.558 WARNING (SyncWorker_2) [homeassistant.loader] We found a custom integration frigate which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-10-28 12:37:11.562 WARNING (SyncWorker_2) [homeassistant.loader] We found a custom integration eufy_security which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-10-28 12:37:11.564 WARNING (SyncWorker_2) [homeassistant.loader] We found a custom integration smartthinq_sensors which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-10-28 12:37:11.569 WARNING (SyncWorker_2) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-10-28 12:37:39.500 ERROR (MainThread) [homeassistant.components.mqtt_room.sensor] MQTT integration is not available
2023-10-28 12:37:53.177 WARNING (MainThread) [homeassistant.setup] Setup of input_text is taking over 10 seconds.
2023-10-28 12:37:53.178 WARNING (MainThread) [homeassistant.setup] Setup of counter is taking over 10 seconds.
2023-10-28 12:37:53.178 WARNING (MainThread) [homeassistant.setup] Setup of tag is taking over 10 seconds.
2023-10-28 12:37:53.179 WARNING (MainThread) [homeassistant.setup] Setup of input_select is taking over 10 seconds.
2023-10-28 12:37:53.180 WARNING (MainThread) [homeassistant.setup] Setup of zone is taking over 10 seconds.
2023-10-28 12:37:53.199 ERROR (MainThread) [homeassistant.components.mqtt_room.sensor] MQTT integration is not available
2023-10-28 12:37:53.441 ERROR (MainThread) [homeassistant.components.mqtt_room.sensor] MQTT integration is not available
2023-10-28 12:37:55.794 WARNING (MainThread) [homeassistant.setup] Setup of input_boolean is taking over 10 seconds.
2023-10-28 12:37:55.795 WARNING (MainThread) [homeassistant.setup] Setup of input_number is taking over 10 seconds.
2023-10-28 12:37:56.817 ERROR (MainThread) [homeassistant.components.mqtt_room.sensor] MQTT integration is not available
2023-10-28 12:38:00.189 INFO (MainThread) [backoff] Backing off async_request(...) for 0.2s (tesla_wall_connector.exceptions.WallConnectorConnectionTimeoutError: Timeout while connecting to Wall Connector at 192.168.2.147)
2023-10-28 12:38:11.260 DEBUG (MainThread) [custom_components.eufy_security.eufy_security_api] on_open - executed
2023-10-28 12:38:11.276 DEBUG (MainThread) [custom_components.eufy_security.eufy_security_api] domain - server - EventSourceType.server - set_api_schema - {'schema_version': 19} - {'schemaVersion': 19}
2023-10-28 12:38:11.278 DEBUG (MainThread) [custom_components.eufy_security.eufy_security_api] {'schemaVersion': 19, 'command': 'set_api_schema', 'messageId': 'set_api_schema.9b42d4dd091744d1bf700bf33b1ff798'}
2023-10-28 12:38:11.279 DEBUG (MainThread) [custom_components.eufy_security.eufy_security_api] send_message - {'schemaVersion': 19, 'command': 'set_api_schema', 'messageId': 'set_api_schema.9b42d4dd091744d1bf700bf33b1ff798'}
2023-10-28 12:38:11.724 DEBUG (MainThread) [custom_components.eufy_security.eufy_security_api] _on_message - {'type': 'version', 'driverVersion': '2.8.1', 'serverVersion': '1.6.4', 'minSchemaVersion': 0, 'maxSchemaVersion': 19}
2023-10-28 12:38:11.745 DEBUG (MainThread) [custom_components.eufy_security.eufy_security_api] _on_message - {'type': 'result', 'success': True, 'messageId': 'set_api_schema.9b42d4dd091744d1bf700bf33b1ff798', 'result': {}}
2023-10-28 12:38:11.785 DEBUG (MainThread) [custom_components.eufy_security.eufy_security_api] _set_products 1
2023-10-28 12:38:11.786 DEBUG (MainThread) [custom_components.eufy_security.eufy_security_api] domain - server - EventSourceType.server - start_listening - {} - {}
2023-10-28 12:38:11.788 DEBUG (MainThread) [custom_components.eufy_security.eufy_security_api] {'command': 'start_listening', 'messageId': 'start_listening.61bc1d1ddc754c6aac9ddc6567d92799'}
2023-10-28 12:38:11.789 DEBUG (MainThread) [custom_components.eufy_security.eufy_security_api] send_message - {'command': 'start_listening', 'messageId': 'start_listening.61bc1d1ddc754c6aac9ddc6567d92799'}
2023-10-28 12:38:12.532 DEBUG (MainThread) [custom_components.eufy_security.eufy_security_api] _on_message - {'type': 'result', 'success': True, 'messageId': 'start_listening.61bc1d1ddc754c6aac9ddc6567d92799', 'result': {'state': {'driver': {'version': '2.8.1', 'connected': True, 'pushConnected': True, 'mqttConnected': False}, 'stations': ['T8030P1323200EBD'], 'devices': ['T821451023342ABF']}}}
2023-10-28 12:38:12.554 DEBUG (MainThread) [custom_components.eufy_security.eufy_security_api] _set_products 2
2023-10-28 12:38:12.555 DEBUG (MainThread) [custom_components.eufy_security.eufy_security_api] domain - device - EventSourceType.product - device.get_properties - {'domain': 'device', 'serial_no': 'T821451023342ABF'} - {'serialNumber': 'T821451023342ABF'}
2023-10-28 12:38:12.558 DEBUG (MainThread) [custom_components.eufy_security.eufy_security_api] {'serialNumber': 'T821451023342ABF', 'command': 'device.get_properties', 'messageId': 'device.get_properties.e34f5153c9514d92980794f9060aec7f'}
2023-10-28 12:38:12.559 DEBUG (MainThread) [custom_components.eufy_security.eufy_security_api] send_message - {'serialNumber': 'T821451023342ABF', 'command': 'device.get_properties', 'messageId': 'device.get_properties.e34f5153c9514d92980794f9060aec7f'}
2023-10-28 12:38:12.643 DEBUG (MainThread) [custom_components.eufy_security.eufy_security_api] _on_message - {'type': 'result', 'success': True, 'messageId': 'device.get_properties.e34f5153c9514d92980794f9060aec7f', 'result': {'serialNumber': 'T821451023342ABF', 'properties': {'name': 'Front Doorbell', 'model': 'T8214', 'serialNumber': 'T821451023342ABF', 'hardwareVersion': '0.0.0.2', 'softwareVersion': '3.0.6.5', 'type': 94, 'stationSerialNumber': 'T8030P1323200EBD'}}}
2023-10-28 12:38:12.701 DEBUG (MainThread) [custom_components.eufy_security.eufy_security_api] domain - device - EventSourceType.product - device.get_properties_metadata - {'domain': 'device', 'serial_no': 'T821451023342ABF'} - {'serialNumber': 'T821451023342ABF'}
2023-10-28 12:38:12.703 DEBUG (MainThread) [custom_components.eufy_security.eufy_security_api] {'serialNumber': 'T821451023342ABF', 'command': 'device.get_properties_metadata', 'messageId': 'device.get_properties_metadata.65371eacd2964f6ea4ce398a549d8c23'}
2023-10-28 12:38:12.704 DEBUG (MainThread) [custom_components.eufy_security.eufy_security_api] send_message - {'serialNumber': 'T821451023342ABF', 'command': 'device.get_properties_metadata', 'messageId': 'device.get_properties_metadata.65371eacd2964f6ea4ce398a549d8c23'}
2023-10-28 12:38:12.768 DEBUG (MainThread) [custom_components.eufy_security.eufy_security_api] _on_message - {'type': 'result', 'success': True, 'messageId': 'device.get_properties_metadata.65371eacd2964f6ea4ce398a549d8c23', 'result': {'serialNumber': 'T821451023342ABF', 'properties': {'name': {'key': 'device_name', 'name': 'name', 'label': 'Name', 'readable': True, 'writeable': False, 'type': 'string'}, 'model': {'key': 'device_model', 'name': 'model', 'label': 'Model', 'readable': True, 'writeable': False, 'type': 'string'}, 'serialNumber': {'key': 'device_sn', 'name': 'serialNumber', 'label': 'Serial number', 'readable': True, 'writeable': False, 'type': 'string'}, 'type': {'key': 'device_type', 'name': 'type', 'label': 'Type', 'readable': True, 'writeable': False, 'type': 'number', 'states': {'0': 'Station', '1': 'Camera', '2': 'Sensor (T8900)', '3': 'Floodlight', '4': 'Camera E', '5': 'Doorbell', '7': 'Battery Doorbell', '8': 'Camera 2', '9': 'eufyCam S210 (eufyCam 2C)', '10': 'Motion Sensor (T8910)', '11': 'Keypad', '14': 'eufyCam S221 (eufyCam 2 Pro)', '15': 'eufyCam S220 (eufyCam 2C Pro)', '16': 'Battery Doorbell 2', '18': 'HomeBase S380 (HomeBase 3; T8030)', '19': 'eufyCam S330 (eufyCam 3)', '23': 'eufyCam S300 (eufyCam 3C)', '30': 'Indoor Camera', '31': 'Indoor Camera PT', '32': 'Solo Camera', '33': 'Solo Camera Pro', '34': 'Indoor Camera 1080', '35': 'Indoor Camera PT 1080', '37': 'Floodlight 8422', '38': 'Floodlight 8423', '39': 'Floodlight 2', '44': 'Outdoor Camera 1080P No Light', '45': 'Outdoor Camera 2k', '46': 'Outdoor Camera 1080P', '50': 'Lock Basic', '51': 'Lock Advanced', '52': 'Lock Basic No Finger', '53': 'Lock Basic Advanced No Finger', '54': 'Retrofit Smart Lock E110 (T8503)', '55': 'Video Smart Lock S330 (T8530)', '56': 'Lock 85A3', '57': 'Lock 8592', '58': 'Retrofit Smart Lock E130 (T8504)', '60': 'Solo Camera Spotlight 1080p', '61': 'Solo Camera Spotlight 2k', '62': 'Solo Camera Spotlight Solar', '90': 'Smart Drop S300 (T8790)', '91': 'Video Doorbell Dual', '93': 'Video Doorbell Dual (Wired)', '100': 'Indoor Cost Down Camera', '101': 'Camera Gun', '102': 'Camera Snail', '110': 'Starlight 4G LTE', '131': 'Camera Garage T8453 Common', '132': 'Garage-Control Cam E110 (T8452)', '133': 'Garage-Control Cam E120 (T8453)', '140': 'Smart Safe S10 (T7400)', '141': 'Smart Safe S12 (T7401)', '142': 'Smart Safe T7402', '143': 'Smart Safe T7403', '151': 'Wired Wall Light Cam S100 (T84A1)', '157': 'SmartTrack Link (T87B0)', '159': 'SmartTrack Card (T87B2)', '180': 'Lock T8502 / T8506', '10005': 'Solar Wall Light Cam S120 (T81A0)'}}, 'hardwareVersion': {'key': 'main_hw_version', 'name': 'hardwareVersion', 'label': 'Hardware version', 'readable': True, 'writeable': False, 'type': 'string'}, 'softwareVersion': {'key': 'main_sw_version', 'name': 'softwareVersion', 'label': 'Software version', 'readable': True, 'writeable': False, 'type': 'string'}, 'stationSerialNumber': {'key': 'station_sn', 'name': 'stationSerialNumber', 'label': 'Station serial number', 'readable': True, 'writeable': False, 'type': 'string'}}}}
2023-10-28 12:38:12.785 DEBUG (MainThread) [custom_components.eufy_security.eufy_security_api] domain - device - EventSourceType.product - device.get_commands - {'domain': 'device', 'serial_no': 'T821451023342ABF'} - {'serialNumber': 'T821451023342ABF'}
2023-10-28 12:38:12.787 DEBUG (MainThread) [custom_components.eufy_security.eufy_security_api] {'serialNumber': 'T821451023342ABF', 'command': 'device.get_commands', 'messageId': 'device.get_commands.28ef0ca80f8f4b23ac1c86ebcc535ccb'}
2023-10-28 12:38:12.787 DEBUG (MainThread) [custom_components.eufy_security.eufy_security_api] send_message - {'serialNumber': 'T821451023342ABF', 'command': 'device.get_commands', 'messageId': 'device.get_commands.28ef0ca80f8f4b23ac1c86ebcc535ccb'}
2023-10-28 12:38:12.822 DEBUG (MainThread) [custom_components.eufy_security.eufy_security_api] _on_message - {'type': 'result', 'success': True, 'messageId': 'device.get_commands.28ef0ca80f8f4b23ac1c86ebcc535ccb', 'result': {'serialNumber': 'T821451023342ABF', 'commands': []}}
2023-10-28 12:38:12.832 DEBUG (MainThread) [custom_components.eufy_security.eufy_security_api] _set_properties -T821451023342ABF - {'name': 'Front Doorbell', 'model': 'T8214', 'serialNumber': 'T821451023342ABF', 'hardwareVersion': '0.0.0.2', 'softwareVersion': '3.0.6.5', 'type': 94, 'stationSerialNumber': 'T8030P1323200EBD'}
2023-10-28 12:38:12.833 DEBUG (MainThread) [custom_components.eufy_security.eufy_security_api] domain - station - EventSourceType.product - station.get_properties - {'domain': 'station', 'serial_no': 'T8030P1323200EBD'} - {'serialNumber': 'T8030P1323200EBD'}
2023-10-28 12:38:12.836 DEBUG (MainThread) [custom_components.eufy_security.eufy_security_api] {'serialNumber': 'T8030P1323200EBD', 'command': 'station.get_properties', 'messageId': 'station.get_properties.74cc87c0a9034d5d87dbd17a235dfca0'}
2023-10-28 12:38:12.836 DEBUG (MainThread) [custom_components.eufy_security.eufy_security_api] send_message - {'serialNumber': 'T8030P1323200EBD', 'command': 'station.get_properties', 'messageId': 'station.get_properties.74cc87c0a9034d5d87dbd17a235dfca0'}
2023-10-28 12:38:12.867 DEBUG (MainThread) [custom_components.eufy_security.eufy_security_api] _on_message - {'type': 'result', 'success': True, 'messageId': 'station.get_properties.74cc87c0a9034d5d87dbd17a235dfca0', 'result': {'serialNumber': 'T8030P1323200EBD', 'properties': {'name': '87 Chapin HB', 'model': 'T8030', 'serialNumber': 'T8030P1323200EBD', 'type': 18, 'hardwareVersion': 'V05', 'softwareVersion': '3.3.2.6', 'macAddress': '0417B68E6AE2', 'timeFormat': 1, 'alarmVolume': 26, 'alarm': False, 'alarmType': 0, 'alarmArmed': False, 'alarmArmDelay': 0, 'alarmDelay': 0, 'alarmDelayType': 0, 'guardMode': 1, 'sdStatus': 4294967148, 'notificationSwitchModeSchedule': True, 'notificationSwitchModeGeofence': True, 'notificationSwitchModeApp': True, 'notificationSwitchModeKeypad': True, 'notificationStartAlarmDelay': False, 'alarmTone': 1, 'lanIpAddress': '192.168.2.223', 'sdCapacity': 0, 'sdCapacityAvailable': 0, 'currentMode': 1, 'promptVolume': 18}}}
2023-10-28 12:38:12.889 DEBUG (MainThread) [custom_components.eufy_security.eufy_security_api] domain - station - EventSourceType.product - station.get_properties_metadata - {'domain': 'station', 'serial_no': 'T8030P1323200EBD'} - {'serialNumber': 'T8030P1323200EBD'}
2023-10-28 12:38:12.890 DEBUG (MainThread) [custom_components.eufy_security.eufy_security_api] {'serialNumber': 'T8030P1323200EBD', 'command': 'station.get_properties_metadata', 'messageId': 'station.get_properties_metadata.ae05ec147036474993a161bf0f62f7c8'}
2023-10-28 12:38:12.891 DEBUG (MainThread) [custom_components.eufy_security.eufy_security_api] send_message - {'serialNumber': 'T8030P1323200EBD', 'command': 'station.get_properties_metadata', 'messageId': 'station.get_properties_metadata.ae05ec147036474993a161bf0f62f7c8'}
2023-10-28 12:38:12.907 DEBUG (MainThread) [custom_components.eufy_security.eufy_security_api] _on_message - {'type': 'result', 'success': True, 'messageId': 'station.get_properties_metadata.ae05ec147036474993a161bf0f62f7c8', 'result': {'serialNumber': 'T8030P1323200EBD', 'properties': {'name': {'key': 'station_name', 'name': 'name', 'label': 'Name', 'readable': True, 'writeable': False, 'type': 'string'}, 'model': {'key': 'station_model', 'name': 'model', 'label': 'Model', 'readable': True, 'writeable': False, 'type': 'string'}, 'serialNumber': {'key': 'station_sn', 'name': 'serialNumber', 'label': 'Serial number', 'readable': True, 'writeable': False, 'type': 'string'}, 'type': {'key': 'device_type', 'name': 'type', 'label': 'Type', 'readable': True, 'writeable': False, 'type': 'number', 'states': {'0': 'Station', '1': 'Camera', '2': 'Sensor (T8900)', '3': 'Floodlight', '4': 'Camera E', '5': 'Doorbell', '7': 'Battery Doorbell', '8': 'Camera 2', '9': 'eufyCam S210 (eufyCam 2C)', '10': 'Motion Sensor (T8910)', '11': 'Keypad', '14': 'eufyCam S221 (eufyCam 2 Pro)', '15': 'eufyCam S220 (eufyCam 2C Pro)', '16': 'Battery Doorbell 2', '18': 'HomeBase S380 (HomeBase 3; T8030)', '19': 'eufyCam S330 (eufyCam 3)', '23': 'eufyCam S300 (eufyCam 3C)', '30': 'Indoor Camera', '31': 'Indoor Camera PT', '32': 'Solo Camera', '33': 'Solo Camera Pro', '34': 'Indoor Camera 1080', '35': 'Indoor Camera PT 1080', '37': 'Floodlight 8422', '38': 'Floodlight 8423', '39': 'Floodlight 2', '44': 'Outdoor Camera 1080P No Light', '45': 'Outdoor Camera 2k', '46': 'Outdoor Camera 1080P', '50': 'Lock Basic', '51': 'Lock Advanced', '52': 'Lock Basic No Finger', '53': 'Lock Basic Advanced No Finger', '54': 'Retrofit Smart Lock E110 (T8503)', '55': 'Video Smart Lock S330 (T8530)', '56': 'Lock 85A3', '57': 'Lock 8592', '58': 'Retrofit Smart Lock E130 (T8504)', '60': 'Solo Camera Spotlight 1080p', '61': 'Solo Camera Spotlight 2k', '62': 'Solo Camera Spotlight Solar', '90': 'Smart Drop S300 (T8790)', '91': 'Video Doorbell Dual', '93': 'Video Doorbell Dual (Wired)', '100': 'Indoor Cost Down Camera', '101': 'Camera Gun', '102': 'Camera Snail', '110': 'Starlight 4G LTE', '131': 'Camera Garage T8453 Common', '132': 'Garage-Control Cam E110 (T8452)', '133': 'Garage-Control Cam E120 (T8453)', '140': 'Smart Safe S10 (T7400)', '141': 'Smart Safe S12 (T7401)', '142': 'Smart Safe T7402', '143': 'Smart Safe T7403', '151': 'Wired Wall Light Cam S100 (T84A1)', '157': 'SmartTrack Link (T87B0)', '159': 'SmartTrack Card (T87B2)', '180': 'Lock T8502 / T8506', '10005': 'Solar Wall Light Cam S120 (T81A0)'}}, 'hardwareVersion': {'key': 'main_hw_version', 'name': 'hardwareVersion', 'label': 'Hardware version', 'readable': True, 'writeable': False, 'type': 'string'}, 'softwareVersion': {'key': 'main_sw_version', 'name': 'softwareVersion', 'label': 'Software version', 'readable': True, 'writeable': False, 'type': 'string'}, 'lanIpAddress': {'key': 1176, 'name': 'lanIpAddress', 'label': 'LAN IP Address', 'readable': True, 'writeable': False, 'type': 'string'}, 'macAddress': {'key': 'wifi_mac', 'name': 'macAddress', 'label': 'MAC Address', 'readable': True, 'writeable': False, 'type': 'string'}, 'guardMode': {'key': 1224, 'name': 'guardMode', 'label': 'Guard Mode', 'readable': True, 'writeable': True, 'type': 'number', 'states': {'0': 'Away', '1': 'Home', '2': 'Schedule', '3': 'Custom 1', '4': 'Custom 2', '5': 'Custom 3', '47': 'Geofencing', '63': 'Disarmed'}}, 'currentMode': {'key': 1151, 'name': 'currentMode', 'label': 'Current Mode', 'readable': True, 'writeable': False, 'type': 'number', 'states': {'0': 'Away', '1': 'Home', '3': 'Custom 1', '4': 'Custom 2', '5': 'Custom 3', '63': 'Disarmed'}}, 'timeFormat': {'key': 1253, 'name': 'timeFormat', 'label': 'Time Format', 'readable': True, 'writeable': True, 'type': 'number', 'states': {'0': '12h', '1': '24h'}, 'default': 0}, 'promptVolume': {'key': 1292, 'name': 'promptVolume', 'label': 'Prompt Volume', 'readable': True, 'writeable': True, 'type': 'number', 'min': 0, 'max': 26}, 'alarmVolume': {'key': 1235, 'name': 'alarmVolume', 'label': 'Alarm Volume', 'readable': True, 'writeable': True, 'type': 'number', 'min': 1, 'max': 26, 'default': 26}, 'alarmTone': {'key': 1281, 'name': 'alarmTone', 'label': 'Alarm Tone', 'readable': True, 'writeable': True, 'type': 'number', 'states': {'1': 'Alarm sound 1', '2': 'Alarm sound 2'}}, 'notificationSwitchModeSchedule': {'key': 1283, 'name': 'notificationSwitchModeSchedule', 'label': 'Notification Switch Mode Schedule', 'readable': True, 'writeable': True, 'type': 'boolean'}, 'notificationSwitchModeGeofence': {'key': 1283, 'name': 'notificationSwitchModeGeofence', 'label': 'Notification Switch Mode Geofence', 'readable': True, 'writeable': True, 'type': 'boolean'}, 'notificationSwitchModeApp': {'key': 1283, 'name': 'notificationSwitchModeApp', 'label': 'Notification Switch Mode App', 'readable': True, 'writeable': True, 'type': 'boolean'}, 'notificationSwitchModeKeypad': {'key': 1283, 'name': 'notificationSwitchModeKeypad', 'label': 'Notification Switch Mode Keypad', 'readable': True, 'writea
2023-10-28 12:38:12.913 DEBUG (MainThread) [custom_components.eufy_security.eufy_security_api] domain - station - EventSourceType.product - station.get_commands - {'domain': 'station', 'serial_no': 'T8030P1323200EBD'} - {'serialNumber': 'T8030P1323200EBD'}
2023-10-28 12:38:12.914 DEBUG (MainThread) [custom_components.eufy_security.eufy_security_api] {'serialNumber': 'T8030P1323200EBD', 'command': 'station.get_commands', 'messageId': 'station.get_commands.76220cddc328471884f920fb3dc52096'}
2023-10-28 12:38:12.914 DEBUG (MainThread) [custom_components.eufy_security.eufy_security_api] send_message - {'serialNumber': 'T8030P1323200EBD', 'command': 'station.get_commands', 'messageId': 'station.get_commands.76220cddc328471884f920fb3dc52096'}
2023-10-28 12:38:12.924 DEBUG (MainThread) [custom_components.eufy_security.eufy_security_api] _on_message - {'type': 'result', 'success': True, 'messageId': 'station.get_commands.76220cddc328471884f920fb3dc52096', 'result': {'serialNumber': 'T8030P1323200EBD', 'commands': ['stationReboot', 'stationTriggerAlarmSound', 'stationDownloadImage', 'stationDatabaseQueryLatestInfo', 'stationDatabaseQueryLocal', 'stationDatabaseCoundByDate', 'stationDatabaseDelete']}}
2023-10-28 12:38:12.929 DEBUG (MainThread) [custom_components.eufy_security.eufy_security_api] _set_properties -T8030P1323200EBD - {'name': '87 Chapin HB', 'model': 'T8030', 'serialNumber': 'T8030P1323200EBD', 'type': 18, 'hardwareVersion': 'V05', 'softwareVersion': '3.3.2.6', 'macAddress': '0417B68E6AE2', 'timeFormat': 1, 'alarmVolume': 26, 'alarm': False, 'alarmType': 0, 'alarmArmed': False, 'alarmArmDelay': 0, 'alarmDelay': 0, 'alarmDelayType': 0, 'guardMode': 1, 'sdStatus': 4294967148, 'notificationSwitchModeSchedule': True, 'notificationSwitchModeGeofence': True, 'notificationSwitchModeApp': True, 'notificationSwitchModeKeypad': True, 'notificationStartAlarmDelay': False, 'alarmTone': 1, 'lanIpAddress': '192.168.2.223', 'sdCapacity': 0, 'sdCapacityAvailable': 0, 'currentMode': 1, 'promptVolume': 18}
2023-10-28 12:38:29.456 WARNING (MainThread) [zigpy.application] Zigbee channel 15 utilization is 99.51%!
2023-10-28 12:38:29.457 WARNING (MainThread) [zigpy.application] If you are having problems joining new devices, are missing sensor updates, or have issues keeping devices joined, ensure your coordinator is away from interference sources such as USB 3.0 devices, SSDs, WiFi routers, etc.
2023-10-28 12:38:57.265 WARNING (MainThread) [homeassistant.components.zha.core.cluster_handlers] [0xC80E:11:0x0006]: async_initialize: all attempts have failed: [DeliveryError('Failed to deliver message: <EmberStatus.DELIVERY_FAILED: 102>'), DeliveryError('Failed to deliver message: <EmberStatus.DELIVERY_FAILED: 102>'), DeliveryError('Failed to deliver message: <EmberStatus.DELIVERY_FAILED: 102>'), DeliveryError('Failed to deliver message: <EmberStatus.DELIVERY_FAILED: 102>')]
2023-10-28 12:38:57.294 WARNING (MainThread) [homeassistant.components.zha.core.cluster_handlers] [0xC80E:11:0x0300]: async_initialize: all attempts have failed: [DeliveryError('Failed to deliver message: <EmberStatus.DELIVERY_FAILED: 102>'), DeliveryError('Failed to deliver message: <EmberStatus.DELIVERY_FAILED: 102>'), DeliveryError('Failed to deliver message: <EmberStatus.DELIVERY_FAILED: 102>'), DeliveryError('Failed to deliver message: <EmberStatus.DELIVERY_FAILED: 102>')]
2023-10-28 12:38:57.859 WARNING (MainThread) [homeassistant.components.zha.core.cluster_handlers] [0xC80E:11:0x0008]: async_initialize: all attempts have failed: [DeliveryError('Failed to deliver message: <EmberStatus.DELIVERY_FAILED: 102>'), DeliveryError('Failed to deliver message: <EmberStatus.DELIVERY_FAILED: 102>'), DeliveryError('Failed to deliver message: <EmberStatus.DELIVERY_FAILED: 102>'), DeliveryError('Failed to deliver message: <EmberStatus.DELIVERY_FAILED: 102>')]

- Logs from Eufy Security Add-on (either from Add-ons page of Home Assistant or Docker output):

s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
2023-10-28 16:09:08.664  INFO  Eufy Security server listening on host 0.0.0.0, port 3000 
2023-10-28 16:09:09.130  INFO  Requested verification code for 2FA 
2023-10-28 16:09:37.256  INFO  Client disconnected with ip: 127.0.0.1 port: 36394 code: 1000 reason: Normal Closure 
2023-10-28 16:10:27.510  INFO  2FA authentication successfully done. Device trusted. 
2023-10-28 16:10:29.888  INFO  Connected to station T8030P1323200EBD on host 192.168.2.223 and port 18082 
2023-10-28 16:10:30.277  ERROR onStationDatabaseQueryLatest Error 
{
  error: {
    message: "DeviceNotFoundError: Device doesn't exists",
    stacktrace: "DeviceNotFoundError: Device doesn't exists\n" +
      '    at EufySecurity.getDevice (/usr/src/app/node_modules/eufy-security-client/build/eufysecurity.js:372:15)\n' +
      '    at EufySecurity.onStationDatabaseQueryLatest (/usr/src/app/node_modules/eufy-security-client/build/eufysecurity.js:2344:26)\n' +
      '    at Station.<anonymous> (/usr/src/app/node_modules/eufy-security-client/build/eufysecurity.js:479:97)\n' +
      '    at Station.emit (node:events:525:35)\n' +
      '    at Station.emit (node:domain:489:12)\n' +
      '    at Station.onDatabaseQueryLatest (/usr/src/app/node_modules/eufy-security-client/build/http/station.js:7377:14)\n' +
      '    at P2PClientProtocol.<anonymous> (/usr/src/app/node_modules/eufy-security-client/build/http/station.js:78:80)\n' +
      '    at P2PClientProtocol.emit (node:events:513:28)\n' +
      '    at P2PClientProtocol.emit (node:domain:489:12)\n' +
      '    at P2PClientProtocol.handleDataControl (/usr/src/app/node_modules/eufy-security-client/build/p2p/session.js:1860:42)'
  },
  stationSN: 'T8030P1323200EBD',
  returnCode: 0
}
2023-10-28 16:10:41.515  INFO  Push notification connection successfully established 
2023-10-28 16:36:36.629  INFO  Client disconnected with ip: 127.0.0.1 port: 47352 code: 1006 reason: Abnormal Closure 
2023-10-28 16:36:36.640  INFO  Client disconnected with ip: 127.0.0.1 port: 54724 code: 1006 reason: Abnormal Closure 
2023-10-28 16:36:36.646  INFO  Client disconnected with ip: 127.0.0.1 port: 36400 code: 1006 reason: Abnormal Closure 

- Would you share your device with me in case further debugging required? (Yes/No):
Maybe

**Additional context**

Add any other context about the problem goes here. Mainly, share everything as log files and use screenshots as last resort.

**Comment by ianisms** [comment]
I see this issue in eufy_security_client: https://github.com/bropat/eufy-security-client/issues/387
