### ISSUE TITLE
Setting up Eufy in Hacs: Log: File "/config/custom_components/eufy_security/const.py", line 37, in <module>     Platform.IMAGE,

### ISSUE THREAD

**Issue by Volvofan63** [fuatakgun/eufy_security#976]
**Describe the bug**
When configuring the eufy intergration i got the message: 
Config-flow could not be loaded : {"message":"Invalid handler specified"}

When checking the log in HA:

`2023-11-02 20:27:09.361 ERROR (MainThread) [homeassistant.loader] Unexpected exception importing platform custom_components.eufy_security.config_flow
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 833, in get_platform
    cache[full_name] = self._import_platform(platform_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 850, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1128, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/config/custom_components/eufy_security/__init__.py", line 11, in <module>
    from .const import COORDINATOR, DOMAIN, PLATFORMS
  File "/config/custom_components/eufy_security/const.py", line 37, in <module>
    Platform.IMAGE,
    ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/enum.py", line 786, in __getattr__
    raise AttributeError(name) from None
AttributeError: IMAGE
2023-11-02 20:27:09.368 ERROR (MainThread) [homeassistant.config_entries] Error occurred loading flow for integration eufy_security: Exception importing custom_components.eufy_security.config_flow`

**Expected behavior**
Provide me the config window for IP setup.

**Additional information**

Go to Settings -> System -> Repairs -> Click on 3 dots (...) -> System Information and get Version and Installation Type to below fields;
- Home Assistant Installation Type (OS - Supvervised - Core): Core (Home Assistant Container)
- Home Assistant Core Version:  core-2023.6.1
- Eufy Security Add-on Version: 7.7.2
- Eufy Security Integration Version: 7.7.2

**Comment by fuatakgun** [comment]
You are using old version of home assistant right? You need to move a fresh one

**Comment by Volvofan63** [comment]
Thanks for your quick response.
An update from Homeassitant was indeed the solution.

**Comment by Volvofan63** [comment]
The issue can be closed
