### ISSUE TITLE
Unable to view video feed from doorbell

### ISSUE THREAD

**Issue by bangcrash** [fuatakgun/eufy_security#988]
Not able to view the video stream from T8200N0021050F39 doorbell camera.

Error in the HA system log:

Logger: custom_components.eufy_security.eufy_security_api
Source: custom_components/eufy_security/eufy_security_api/p2p_stream_handler.py:107
Integration: Eufy Security ([documentation](https://github.com/fuatakgun/eufy_security), [issues](https://github.com/fuatakgun/eufy_security/issues))
First occurred: 12:14:16 (6 occurrences)
Last logged: 12:27:30

Exception [Errno 104] Connection reset by peer - traceback: Traceback (most recent call last): File "/config/custom_components/eufy_security/eufy_security_api/p2p_stream_handler.py", line 103, in setup client_socket.sendall(bytearray(self.camera.video_queue.get())) ConnectionResetError: [Errno 104] Connection reset by peer
Exception [Errno 32] Broken pipe - traceback: Traceback (most recent call last): File "/config/custom_components/eufy_security/eufy_security_api/p2p_stream_handler.py", line 103, in setup client_socket.sendall(bytearray(self.camera.video_queue.get())) BrokenPipeError: [Errno 32] Broken pipe

**To reproduce**

I am using the recommended dashboard camera view from the readme file.

When the dashboard card is clicked nothing happens

**Expected behavior**

The video stream should start and be visible on the HA dashboard

**Additional information**

Go to Settings -> System -> Repairs -> Click on 3 dots (...) -> System Information and get Version and Installation Type to below fields;
- Home Assistant Installation Type (OS - Supvervised - Core): Home Assistant OS
- Home Assistant Core Version: 2023.11.1
- Eufy Security Add-on Version: 1.7.1
- Eufy Security Integration Version: 7.7.3

Hardware Information;
- Camera Model: T8200N0021050F39

- Live Streaming Protocol (RTSP/P2P):  P2P

- Debug Logs from Home Assistant (https://github.com/fuatakgun/eufy_security/discussions/624) - Without this, I will automatically resolve this issue:

 2023-11-08 12:27:00.142 INFO (MainThread) [aiortsp.rtsp.reader] try loading stream rtsp://127.0.0.1:8554/T8200N0021050F39
2023-11-08 12:27:00.143 INFO (MainThread) [aiortsp.rtsp.reader] connected!
2023-11-08 12:27:00.143 INFO (MainThread) [aiortsp.rtsp.reader] receiving interleaved RTP (0) and RTCP (1)
2023-11-08 12:27:00.144 INFO (MainThread) [aiortsp.rtsp.reader] session options: {'RECORD', 'TEARDOWN', 'OPTIONS', 'DESCRIBE', 'ANNOUNCE', 'SETUP', 'PAUSE', 'PLAY'}
2023-11-08 12:27:00.145 INFO (MainThread) [aiortsp.rtsp.reader] connection to RTSP server 127.0.0.1:8554 closed (error: None)
2023-11-08 12:27:00.691 INFO (MainThread) [aiortsp.rtsp.reader] try loading stream rtsp://127.0.0.1:8554/T8200N0021050F39
2023-11-08 12:27:00.696 INFO (MainThread) [aiortsp.rtsp.reader] connected!
2023-11-08 12:27:00.696 INFO (MainThread) [aiortsp.rtsp.reader] receiving interleaved RTP (0) and RTCP (1)
2023-11-08 12:27:00.697 INFO (MainThread) [aiortsp.rtsp.reader] session options: {'RECORD', 'TEARDOWN', 'OPTIONS', 'DESCRIBE', 'ANNOUNCE', 'SETUP', 'PAUSE', 'PLAY'}
2023-11-08 12:27:00.698 INFO (MainThread) [aiortsp.rtsp.reader] connection to RTSP server 127.0.0.1:8554 closed (error: None)
2023-11-08 12:27:01.200 INFO (MainThread) [aiortsp.rtsp.reader] try loading stream rtsp://127.0.0.1:8554/T8200N0021050F39
2023-11-08 12:27:01.201 INFO (MainThread) [aiortsp.rtsp.reader] connected!
2023-11-08 12:27:01.201 INFO (MainThread) [aiortsp.rtsp.reader] receiving interleaved RTP (0) and RTCP (1)
2023-11-08 12:27:01.202 INFO (MainThread) [aiortsp.rtsp.reader] session options: {'RECORD', 'TEARDOWN', 'OPTIONS', 'DESCRIBE', 'ANNOUNCE', 'SETUP', 'PAUSE', 'PLAY'}
2023-11-08 12:27:01.203 INFO (MainThread) [aiortsp.rtsp.reader] connection to RTSP server 127.0.0.1:8554 closed (error: None)
2023-11-08 12:27:01.212 ERROR (Thread-107 (setup)) [custom_components.eufy_security.eufy_security_api] Exception [Errno 32] Broken pipe - traceback: Traceback (most recent call last):
  File "/config/custom_components/eufy_security/eufy_security_api/p2p_stream_handler.py", line 103, in setup
    client_socket.sendall(bytearray(self.camera.video_queue.get()))
BrokenPipeError: [Errno 32] Broken pipe

2023-11-08 12:27:01.706 INFO (MainThread) [aiortsp.rtsp.reader] try loading stream rtsp://127.0.0.1:8554/T8200N0021050F39
2023-11-08 12:27:01.707 INFO (MainThread) [aiortsp.rtsp.reader] connected!
2023-11-08 12:27:01.707 INFO (MainThread) [aiortsp.rtsp.reader] receiving interleaved RTP (0) and RTCP (1)
2023-11-08 12:27:01.708 INFO (MainThread) [aiortsp.rtsp.reader] session options: {'RECORD', 'TEARDOWN', 'OPTIONS', 'DESCRIBE', 'ANNOUNCE', 'SETUP', 'PAUSE', 'PLAY'}
2023-11-08 12:27:01.709 INFO (MainThread) [aiortsp.rtsp.reader] connection to RTSP server 127.0.0.1:8554 closed (error: None)
2023-11-08 12:27:02.211 INFO (MainThread) [aiortsp.rtsp.reader] try loading stream rtsp://127.0.0.1:8554/T8200N0021050F39
2023-11-08 12:27:02.212 INFO (MainThread) [aiortsp.rtsp.reader] connected!
2023-11-08 12:27:02.212 INFO (MainThread) [aiortsp.rtsp.reader] receiving interleaved RTP (0) and RTCP (1)
2023-11-08 12:27:02.214 INFO (MainThread) [aiortsp.rtsp.reader] session options: {'RECORD', 'TEARDOWN', 'OPTIONS', 'DESCRIBE', 'ANNOUNCE', 'SETUP', 'PAUSE', 'PLAY'}
2023-11-08 12:27:02.215 INFO (MainThread) [aiortsp.rtsp.reader] connection to RTSP server 127.0.0.1:8554 closed (error: None)
2023-11-08 12:27:02.717 INFO (MainThread) [aiortsp.rtsp.reader] try loading stream rtsp://127.0.0.1:8554/T8200N0021050F39
2023-11-08 12:27:02.719 INFO (MainThread) [aiortsp.rtsp.reader] connected!
2023-11-08 12:27:02.719 INFO (MainThread) [aiortsp.rtsp.reader] receiving interleaved RTP (0) and RTCP (1)
2023-11-08 12:27:02.719 INFO (MainThread) [aiortsp.rtsp.reader] session options: {'RECORD', 'TEARDOWN', 'OPTIONS', 'DESCRIBE', 'ANNOUNCE', 'SETUP', 'PAUSE', 'PLAY'}
2023-11-08 12:27:02.720 INFO (MainThread) [aiortsp.rtsp.reader] connection to RTSP server 127.0.0.1:8554 closed (error: None)
2023-11-08 12:27:03.222 INFO (MainThread) [aiortsp.rtsp.reader] try loading stream rtsp://127.0.0.1:8554/T8200N0021050F39
2023-11-08 12:27:03.223 INFO (MainThread) [aiortsp.rtsp.reader] connected!
2023-11-08 12:27:03.224 INFO (MainThread) [aiortsp.rtsp.reader] receiving interleaved RTP (0) and RTCP (1)
2023-11-08 12:27:03.225 INFO (MainThread) [aiortsp.rtsp.reader] session options: {'RECORD', 'TEARDOWN', 'OPTIONS', 'DESCRIBE', 'ANNOUNCE', 'SETUP', 'PAUSE', 'PLAY'}
 
[eufy_security debug.txt](https://github.com/fuatakgun/eufy_security/files/13296797/eufy_security.debug.txt)
Full debug log in the attached text file

- Logs from Eufy Security Add-on (either from Add-ons page of Home Assistant or Docker output):

s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
2023-11-08 12:24:12.555  INFO  Eufy Security server listening on host 0.0.0.0, port 3000 
2023-11-08 12:24:15.202  INFO  Connected to station T8200N0021050F39 on host 10.69.10.1 and port 28095 
2023-11-08 12:24:16.563  INFO  Push notification connection successfully established 
2023-11-08 12:24:45.369  INFO  Client disconnected with ip: 127.0.0.1 port: 39500 code: 1000 reason: Normal Closure 

- Would you share your device with me in case further debugging required? (Yes/No): Yes

**Additional context**

Add any other context about the problem goes here. Mainly, share everything as log files and use screenshots as last resort.

**Comment by fuatakgun** [comment]
It is not working at all or you are having occasion issues

**Comment by bangcrash** [comment]
It's not working at all at the moment.  I have tried restarting the RSTP Server addon and the Eufy Security WS addon, then reloading the integration which has fixed problems in the past but not this time.

**Comment by fuatakgun** [comment]
I believe you have signed for office hours for this Friday, if it is ok for you, can you share your device beforehand so i can take a look at it locally?

**Comment by bangcrash** [comment]
Just shared with you.

**Comment by fuatakgun** [comment]
do you have any firewall or DNS configuration on your side blocking me to access your device remotely?

```
WARN Tried all hosts, no connection could be established to station T8200N0021050F39.
2023-11-09 08:49:01.984  INFO  Timeout connecting to station T8200N0021050F39
```

**Comment by bangcrash** [comment]
I have a firewall and the device is on a separate IoT VLAN.  I have no
problems accessing it remotely from my own phone and the device has access
to the internet from that VLAN.  Do you know how you are making the
connection?  I assumed that it would be proxied by the Eufy cloud service,
is that not the case?

**Comment by fuatakgun** [comment]
I am using eufy security addon locally from my home network and it is failing to make a connection to your local device. I can also access from eufy app but add-on is failing to do so.

Please move them out of limited vlan and let me know. I want to eliminate network related things to understand if i should fix anything on integration side.

**Comment by bangcrash** [comment]
Please could you help me to understand here?  You are not going to be able
to directly access a device on my network unless I use port forwarding to
publish it to the outside world.  How can the addon access a device on my
local network directly from your network without either a VPN connection or
my device being exposed through my firewall?  Just moving the device from
one VLAN to the other won't fix this as it will still be protected by my
perimeter firewall.  I'm happy to reconfigure the device but I need to know
how it needs to be configured to give you access.

**Comment by fuatakgun** [comment]
I have zero knowledge around VLANs and networks but I have accessed many remote devices around the world (USA, Austria, Europe) using add-on because add-on is trying cloud and local connections parallel to each other. 

But, I cannot access your device and I do not want to spend any time and energy to find out what kind of network setup needed to access it.

Maybe even after moving it to unrestricted VLAN, I still cannot access it, I do not know.

**Comment by fuatakgun** [comment]
anyway, let me know when you are interested to do so or else, I do not have a solution to fix the network issue or streaming issue.

**Comment by bangcrash** [comment]
I'm very happy to make changes to get this to work but I just don't know
what changes to make.  You will not be able to connect directly to anything
on my network and that would be the same for the majority of people as
their router/firewall will block the direct connection into the network and
you would need to know my public IP address to make that connection as
well.  My device is communicating properly with the Eufy cloud service as I
can access it using the Eufy app when I am not on my home network.  I can
move the device over to another VLAN but I don't think that will change
anything though.  I will try it when I get home from work this evening
and let you know.

**Comment by fuatakgun** [comment]
https://github.com/bropat/eufy-security-ws/issues/60#issuecomment-1019336675

As i said, i just want to be sure that vlan is not a specific issue for us here. I want to focus on the integration itself.

**Comment by novisys** [comment]
Hi
I have same problem , can you tell me how to give you the needed access to my doorbell to analyse it ?
